# SPDX-License-Identifier: GPL-2.0-only

# ARM Architecture

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "pwm-exynos",
    out = "pwm-exynos.ko",
    conditional_srcs = {
        "CONFIG_PWM_EXYNOS": {
            True: [
                "pwm-exynos.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-cpupm",
    ],
)
