#ifndef VPN_RPC_SERVICE_CLIENT_NANOPB_H
#define VPN_RPC_SERVICE_CLIENT_NANOPB_H

#include "pw_rpc_c/pw_rpc_call.h"
#include "pw_rpc_c/pw_rpc_client.h"
#include "pw_rpc_c/pw_status.h"

#ifdef __cplusplus
extern "C" {
#endif
/// @brief Initiates an connection for the `VpnRpc::Connect` RPC service.
///
/// This function asynchronously establishes a bidirectional streaming RPC
/// connection from the `client` instance.
///
/// Once the connection is established, subsequent messages can be sent using
/// the returned `call_id` through the functions provided by pw_rpc_c for
/// sending CLIENT_STREAM messages.
///
/// @param[in] client A pointer to the PwRpcClient object responsible for
/// managing the communication channel. Must not be NULL.
///
/// @param[in] on_next A callback function invoked whenever a new message is
/// received from the VPN service.
///
/// @param[in] on_complete A callback function called when the RPC connection
/// finished normally.
///
/// @param[in] on_error A callback function called when the RPC is
/// terminated due to an error.
///
/// @param[out] call_id A pointer to the memory that will store the unique
/// identifier assigned to this RPC call upon successful initiation.
///
/// @retval @pw_status{OK} if the RPC invocation to initiate the connection
/// was successful.
///
/// @retval @pw_status{INVALID_ARGUMENT} if the provided `client` pointer
/// is null.
///
/// @retval Other error codes may be returned if there are issues with the
/// underlying RPC channel.
inline __attribute__((weak)) PwStatus
VpnRpcConnect(PwRpcClient* client, PwRpcCallOnNextCallback on_next,
              PwRpcCallOnCompleteCallback on_complete,
              PwRpcCallOnErrorCallback on_error, uint32_t* call_id) {
  // Service and method IDs generated by the pw_protobuf compiler.
  // TODO(b/351242791): These hard-coded values should be replaced with values
  //                    from a C-compatible header once the pw_protobuf compiler
  //                    supports it.
  const uint32_t vpn_rpc_service_id = 0x5188e0b8u;
  const uint32_t vpn_rpc_connect_method_id = 0xda8b723du;

  if (!client) {
    return kPwStatusInvalidArgument;
  }

  // Allow `NULL` for compatibility with C.
  // NOLINTBEGIN(modernize-use-nullptr)

  // Initiate the streaming RPC call with a REQUEST packet without payload.
  // The provided callbacks will handle incoming messages, completion, and errors.
  // The assigned call ID is stored in the provided call_id pointer.
  return PwRpcClientInvokeStreaming(
      client, vpn_rpc_service_id, vpn_rpc_connect_method_id,
      // Empty payload. (with null buffer and zero length)
      NULL, 0, on_next, on_complete, on_error,
      // Unused `call_context` parameter.
      NULL, call_id);

  // NOLINTEND(modernize-use-nullptr)
}

#ifdef __cplusplus
}
#endif
#endif  // VPN_RPC_SERVICE_CLIENT_NANOPB_H
