# SPDX-License-Identifier: GPL-2.0-or-later

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

filegroup(
    name = "sec.kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/soc/gs:__pkg__",
    ],
)

ddk_module(
    name = "sec_touch",
    srcs = glob([
        "**/*.h",
    ]) + [
        "sec_cmd.c",
        "sec_ts.c",
        "sec_ts_fn.c",
        "sec_ts_fw.c",
        "sec_ts_only_vendor.c",
    ],
    out = "sec_touch.ko",
    conditional_srcs = {
        "CONFIG_GOOG_TOUCH_INTERFACE": {
            True: [
                "sec_ts_goog.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    local_defines = [
        "DYNAMIC_DEBUG_MODULE",
    ],
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:systrace",
        "//private/google-modules/touch/common:ddk_headers",
        "//private/google-modules/touch/common:goog_touch_interface",
    ],
)
