# SPDX-License-Identifier: GPL-2.0-only

"""
Kernel targets used by Pixel kernel codebase.
"""

KERNEL_TARGETS = [
    # keep sorted
    "Makefile",
    "aarch64_additional_kmi_symbol_lists",
    "all_headers_aarch64",
    "arch/arm64/kvm/hyp/include/nvhe/alloc.h",
    "arch/arm64/kvm/hyp/include/nvhe/gfp.h",
    "arch/arm64/kvm/hyp/include/nvhe/mem_protect.h",
    "arch/arm64/kvm/hyp/include/nvhe/memory.h",
    "arch/arm64/kvm/hyp/include/nvhe/mm.h",
    "arch/arm64/kvm/hyp/include/nvhe/pkvm.h",
    "arch/arm64/kvm/hyp/include/nvhe/refcount.h",
    "arch/arm64/kvm/hyp/include/nvhe/rwlock.h",
    "arch/arm64/kvm/hyp/include/nvhe/trap_handler.h",
    "drivers/android/binder_internal.h",
    "drivers/android/debug_kinfo.h",
    "drivers/hwtracing/coresight/coresight-etm4x.h",
    "drivers/hwtracing/coresight/coresight-priv.h",
    "drivers/iommu/dma-iommu.h",
    "drivers/pinctrl/pinctrl-utils.h",
    "drivers/pinctrl/samsung/pinctrl-samsung.h",
    "drivers/spi/spi-dw.h",
    "drivers/ufs/core/ufshcd-crypto.h",
    "drivers/ufs/host/ufshcd-pltfrm.h",
    "drivers/usb/core/hub.h",
    "drivers/usb/dwc3/gadget.h",
    "drivers/usb/gadget/configfs.h",
    "drivers/usb/host/xhci.h",
    "drivers/usb/host/xhci-mvebu.h",
    "drivers/usb/host/xhci-plat.h",
    "include/uapi/drm/drm_fourcc.h",
    "include/uapi/sound/asound.h",
    "include/uapi/sound/compress_offload.h",
    "include/uapi/sound/compress_params.h",
    "kernel/sched/autogroup.h",
    "kernel/sched/pelt.h",
    "kernel/sched/sched.h",
    "kernel/sched/sched-pelt.h",
    "kernel_aarch64",
    "kernel_aarch64/lib/kunit/kunit.ko",
    "kernel_aarch64_abi_update",
    "kernel_aarch64_config",
    "kernel_aarch64_gki_artifacts",
    "kernel_aarch64_headers",
    "kernel_aarch64_modules",
    "kernel_aarch64_sources",
    "kernel_aarch64_system_dlkm_image",
    "scripts/checkpatch.pl",
]
