/*
 * DHD definitions
 *
 * Copyright (C) 2025, Broadcom.
 *
 *      Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to you
 * under the terms of the GNU General Public License version 2 (the "GPL"),
 * available at http://www.broadcom.com/licenses/GPLv2.php, with the
 * following added to such license:
 *
 *      As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy and
 * distribute the resulting executable under terms of your choice, provided that
 * you also meet, for each linked independent module, the terms and conditions of
 * the license of that module.  An independent module is a module which is not
 * derived from this software.  The special exception does not apply to any
 * modifications of the software.
 *
 *
 * <<Broadcom-WL-IPTag/Dual:>>
 */
#define CONFIG_BCMDHD m
#define CONFIG_BCMDHD_PCIE y
#define CONFIG_BCM43752
#define CONFIG_BCM4389
#define CONFIG_BCM4398
#define CONFIG_BCM4390
#define CONFIG_BCM4383 y
#define CONFIG_DHD_OF_SUPPORT y
#define CONFIG_BROADCOM_WIFI_RESERVED_MEM y
#define CONFIG_DHD_USE_STATIC_BUF y
#define CONFIG_DHD_USE_SCHED_SCAN y
#define CONFIG_DHD_SET_RANDOM_MAC_VAL 0x001A11
#define CONFIG_WLAN_REGION_CODE 100
#define CONFIG_WLAIBSS y
#define CONFIG_WL_RELMCAST y
#define CONFIG_DHD_SET_RANDOM_MAC_VAL 0x001A11
#define CONFIG_BCMDHD_PREALLOC_MEMDUMP y
#define CONFIG_BCMDHD_OOB_HOST_WAKE y
#define CONFIG_BCMDHD_GET_OOB_STATE y
#define CONFIG_BCMDHD_DAL y
#define BCMUTILS_ERR_CODES
#define BCM_FLEX_ARRAY
#define USE_NEW_RSPEC_DEFS
#define CHIPC_NEW_ACCESS_MACROS
#define PCIE_NEW_ACCESS_MACROS
#define PMU_NEW_ACCESS_MACROS
#define SR_NEW_ACCESS_MACROS
#define ARP_OFFLOAD_SUPPORT
#define BCMDONGLEHOST
#define BCMDRIVER
#define BCMFILEIMAGE
#define DHDTHREAD
#define DHD_FW_COREDUMP
#define DHD_USE_RANDMAC
#define EMBEDDED_PLATFORM
#define GET_CUSTOM_MAC_ENABLE
#define KEEP_ALIVE
#define LINUX
#define PNO_SUPPORT
#define SEC_ENHANCEMENT
#define SHOW_EVENTS
#define SHOW_LOGTRACE
#define WIFI_ACT_FRAME
#define WLP2P
#define WL_BW160MHZ
#define WL_BW320MHZ
#define WL_P2P_USE_RANDMAC
#define OEM_ANDROID
#define DHD_COREDUMP
#define WL_VIRTUAL_APSTA
#define DHD_EXPORT_CNTL_FILE
#define EWP_ECNTRS_LOGGING
#define EWP_RTT_LOGGING
#define DHD_LINUX_STD_FW_API
#define FW_SIGNATURE
#define BL_HEAP_START_GAP_SIZE 0x1000
#define BL_HEAP_SIZE 0x10000
#define EWP_EDL
#define EWP_DACS
#define EWP_EVENTTS_LOG
#define EVENT_LOG_RATE_HC
#define DHD_FW_NAME "fw_bcmdhd.bin"
#define DHD_NVRAM_NAME "bcmdhd.cal"
#define DHD_CLM_NAME "bcmdhd_clm.blob"
#define DHD_MAP_NAME "fw_bcmdhd.map"
#define DHD_TXCAP_NAME "bcmdhd_txcap.blob"
#define DHD_USE_SCAN_WAKELOCK
#define DHD_TRACE_WAKE_LOCK
#define PWRSTATS_SYSFS
#define DHD_SBN
#define PCIE_INB_DW
#define PRIORITIZE_ARP
#define WAIT_FOR_DISCONNECT_MAX 20
#define WL_STATIC_IF
#define WLFBT
#define OKC_SUPPORT
#define WL_CFG80211
#define WL_IFACE_MGMT
#define WL_IFACE_MGMT_CONF
#define WL_MLO
#define RTT_GEOFENCE_INTERVAL
#define RTT_GEOFENCE_CONT
#define HAL_DEBUGABILITY
#define DEBUGABILITY
#define DEBUGABILITY_DISABLE_MEMDUMP
#define DHD_DEBUGABILITY_LOG_DUMP_RING
#define DHD_PKT_LOGGING_DBGRING
#define DHD_ECNTRS_EXPOSED_DBGRING
#define DHD_DUMP_BUF_KVMALLOC
#define CUSTOMER_DBG_SYSTEM_TIME
#define CUSTOMER_DBG_PREFIX_ENABLE
#define LOG_CUSTOM_PREFIX_AND_RTC "[dhd][wlan]"
#define DHD_LOGLEVEL
#define BCMASSERT_LOG
#define DHD_LOG_DUMP
#define DHD_LOG_PRINT_RATE_LIMIT
#define APSTA_BLOCK_ARP_DURING_DHCP
#define WL_SKIP_CONNECT_HINTS
#define WL_DYNAMIC_CHAN_POLICY
#define WL_DYNAMIC_CHAN_POLICY_INDOOR
#define WL_DYNAMIC_CHAN_POLICY_DFS
#define WLAN_ACCEL_BOOT
#define TX_CSO
#define RX_CSO
#define AGG_H2D_DB
#define DHD_USE_SPIN_LOCK_BH
#define DHD_SSSR_DUMP
#define DHD_SDTC_ETB_DUMP
#define D2H_MINIDUMP
#define DHD_KERNEL_SCHED_DEBUG
#define BCMPCIE_CTO_PREVENTION
#define DHD_SKIP_DONGLE_RESET_IN_ATTACH
#define DONGLE_ENABLE_ISOLATION
#define DHD_DONGLE_TRAP_IN_DETACH
#define FORCE_DONGLE_RESET_IN_DEVRESET_ON
#define DBG_PRINT_AMNI
#define DHD_MEM_STATS
#define CHECK_TRAP_ROT
#define HOST_SFH_LLC
#define WL_MONITOR
#define WL_CFG80211_MONITOR
#define DHD_ART
#define DHD_MAP_PKTID_LOGGING
#define DHD_FLOW_RING_STATUS_TRACE
#define DHD_MMIO_TRACE
#define RX_PKT_POOL
#define DHD_LB
#define DHD_LB_RXP
#define DHD_LB_TXP
#define DHD_LB_STATS
#define DHD_LB_CPU_SET8 0x100
#define DHD_LB_CPU_SET4 0x070
#define DHD_LB_CPU_SET0 0x00E
#define ENABLE_DHD_GRO
#define WBRC
#define WBRC_WLAN_ON_FIRST_ALWAYS
#define SUPPORT_MULTIPLE_REVISION
#define SUPPORT_MULTIPLE_REVISION_MAP
#define SUPPORT_MIXED_MODULES
#define USE_CID_CHECK
#define SUPPORT_MULTIPLE_CHIPS
#define CONCAT_DEF_REV_FOR_NOMATCH_VID
#define RESCHED_CNT_CHECK_PERIOD_SEC 2
#define AFFINITY_UPDATE_MIN_PERIOD_SEC 6
#define DHD_CUSTOM_PKT_COUNT_ENABLE
#define PKT_COUNT_HIGH 50000
#define PKT_COUNT_MID 5000
#define PKT_COUNT_LOW 3000
#define DHD_CPUFREQ_MID 4u
#define DHD_CPUFREQ_BIG 7u
#define DHD_LITTLE_CORE_PERF_FREQ 1849000u
#define DHD_MID_CORE_PERF_FREQ 2450000u
#define DHD_BIG_CORE_PERF_FREQ 3015000u
#define CLEAN_IRQ_AFFINITY_HINT
#define WAKEUP_KSOFTIRQD_POST_NAPI_SCHEDULE
#define IRQ_AFFINITY_SMALL_CORE 6
#define IRQ_AFFINITY_BIG_CORE 7
#define DHD_BUS_BUSY_TIMEOUT 5000
#define DHD_MSI_SUPPORT
#define DHD_TX_CPL_BOUND 1024
#define DHD_TX_POST_BOUND 128
#define DHD_RX_CPL_POST_BOUND 96
#define DHD_CTRL_CPL_POST_BOUND 16
#define DHD_LB_TXBOUND 32
#define DHD_NON_DMA_M2M_CORRUPTION
#define DHD_FW_MEM_CORRUPTION
#define DHD_RECOVER_TIMEOUT
#define DHD_SKIP_XORCSUM_HIGH_TPUT
#define DHD_SKIP_COREDUMP_ON_HC
#define DHD_SKIP_COREDUMP_OLDER_CHIPS
#define SKIP_COREDUMP_PKTDROP_RXHC
#define DHD_HOST_CPUFREQ_BOOST
#define DHD_HOST_CPUFREQ_BOOST_DEFAULT_ENAB
#define DHD_FILE_DUMP_EVENT
#define DHD_HAL_RING_DUMP
#define DHD_DUMP_START_COMMAND
#define WL_MLO_BKPORT
#define WL_MLO_BKPORT_NEW_PORT_AUTH
#define WL_CROSS_AKM_BKPORT
#define DISABLE_NAN_PAIRING
#define WL_CH_SWITCH_BKPORT
#define USE_WL_FRAMEBURST
#define USE_WL_TXBF
#define SOFTAP_UAPSD_OFF
#define VSDB
#define WL_CFG80211_STA_EVENT
#define APF
#define WL_APF_PROGRAM_MAX_SIZE 4096
#define DHD_GET_VALID_CHANNELS
#define LINKSTAT_SUPPORT
#define LINKSTAT_EXT_SUPPORT
#define PFN_SCANRESULT_2
#define WL_IFACE_COMB_NUM_CHANNELS
#define WL_SCHED_SCAN
#define ROAMEXP_SUPPORT
#define WL_SKIP_CONNECT_HINTS
#define CUSTOM_SET_OCLOFF
#define DHD_ENABLE_LPC
#define DISABLE_PM_BCNRX
#define FCC_PWR_LIMIT_2G
#define SUPPORT_2G_VHT
#define SUPPORT_5G_1024QAM_VHT
#define SUPPORT_LTECX
#define SUPPORT_LQCM
#define SUPPORT_SET_CAC
#define DHD_LOSSLESS_ROAMING
#define ENABLE_FW_ROAM_SUSPEND
#define ROAM_API
#define ROAM_AP_ENV_DETECTION
#define ROAM_CHANNEL_CACHE
#define ROAM_ENABLE
#define SKIP_ROAM_TRIGGER_RESET
#define WBTEXT
#define WBTEXT_BTMDELTA 0
#define WBTEXT_SCORE_V2
#define RRM_BCNREQ_MAX_CHAN_TIME 12
#define WL_LASTEVT
#define ROAM_EVT_DISABLE
#define WL_SOFTAP_ACS
#define CONFIG_HAS_WAKELOCK
#define DHD_WAKE_EVENT_STATUS
#define DHD_WAKE_RX_STATUS
#define CUSTOM_WAKE_REASON_STATS
#define DHD_WAKEPKT_SET_MARK
#define WL_USE_RANDOMIZED_SCAN
#define STA_RANDMAC_ENFORCED
#define WL_STA_ASSOC_RAND
#define WL_SOFTAP_RAND
#define WL_P2P_RAND
#define WL_CUSTOM_MAPPING_OF_DSCP
#define DHD_WAKE_STATUS
#define ENABLE_BCN_LI_BCN_WAKEUP
#define DHD_HANG_SEND_UP_TEST
#define DHD_USE_EXTENDED_HANG_REASON
#define PREVENT_REOPEN_DURING_HANG
#define SUPPORT_LINKDOWN_RECOVERY
#define SUPPORT_TRIGGER_HANG_EVENT
#define BCMASSERT_LOG
#define DHD_8021X_DUMP
#define DHD_DHCP_DUMP
#define DHD_ICMP_DUMP
#define DHD_ARP_DUMP
#define DHD_DNS_DUMP
#define DHD_PKT_LOGGING
#define DHD_PKTDUMP_ROAM
#define DHD_RANDMAC_LOGGING
#define DHD_STATUS_LOGGING
#define DHD_WAKEPKT_DUMP
#define RSSI_MONITOR_SUPPORT
#define SET_SSID_FAIL_CUSTOM_RC 100
#define DHD_EVENT_LOG_FILTER
#define WL_CFGVENDOR_SEND_HANG_EVENT
#define BLOCK_IPV6_PACKET
#define PASS_ALL_MCAST_PKTS
#define PKTPRIO_OVERRIDE
#define NDO_CONFIG_SUPPORT
#define WAIT_DEQUEUE
#define WL_SUPPORT_BACKPORTED_KPATCHES
#define SUPPORT_AP_HIGHER_BEACONRATE
#define SUPPORT_AP_RADIO_PWRSAVE
#define SUPPORT_HIDDEN_AP
#define SUPPORT_SOFTAP_SINGL_DISASSOC
#define WL_SUPPORT_AUTO_CHANNEL
#define SUPPORT_SOFTAP_WPAWPA2_MIXED
#define P2P_LISTEN_OFFLOADING
#define CUSTOMER_SCAN_TIMEOUT_SETTING
#define DISABLE_PRUNED_SCAN
#define ESCAN_BUF_OVERFLOW_MGMT
#define SUPPORT_RANDOM_MAC_SCAN
#define USE_INITIAL_SHORT_DWELL_TIME
#define WL_CFG80211_VSDB_PRIORITIZE_SCAN_REQUEST
#define CUSTOM_SCAN_UNASSOC_ACTIVE_TIME 40
#define CUSTOM_SCAN_PASSIVE_TIME 110
#define ENABLE_MAX_DTIM_IN_SUSPEND
#define SUPPORT_DEEP_SLEEP
#define DHD_BLOB_EXISTENCE_CHECK
#define SUPPORT_PM2_ONLY
#define SUPPORT_AMPDU_MPDU_CMD
#define WL_RELMCAST
#define WL_SUPP_EVENT
#define DISABLE_WL_FRAMEBURST_SOFTAP
#define FILTER_IE
#define CUSTOM_LONG_RETRY_LIMIT 12
#define DHD_POST_EAPOL_M1_AFTER_ROAM_EVT
#define ROAMEXP_SUPPORT
#define CUSTOM_BSSID_BLACKLIST_NUM 16
#define CUSTOM_SSID_WHITELIST_NUM 16
#define ENABLE_TDLS_AUTO_MODE
#define EXPLICIT_DISCIF_CLEANUP
#define SKIP_WLFC_ON_CONCURRENT
#define CUSTOM_BLOCK_DEAUTH_AT_EAP_FAILURE
#define TDLS_MSG_ONLY_WFD
#define CUSTOM_EVENT_PM_WAKE_MEMDUMP_DISABLED
#define DHD_RESET_FEM_5G_RFFE_VI0
#define CUSTOM_ROAM_TIME_THRESH_IN_SUSPEND 6000
#define CUSTOM_EVENT_PM_WAKE 30
#define CUSTOM_EVENT_PM_PERCENT 70
#define CUSTOM_KEEP_ALIVE_SETTING 30000
#define CUSTOM_PNO_EVENT_LOCK_xTIME 10
#define CUSTOM_OCL_RSSI_VAL -75
#define CUSTOM_DHD_WATCHDOG_MS 0
#define CUSTOM_TDLS_IDLE_MODE_SETTING 10000
#define CUSTOM_TDLS_RSSI_THRESHOLD_HIGH -80
#define CUSTOM_TDLS_RSSI_THRESHOLD_LOW -85
#define D3_ACK_RESP_TIMEOUT 4000
#define IOCTL_RESP_TIMEOUT 5000
#define MAX_DTIM_ALLOWED_INTERVAL 925
#define ENABLE_MAX_DTIM_IN_SUSPEND
#define NUM_SCB_MAX_PROBE 3
#define WL_SCB_TIMEOUT 10
#define WIFI_TURNOFF_DELAY 10
#define WIFI_TURNON_USE_HALINIT
#define DHD_USE_STATIC_MEMDUMP
#define WL_MBO
#define WL_OCE
#define WL_MBO_HOST
#define WL_CELLULAR_CHAN_AVOID
#define WL_CELLULAR_CHAN_AVOID_DUMP
#define WL_USABLE_CHAN
#define DHD_ACS_CHECK_SCC_2G_ACTIVE_CH
#define WL_LATENCY_MODE
#define SUPPORT_LATENCY_CRITICAL_DATA
#define WL_CFG80211_GON_COLLISION
#define DHD_SEND_HANG_PRIVCMD_ERRORS
#define DHD_SEND_HANG_ESCAN_SYNCID_MISMATCH
#define WFC_NON_CONT_CHAN
#define CHRE
#define DHD_USE_STATIC_CTRLBUF
#define DHD_USE_COHERENT_MEM_FOR_RING
#define DHD_PCIE_RUNTIMEPM
#define MAX_IDLE_COUNT 5
#define DNGL_AXI_ERROR_LOGGING
#define DHD_4WAYM4_FAIL_DISCONNECT
#define BCMPCIE_OOB_HOST_WAKE
#define DHD_USE_PCIE_OOB_THREADED_IRQ
#define BCMDMA64OSL
#define VSDB
#define WLTDLS
#define WLTDLS_AUTO_ENABLE
#define CUSTOM_TDLS_IDLE_MODE_SETTING 10000
#define CUSTOM_TDLS_RSSI_THRESHOLD_HIGH -80
#define CUSTOM_TDLS_RSSI_THRESHOLD_LOW -85
#define CUSTOM_ROAM_TRIGGER_SETTING -75
#define CUSTOM_ROAM_DELTA_SETTING 10
#define SUPPORT_PM2_ONLY
#define CUSTOM_PNO_EVENT_LOCK_xTIME 10
#define MIRACAST_AMPDU_SIZE 8
#define WL_VENDOR_EXT_SUPPORT
#define RSSI_MONITOR_SUPPORT
#define RTT_SUPPORT
#define RTT_DEBUG
#define NDO_CONFIG_SUPPORT
#define IPV6_NDO_SUPPORT
#define DBG_PKT_MON
#define DBG_PKT_MON_INIT_DEFAULT
#define DHD_PKT_MON_DUAL_STA
#define DNGL_EVENT_SUPPORT
#define PARSE_DONGLE_HOST_EVENT
#define WL_CFGVENDOR_SEND_ALERT_EVENT
#define DHD_USE_EARLYSUSPEND
#define ESCAN_RESULT_PATCH
#define DUAL_ESCAN_RESULT_BUFFER
#define WL_NAN
#define WL_NAN_DISC_CACHE
#define WL_NANP2P
#define NAN_DAM_ANDROID
#define WL_NAN_6G
#define WL_NAN_INSTANT_MODE
#define FTM
#define DHD_RTT_USE_FTM_RANGE
#define DHD_RTT_USE_SEPARATE_PASSPHRASE_DB
#define QOS_MAP_SET
#define DHD_DSCP_POLICY
#define WL_THERMAL_MITIGATION
#define WL_SAR_TX_POWER
#define WL_SAR_TX_POWER_CONFIG
#define WL_USABLE_CHAN
#define WL_GET_RCC
#define CONFIG_ROAM_RSSI_LIMIT
#define CUSTOM_ROAMRSSI_2G -80
#define CUSTOM_ROAMRSSI_5G -77
#define WL_GCMP_SUPPORT
#define WL_DISABLE_HE_P2P
#define WL_CAP_HE
#define WL_CAP_OCE_STA
#define WL_RTT_LCI
#define WL_RTT_ONE_WAY
#define WL_RTT_BW160
#define ENHANCED_STATIC_BUF
#define STATIC_WL_PRIV_STRUCT
#define IOCTL_RESP_TIMEOUT 5000
#define WAIT_DEQUEUE
#define DHD_USE_IDLECOUNT
#define DHDENABLE_TAILPAD
#define CUSTOM_SET_SHORT_DWELL_TIME
#define WL_WPS_SYNC
#define BCMCRYPTO_COMPONENT
#define PLATFORM_PATH "/vendor/etc/wifi/"
#define SIMPLE_MAC_PRINT
#define DHD_CLEANUP_KEEP_ALIVE
#define WL_DUAL_STA
#define WL_DUAL_APSTA
#define SUPPORT_OTA_UPDATE
#define DHD_SCAN_INC_RNR
#define SYNCID_MISMATCH_DEBUG
#define WL_RAV_MSCS_NEG_IN_ASSOC
#define MAX_PFN_LIST_COUNT 16
#define WL_OWE_OFFLD_BKPORT
#define WL_AP_PORT_AUTH_BKPORT
#define WL_OWE_OFFLD_FEAT_ADV_BKPORT
#define WL_BSS_STA_INFO
#define WL_TWT_HAL_IF
#define WL_6G_BAND
#define WL_5P9G
#define WL_UNII4_CHAN
#define APF_SINGLE_IF_SUPPORT
#define USE_WL_TXBF
#define CUSTOM_DPC_CPUCORE 0
#define WL11U
#define MFP
#define DHD_WAKE_STATUS
#define DHD_WAKE_RX_STATUS
#define DHD_WAKE_EVENT_STATUS
#define DHD_WAKE_STATUS_PRINT
#define TSQ_MULTIPLIER 10
#define PCIE_FULL_DONGLE
#define BCMPCIE
#define CUSTOM_DPC_PRIO_SETTING -1
#define SOCI_NCI_BUS
#define CUSTOM_AMPDU_BA_WSIZE 64
#define PROP_TXSTATUS_VSDB
#define BCM_ASLR_HEAP
#define DHD_AGGR_WI
#define DHD_AGGR_WI_EN 0xE
#define MAX_CNTL_TX_TIMEOUT 1
#define DHD_USE_STATIC_IOCTLBUF
#define DNGL_EVENT_SUPPORT
#define HCHK_COMMON_SW_EVENT
#define DHD_OF_SUPPORT
#define DHD_8021X_DUMP
#define EAPOL_PKT_PRIO
#define WL_RATE_INFO
#define ENABLE_INSMOD_NO_FW_LOAD
#define BCMDHD_MODULAR
#define DEBUG_DNGL_INIT_FAIL
#define DHD_CAP_CUSTOMER "hw2 "
#define POWERUP_MAX_RETRY 0
#define CUSTOMER_HW2
#define CUSTOMER_HW2_DEBUG
#define DHD_SET_PCIE_DMA_MASK_FOR_GS101
#define CUSTOM_CONTROL_LOGTRACE 1
#define DHD_CAP_PLATFORM "exynos "
#define CONFIG_ARCH_EXYNOS
#define DHD_MODULE_INIT_FORCE_SUCCESS
#define SUPPORT_MULTIPLE_NVRAM
#define SUPPORT_MULTIPLE_CLMBLOB
#define DHD_LB_TXP_DEFAULT_ENAB
#define DHD_SSSR_COREDUMP
#define DHD_REDUCE_PM_LOG
#define LB_RXP_STOP_THR 500
#define LB_RXP_STRT_THR 499
#define DHD_FIS_DUMP
#define FIS_WITHOUT_CMN
#define DEFAULT_RECREATE_BI_TIMEOUT 40
#define BCMPCI_DEV_ID 0x4449
#define BCMPCI_NOOTP_DEV_ID 0x4383
#define BCM4383_CHIP_DEF
#define PCIE_CPL_TIMEOUT_RECOVERY
#define DHD_TCP_LIMIT_OUTPUT
#define DHD_TCP_PACING_SHIFT
#define DHD_DEBUG
#define DHD_COMPILED "/opt/wcd/work/workspace/WIFI_DHD_Build/DOPPLER_BRANCH_103_10/build/dhd/android-b/gg_pixeltg4-gg/pcie@gg/source"
