# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("//private/devices/google/common/kleaf:checkpatch.bzl", "checkpatch_strict")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

checkpatch_strict(
    name = "checkpatch",
)

filegroup(
    name = "arm-smmu-v3.kconfig",
    srcs = [
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:kconfig",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/perf:kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_headers(
    name = "headers",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    visibility = [":__subpackages__"],
)
