# SPDX-License-Identifier: GPL-2.0-only

load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "google_gem",
    srcs = glob([
        "**/*.h",
    ]),
    out = "google_gem.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_GEM": {
            True: [
                "google_gem.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-gdmc-iface",
    ],
)

ddk_module(
    name = "google_gem_test_module",  # Added "_module" for the error _kernel_module rule 'google_gem_test' conflicts with existing hermetic_test rule
    srcs = glob([
        "**/*.h",
    ]),
    out = "google_gem_test.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_GEM_TEST": {
            True: [
                "google_gem_test.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        ":google_gem",
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)
