import("//build_overrides/noa.gni")
import("//build_overrides/pigweed.gni")

import("$dir_pw_unit_test/test.gni")

pw_test_group("tests") {
  enable_if = current_os == "linux"
  group_deps = [
    "$dir_noa_packages/noah_lib/noa_ipc:tests",
    "$dir_noa_packages/noah_lib/pw_rpc_c:tests",
    "$dir_noa_packages/noah_lib/pw_rpc_service_client:tests",
  ]
}
