# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "s2mpg12-key",
    out = "s2mpg12-key.ko",
    conditional_srcs = {
        "CONFIG_KEYBOARD_S2MPG12": {
            True: [
                "s2mpg12-key.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)

ddk_module(
    name = "s2mpg14-key",
    out = "s2mpg14-key.ko",
    conditional_srcs = {
        "CONFIG_KEYBOARD_S2MPG14": {
            True: [
                "s2mpg14-key.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)
