/* SPDX-License-Identifier: GPL-2.0 */

#define CONFIG_BCMDHD m
#define CONFIG_BCMDHD_PCIE y
#define CONFIG_BCM43756 y
#define CONFIG_DHD_OF_SUPPORT y
#define CONFIG_BCMDHD_FW_PATH "/vendor/firmware/fw_bcmdhd.bin"
#define CONFIG_BCMDHD_NVRAM_PATH "/vendor/firmware/bcmdhd.cal"
#define CONFIG_BCMDHD_CLM_PATH "/vendor/firmware/bcmdhd_clm.blob"
#define CONFIG_BCMDHD_MAP_PATH "/vendor/firmware/fw_bcmdhd.map"
#define CONFIG_BROADCOM_WIFI_RESERVED_MEM y
#define CONFIG_DHD_USE_STATIC_BUF y
#define CONFIG_DHD_USE_SCHED_SCAN y
#define CONFIG_DHD_SET_RANDOM_MAC_VAL 0x001A11
#define CONFIG_WLAN_REGION_CODE 100
#define CONFIG_WLAIBSS y
#define CONFIG_WL_RELMCAST y
#define CONFIG_BCMDHD_PREALLOC_MEMDUMP y
#define CONFIG_BCMDHD_OOB_HOST_WAKE y
#define CONFIG_BCMDHD_GET_OOB_STATE y
#define BCMUTILS_ERR_CODES
#define USE_NEW_RSPEC_DEFS
#define LINUX
#define BCMDRIVER
#define BCMDONGLEHOST
#define BCMFILEIMAGE
#define DHDTHREAD
#define SHOW_EVENTS
#define WLP2P
#define WIFI_ACT_FRAME
#define ARP_OFFLOAD_SUPPORT
#define KEEP_ALIVE
#define EMBEDDED_PLATFORM
#define PNO_SUPPORT
#define SHOW_LOGTRACE
#define GET_CUSTOM_MAC_ENABLE
#define SEC_ENHANCEMENT
#define DHD_FW_COREDUMP
#define DHD_USE_RANDMAC
#define WL_P2P_USE_RANDMAC
#define OEM_ANDROID
#define DHD_COREDUMP
#define WL_VIRTUAL_APSTA
#define EWP_ECNTRS_LOGGING
#define EWP_RTT_LOGGING
#define EWP_ETD_PRSRV_LOGS
#define EWP_EDL
#define EVENT_LOG_RATE_HC
#define CPL_TIMEOUT_RECOVERY
#define DHD_USE_SCAN_WAKELOCK
#define DHD_TRACE_WAKE_LOCK
#define CHAN_STATS_SUPPORT
#define PWRSTATS_SYSFS
#define DHD_SBN
#define DHD_SKIP_PKTLOGGING_FOR_DATA_PKTS
#define PCIE_INB_DW
#define PCIE_INB_DSACK_EXT_WAIT
#define WAIT_FOR_DISCONNECT_MAX 20
#define APSTA_NON_CONCURRENT
#define WLFBT
#define OKC_SUPPORT
#define WL_CFG80211
#define WL_IFACE_MGMT
#define WL_IFACE_MGMT_CONF
#define RTT_GEOFENCE_INTERVAL
#define RTT_GEOFENCE_CONT
#define SYNCID_MISMATCH_DEBUG
#define DEBUGABILITY
#define DEBUGABILITY_DISABLE_MEMDUMP
#define DHD_PKT_LOGGING_DBGRING
#define DHD_DEBUGABILITY_LOG_DUMP_RING
#define CUSTOMER_DBG_SYSTEM_TIME
#define CUSTOMER_DBG_PREFIX_ENABLE
#define WL_CFGVENDOR_SEND_ALERT_EVENT
#define DHD_REPLACE_LOG_INFO_TO_TRACE
#define DHD_DUMP_BUF_KVMALLOC
#define CUSTOM_PREFIX "[dhd][wlan]"
#define DHD_LOGLEVEL
#define BCMASSERT_LOG
#define DHD_LOG_DUMP
#define DHD_MMIO_TRACE
#define DHD_LOG_PRINT_RATE_LIMIT
#define APSTA_BLOCK_ARP_DURING_DHCP
#define WL_SKIP_CONNECT_HINTS
#define WL_AUTO_COUNTRY
#define WIPHY_DYNAMIC_UPDATE
#define DHD_USE_SPIN_LOCK_BH
#define DHD_SSSR_DUMP
#define D2H_MINIDUMP
#define DHD_KERNEL_SCHED_DEBUG
#define BCMPCIE_CTO_PREVENTION
#define DONGLE_ENABLE_ISOLATION
#define DHD_DONGLE_TRAP_IN_DETACH
#define FORCE_DONGLE_RESET_IN_DEVRESET_ON
#define RESCHED_CNT_CHECK_PERIOD_SEC 2
#define AFFINITY_UPDATE_MIN_PERIOD_SEC 6
#define RESCHED_STREAK_MAX_HIGH 10
#define RESCHED_STREAK_MAX_LOW 2
#define CLEAN_IRQ_AFFINITY_HINT
#define IRQ_AFFINITY_BIG_CORE 4
#define IRQ_AFFINITY_SMALL_CORE 4
#define WAKEUP_KSOFTIRQD_POST_NAPI_SCHEDULE
#define DHD_MEM_STATS
#define CHECK_TRAP_ROT
#define HOST_SFH_LLC
#define DHD_PKTID_AUDIT_ENABLED
#define DHD_LB
#define DHD_LB_RXP
#define DHD_LB_TXP
#define DHD_LB_STATS
#define DHD_LB_PRIMARY_CPUS 0xF0
#define DHD_LB_SECONDARY_CPUS 0x0E
#define ENABLE_DHD_GRO
#define WL_MONITOR
#define WBRC
#define WL_CFG80211_MONITOR
#define DHD_FILE_DUMP_EVENT
#define DHDTCPACK_SUPPRESS
#define USE_WL_FRAMEBURST
#define USE_WL_TXBF
#define SOFTAP_UAPSD_OFF
#define VSDB
#define WL_CFG80211_STA_EVENT
#define APF
#define DHD_GET_VALID_CHANNELS
#define LINKSTAT_SUPPORT
#define LINKSTAT_EXT_SUPPORT
#define PFN_SCANRESULT_2
#define WL_IFACE_COMB_NUM_CHANNELS
#define ASSOC_PREF_5G
#define ASSOC_PREFER_RSSI_THRESH -65
#define WL_CUSTOM_MAPPING_OF_DSCP
#define QOS_MAP_SET
#define WL_SCHED_SCAN
#define PNO_DISABLE_EL
#define ROAMEXP_SUPPORT
#define CUSTOM_SET_OCLOFF
#define DHD_ENABLE_LPC
#define DISABLE_PM_BCNRX
#define FCC_PWR_LIMIT_2G
#define SUPPORT_2G_VHT
#define SUPPORT_5G_1024QAM_VHT
#define SUPPORT_LTECX
#define SUPPORT_LQCM
#define SUPPORT_SET_CAC
#define SUPPORT_WL_TXPOWER
#define WL_THERMAL_MITIGATION
#define DHD_LOSSLESS_ROAMING
#define ENABLE_FW_ROAM_SUSPEND
#define ROAM_API
#define ROAM_AP_ENV_DETECTION
#define ROAM_CHANNEL_CACHE
#define ROAM_ENABLE
#define SKIP_ROAM_TRIGGER_RESET
#define WBTEXT_SCORE_V2
#define WL_LASTEVT
#define ROAM_EVT_DISABLE
#define CONFIG_HAS_WAKELOCK
#define DHD_WAKE_EVENT_STATUS
#define DHD_WAKE_RX_STATUS
#define WL_USE_RANDOMIZED_SCAN
#define STA_RANDMAC_ENFORCED
#define WL_STA_ASSOC_RAND
#define WL_SOFTAP_RAND
#define WL_P2P_RAND
#define DHD_WAKE_STATUS
#define ENABLE_BCN_LI_BCN_WAKEUP
#define DHD_HANG_SEND_UP_TEST
#define DHD_USE_EXTENDED_HANG_REASON
#define PREVENT_REOPEN_DURING_HANG
#define SUPPORT_LINKDOWN_RECOVERY
#define SUPPORT_TRIGGER_HANG_EVENT
#define DHD_8021X_DUMP
#define DHD_DHCP_DUMP
#define DHD_IPV6_DUMP
#define DHD_ICMP_DUMP
#define DHD_ARP_DUMP
#define DHD_DNS_DUMP
#define DHD_PKT_LOGGING
#define DHD_PKTDUMP_ROAM
#define DHD_RANDMAC_LOGGING
#define DHD_STATUS_LOGGING
#define DISABLE_PCI_LOGGING
#define DISABLE_BEACON_LOGGING
#define DHD_WL_ERROR_LOGGING
#define DHD_IE_ERROR_LOGGING
#define DHD_ASSOC_ERROR_LOGGING
#define DHD_PMU_ERROR_LOGGING
#define DHD_8021X_ERROR_LOGGING
#define DHD_AMPDU_ERROR_LOGGING
#define DHD_SAE_ERROR_LOGGING
#define DHD_WAKEPKT_SET_MARK
#define RSSI_MONITOR_SUPPORT
#define SET_SSID_FAIL_CUSTOM_RC 100
#define DHD_EVENT_LOG_FILTER
#define WL_CFGVENDOR_SEND_HANG_EVENT
#define BLOCK_IPV6_PACKET
#define ENABLE_IPMCAST_FILTER
#define PASS_ALL_MCAST_PKTS
#define PRIORITIZE_ARP
#define PKTPRIO_OVERRIDE
#define NDO_CONFIG_SUPPORT
#define DISABLE_TXACK_ALIVE
#define WAIT_DEQUEUE
#define WL_SUPPORT_BACKPORTED_KPATCHES
#define SUPPORT_AP_HIGHER_BEACONRATE
#define SUPPORT_AP_RADIO_PWRSAVE
#define SUPPORT_HIDDEN_AP
#define SUPPORT_SOFTAP_SINGL_DISASSOC
#define WL_SUPPORT_AUTO_CHANNEL
#define SUPPORT_SOFTAP_WPAWPA2_MIXED
#define P2P_LISTEN_OFFLOADING
#define P2P_SKIP_DFS
#define SPECIFIC_MAC_GEN_SCHEME
#define CUSTOMER_SCAN_TIMEOUT_SETTING
#define DISABLE_PRUNED_SCAN
#define ESCAN_BUF_OVERFLOW_MGMT
#define SUPPORT_RANDOM_MAC_SCAN
#define USE_INITIAL_SHORT_DWELL_TIME
#define WL_CFG80211_VSDB_PRIORITIZE_SCAN_REQUEST
#define CUSTOM_SCAN_UNASSOC_ACTIVE_TIME 40
#define CUSTOM_SCAN_PASSIVE_TIME 110
#define ENABLE_MAX_DTIM_IN_SUSPEND
#define SUPPORT_DEEP_SLEEP
#define DHD_BLOB_EXISTENCE_CHECK
#define SUPPORT_PM2_ONLY
#define SUPPORT_AMPDU_MPDU_CMD
#define WL_RELMCAST
#define WL_SUPP_EVENT
#define DISABLE_WL_FRAMEBURST_SOFTAP
#define FILTER_IE
#define CUSTOM_LONG_RETRY_LIMIT 12
#define DHD_POST_EAPOL_M1_AFTER_ROAM_EVT
#define CUSTOM_BSSID_BLACKLIST_NUM 16
#define CUSTOM_SSID_WHITELIST_NUM 16
#define ENABLE_TDLS_AUTO_MODE
#define EXPLICIT_DISCIF_CLEANUP
#define SKIP_WLFC_ON_CONCURRENT
#define CUSTOM_BLOCK_DEAUTH_AT_EAP_FAILURE
#define TDLS_MSG_ONLY_WFD
#define CUSTOM_ROAM_TIME_THRESH_IN_SUSPEND 6000
#define CUSTOM_EVENT_PM_WAKE 20
#define CUSTOM_KEEP_ALIVE_SETTING 30000
#define CUSTOM_PNO_EVENT_LOCK_xTIME 10
#define CUSTOM_DHD_WATCHDOG_MS 0
#define CUSTOM_TDLS_IDLE_MODE_SETTING 10000
#define CUSTOM_TDLS_RSSI_THRESHOLD_HIGH -80
#define CUSTOM_TDLS_RSSI_THRESHOLD_LOW -85
#define CUSTOM_TCPACK_SUPP_RATIO 15
#define CUSTOM_TCPACK_DELAY_TIME 10
#define D3_ACK_RESP_TIMEOUT 4000
#define IOCTL_RESP_TIMEOUT 5000
#define MAX_DTIM_ALLOWED_INTERVAL 925
#define NUM_SCB_MAX_PROBE 3
#define WL_SCB_TIMEOUT 10
#define WIFI_TURNOFF_DELAY 10
#define WIFI_TURNON_USE_HALINIT
#define DHD_USE_STATIC_MEMDUMP
#define WL_MBO
#define WL_OCE
#define WL_CAP_OCE_STA
#define WL_BCNRECV
#define WL_CAC_TS
#define WL_LATENCY_MODE
#define SUPPORT_LATENCY_CRITICAL_DATA
#define WL_CFG80211_GON_COLLISION
#define DHD_SEND_HANG_PRIVCMD_ERRORS
#define DHD_USE_STATIC_CTRLBUF
#define DHD_USE_COHERENT_MEM_FOR_RING
#define DHD_PCIE_RUNTIMEPM
#define MAX_IDLE_COUNT 5
#define DNGL_AXI_ERROR_LOGGING
#define DHD_4WAYM4_FAIL_DISCONNECT
#define BCMPCIE_OOB_HOST_WAKE
#define DHD_USE_PCIE_OOB_THREADED_IRQ
#define BCMDMA64OSL
#define WLTDLS
#define WLTDLS_AUTO_ENABLE
#define CUSTOM_ROAM_TRIGGER_SETTING -75
#define CUSTOM_ROAM_DELTA_SETTING 10
#define WLADPS
#define MIRACAST_AMPDU_SIZE 8
#define WL_VENDOR_EXT_SUPPORT
#define DISABLE_ANDROID_GSCAN
#define RTT_SUPPORT
#define RTT_DEBUG
#define WL_RTT_CTS
#define WL_RTT_ONE_WAY
#define IPV6_NDO_SUPPORT
#define DBG_PKT_MON
#define DBG_PKT_MON_INIT_DEFAULT
#define DNGL_EVENT_SUPPORT
#define PARSE_DONGLE_HOST_EVENT
#define DHD_USE_EARLYSUSPEND
#define ESCAN_RESULT_PATCH
#define DUAL_ESCAN_RESULT_BUFFER
#define WL_NAN
#define WL_NAN_DISC_CACHE
#define WL_NANP2P
#define WL_NAN_INSTANT_MODE
#define WL_SAR_TX_POWER
#define WL_SAR_TX_POWER_CONFIG
#define WL_OWE
#define WL_SAE_FT
#define CONFIG_SILENT_ROAM
#define HIGHBAND_ROAM
#define WL_GET_RCC
#define CONFIG_ROAM_RSSI_LIMIT
#define CUSTOM_ROAMRSSI_2G -70
#define CUSTOM_ROAMRSSI_5G -70
#define THERMAL_MITIGATION_THRESHOLD 1
#define WL_GCMP_SUPPORT
#define WL_DISABLE_HE_P2P
#define ENHANCED_STATIC_BUF
#define STATIC_WL_PRIV_STRUCT
#define DHD_USE_IDLECOUNT
#define DHDENABLE_TAILPAD
#define CUSTOM_SET_SHORT_DWELL_TIME
#define DISABLE_FRAMEBURST_VSDB
#define WL_WPS_SYNC
#define BCMCRYPTO_COMPONENT
#define WL_CAP_HE
#define PLATFORM_PATH "/vendor/etc/wifi/"
#define SUPPORT_OTA_UPDATE
#define DRIVER_TYPE m
#define CUSTOM_DPC_CPUCORE 0
#define WL11U
#define MFP
#define CUSTOM_WAKE_REASON_STATS
#define TSQ_MULTIPLIER 10
#define PCIE_FULL_DONGLE
#define BCMPCIE
#define CUSTOM_DPC_PRIO_SETTING -1
#define CUSTOM_AMPDU_BA_WSIZE 64
#define PROP_TXSTATUS_VSDB
#define BCM_ASLR_HEAP
#define MAX_CNTL_TX_TIMEOUT 1
#define DHD_USE_STATIC_IOCTLBUF
#define HCHK_COMMON_SW_EVENT
#define DHD_OF_SUPPORT
#define EAPOL_PKT_PRIO
#define WL_USABLE_CHAN
#define ENABLE_INSMOD_NO_FW_LOAD
#define BCMDHD_MODULAR
#define DHD_CAP_CUSTOMER "hw2 "
#define CUSTOMER_HW2_DEBUG
#define DHD_CUSTOMER_PCIE_DMA_MASK 36
#define DHD_CAP_PLATFORM "exynos "
#define CONFIG_ARCH_EXYNOS
#define DHD_MODULE_INIT_FORCE_SUCCESS
#define SUPPORT_MULTIPLE_NVRAM
#define SUPPORT_MULTIPLE_CLMBLOB
#define DHD_LB_TXP_DEFAULT_ENAB
#define BOARD_MODULAR_INIT
#define DHD_REDUCE_PM_LOG
#define POWERUP_MAX_RETRY 0
#define BCMPCI_DEV_ID 0x449d
#define BCMPCI_NOOTP_DEV_ID 0x4362
#define BCMPCIE_DISABLE_ASYNC_SUSPEND
#define DHD_LINUX_STD_FW_API
#define DHD_FW_NAME "fw_bcmdhd.bin"
#define DHD_NVRAM_NAME "bcmdhd.cal"
#define DHD_CLM_NAME "bcmdhd_clm.blob"
#define DHD_MAP_NAME "fw_bcmdhd.map"
#define FILTER_IE_NAME "filter_ie"
#define DHD_TCP_LIMIT_OUTPUT
#define DHD_TCP_PACING_SHIFT
#define DHD_DEBUG
