# SPDX-License-Identifier: GPL-2.0-or-later

load(
    "@kleaf//build/kernel/kleaf:kernel.bzl",
    "checkpatch",
    "ddk_headers",
    "ddk_module",
    "ddk_uapi_headers",
)

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

ddk_uapi_headers(
    name = "uapi_headers",
    srcs = glob([
        "include/uapi/**/*.h",
    ]),
    out = "cnm-uapi-headers.tar.gz",
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_headers(
    name = "headers",
    hdrs = glob([
        "include/**/*.h",
    ]),
    includes = [
        "include",
    ],
)

ddk_module(
    name = "jpu",
    srcs = glob([
        "**/*.h",
    ]) + [
        "jpu_ioctl.c",
        "jpu_pm.c",
    ],
    out = "jpu.ko",
    copts = [
        "-Wformat",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    local_defines = [
        "DYNAMIC_DEBUG_MODULE",
    ],
    deps = [
        ":headers",
        "//common:all_headers_aarch64",
        "//private/google-modules/perf/core/google_pm_qos",
        "//private/google-modules/perf/core/gs_perf_domain:perf_domain",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/soc/rdo/interconnect:google_icc",
    ],
)
