// SPDX-License-Identifier: GPL-2.0-only
/*
 * Platform device driver to power on/off google soc power domains
 * Copyright (C) 2024 Google LLC.
 */

#include <dt-bindings/power/genpd_mbu.h>

#include "cpm_mappings.h"

#define LPCM_GENPD_SSWRP_DPU 0
#define LPCM_GENPD_SSWRP_HSIO_S 1
#define LPCM_GENPD_SSWRP_HSIO_N 2
#define LPCM_GENPD_SSWRP_LSIO_S 3
#define LPCM_GENPD_SSWRP_LSIO_E 4
#define LPCM_GENPD_SSWRP_G2D 5
#define LPCM_GENPD_SSWRP_PCIE 6
#define LPCM_GENPD_SSWRP_ISPFE 7
#define LPCM_GENPD_SSWRP_AOSS 8
#define LPCM_GENPD_SSWRP_COUNT 9

static const u32 sswrp_id_cpm_lpcm_mapping[] = {
	[GENPD_MBU_SSWRP_AOSS_AMBSS_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_AOSS_AONSS_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_AOSS_PG_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_AURDSP_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_BMSM_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_CODEC_3P_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_CPU_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_CPUACC_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_DPU_ID]	= LPCM_GENPD_SSWRP_DPU,
	[GENPD_MBU_SSWRP_FABDISP_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_FABHBW_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_FABMED_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_FABSTBY_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_FABSYSS_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_G2D_ID]	= LPCM_GENPD_SSWRP_G2D,
	[GENPD_MBU_SSWRP_GCV_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GMC0_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GMC1_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GMC2_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GMC3_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GPCA_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GPCM_AMB_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GPCM_INFRA_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GPU_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_GSA_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_HSIO_N_ID]	= LPCM_GENPD_SSWRP_HSIO_N,
	[GENPD_MBU_SSWRP_HSIO_S_ID]	= LPCM_GENPD_SSWRP_HSIO_S,
	[GENPD_MBU_SSWRP_ISPBE_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_ISPFE_ID]	= LPCM_GENPD_SSWRP_ISPFE,
	[GENPD_MBU_SSWRP_LSIO_E_ID]	= LPCM_GENPD_SSWRP_LSIO_E,
	[GENPD_MBU_SSWRP_LSIO_S_ID]	= LPCM_GENPD_SSWRP_LSIO_S,
	[GENPD_MBU_SSWRP_MEMSS_ID]	= NOT_SUPPORTED,
	[GENPD_MBU_SSWRP_PCIE_ID]	= LPCM_GENPD_SSWRP_PCIE,
	[GENPD_MBU_SSWRP_TPU_ID]	= NOT_SUPPORTED,
};

const struct cpm_mappings mbu_cpm_mappings = {
	.sswrp_to_lpb_ids = NULL,
	.sswrp_to_lpcm_ids = sswrp_id_cpm_lpcm_mapping,
};
