/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright 2025 Google LLC
 */
#ifndef _UFS_REGS_GEN_H_
#define _UFS_REGS_GEN_H_

/* DONOT modify manually. Use go/ufs-autogen */

/* Begin autogen region hc signature: 8d2419ec */
enum hc_offset {
	REG_IS = 0x20,
	REG_BUSTHRTL = 0xc0,
	REG_SECURITY = 0xcc,
	REG_UFSHC_VER_ID_REG = 0xd0,
	REG_UFSHC_VER_TYPE_REG = 0xd4,
	REG_VS_OOO_CONFIG = 0xd8,
	REG_VS_IAG = 0xdc,
	REG_VS_CQES = 0xe0,
	REG_HCLKDIV = 0xf8,
	REG_EXTND_VENDOR_REG_POINTER = 0xfc,
	REG_CCAP = 0x100,
	REG_CRYPTOCAP_0 = 0x104,
	REG_CRYPTOCAP_1 = 0x108,
	REG_UFS_SFTY_MECHANISM_MONITOR_EN_REG = 0x214,
	REG_CONFIG = 0x300,
	REG_MCQCONFIG = 0x380,
};

enum is_bitfields {
	UTRCS_OFFSET = 0x0U,
	UTRCS_MASK = 0x1U,
	UTRCS_DEFAULT = 0x0U,
	UDEPRI_OFFSET = 0x1U,
	UDEPRI_MASK = 0x2U,
	UDEPRI_DEFAULT = 0x0U,
	UE_OFFSET = 0x2U,
	UE_MASK = 0x4U,
	UE_DEFAULT = 0x0U,
	UTMS_OFFSET = 0x3U,
	UTMS_MASK = 0x8U,
	UTMS_DEFAULT = 0x0U,
	UPMS_OFFSET = 0x4U,
	UPMS_MASK = 0x10U,
	UPMS_DEFAULT = 0x0U,
	UHXS_OFFSET = 0x5U,
	UHXS_MASK = 0x20U,
	UHXS_DEFAULT = 0x0U,
	UHES_OFFSET = 0x6U,
	UHES_MASK = 0x40U,
	UHES_DEFAULT = 0x0U,
	ULLS_OFFSET = 0x7U,
	ULLS_MASK = 0x80U,
	ULLS_DEFAULT = 0x0U,
	ULSS_OFFSET = 0x8U,
	ULSS_MASK = 0x100U,
	ULSS_DEFAULT = 0x0U,
	UTMRCS_OFFSET = 0x9U,
	UTMRCS_MASK = 0x200U,
	UTMRCS_DEFAULT = 0x0U,
	UCCS_OFFSET = 0xaU,
	UCCS_MASK = 0x400U,
	UCCS_DEFAULT = 0x0U,
	DFES_OFFSET = 0xbU,
	DFES_MASK = 0x800U,
	DFES_DEFAULT = 0x0U,
	UTPES_OFFSET = 0xcU,
	UTPES_MASK = 0x1000U,
	UTPES_DEFAULT = 0x0U,
	IS_RSVD_15_13_OFFSET = 0xdU,
	IS_RSVD_15_13_MASK = 0xe000U,
	IS_RSVD_15_13_DEFAULT = 0x0U,
	HCFES_OFFSET = 0x10U,
	HCFES_MASK = 0x10000U,
	HCFES_DEFAULT = 0x0U,
	SBFES_OFFSET = 0x11U,
	SBFES_MASK = 0x20000U,
	SBFES_DEFAULT = 0x0U,
	CEFES_OFFSET = 0x12U,
	CEFES_MASK = 0x40000U,
	CEFES_DEFAULT = 0x0U,
	SQES_OFFSET = 0x13U,
	SQES_MASK = 0x80000U,
	SQES_DEFAULT = 0x0U,
	CQES_OFFSET = 0x14U,
	CQES_MASK = 0x100000U,
	CQES_DEFAULT = 0x0U,
	IAGES_OFFSET = 0x15U,
	IAGES_MASK = 0x200000U,
	IAGES_DEFAULT = 0x0U,
	IS_RSVD_28_22_OFFSET = 0x16U,
	IS_RSVD_28_22_MASK = 0x1fc00000U,
	IS_RSVD_28_22_DEFAULT = 0x0U,
	CIS_OFFSET = 0x1dU,
	CIS_MASK = 0x20000000U,
	CIS_DEFAULT = 0x0U,
	CRS_OFFSET = 0x1eU,
	CRS_MASK = 0x40000000U,
	CRS_DEFAULT = 0x0U,
	CTES_OFFSET = 0x1fU,
	CTES_MASK = 0x80000000U,
	CTES_DEFAULT = 0x0U,
};

enum busthrtl_bitfields {
	BUSDLY_OFFSET = 0x0U,
	BUSDLY_MASK = 0xffU,
	BUSDLY_DEFAULT = 0x0U,
	CGE_OFFSET = 0xcU,
	CGE_MASK = 0x1000U,
	CGE_DEFAULT = 0x1U,
	MBL_OFFSET = 0xdU,
	MBL_MASK = 0xe000U,
	MBL_DEFAULT = 0x3U,
	LP_PGE_OFFSET = 0x10U,
	LP_PGE_MASK = 0x10000U,
	LP_PGE_DEFAULT = 0x1U,
	LP_AH8_PGE_OFFSET = 0x11U,
	LP_AH8_PGE_MASK = 0x20000U,
	LP_AH8_PGE_DEFAULT = 0x1U,
	MAXOBUSR_OFFSET = 0x12U,
	MAXOBUSR_MASK = 0xfc0000U,
	MAXOBUSR_DEFAULT = 0x18U,
	BUSTHRTL_RSVD_27_24_OFFSET = 0x18U,
	BUSTHRTL_RSVD_27_24_MASK = 0xf000000U,
	BUSTHRTL_RSVD_27_24_DEFAULT = 0x0U,
	DME_CTRL_LOGIC_EN_OFFSET = 0x1cU,
	DME_CTRL_LOGIC_EN_MASK = 0x10000000U,
	DME_CTRL_LOGIC_EN_DEFAULT = 0x1U,
	LP_NOCARD_PGE_OFFSET = 0x1dU,
	LP_NOCARD_PGE_MASK = 0x20000000U,
	LP_NOCARD_PGE_DEFAULT = 0x0U,
	BUSTHRTL_RSVD_31_30_OFFSET = 0x1eU,
	BUSTHRTL_RSVD_31_30_MASK = 0xc0000000U,
	BUSTHRTL_RSVD_31_30_DEFAULT = 0x0U,
};

enum security_bitfields {
	KEY_ACC_SEL_OFFSET = 0x0U,
	KEY_ACC_SEL_MASK = 0x1U,
	KEY_ACC_SEL_DEFAULT = 0x0U,
	SECURITY_RSVD_31_1_OFFSET = 0x1U,
	SECURITY_RSVD_31_1_MASK = 0xfffffffeU,
	SECURITY_RSVD_31_1_DEFAULT = 0x0U,
};

enum ufshc_ver_id_reg_bitfields {
	UFSHC_VER_ID_OFFSET = 0x0U,
	UFSHC_VER_ID_MASK = 0xffffffffU,
	UFSHC_VER_ID_DEFAULT = 0x3132332aU,
};

enum ufshc_ver_type_reg_bitfields {
	UFSHC_VER_TYPE_OFFSET = 0x0U,
	UFSHC_VER_TYPE_MASK = 0xffffffffU,
	UFSHC_VER_TYPE_DEFAULT = 0x65613034U,
};

enum vs_ooo_config_bitfields {
	LBS_OFFSET = 0x0U,
	LBS_MASK = 0xfU,
	LBS_DEFAULT = 0x1U,
	VS_OOO_CONFIG_RSVD_31_4_OFFSET = 0x4U,
	VS_OOO_CONFIG_RSVD_31_4_MASK = 0xfffffff0U,
	VS_OOO_CONFIG_RSVD_31_4_DEFAULT = 0x0U,
};

enum vs_iag_bitfields {
	IAG_ID_OFFSET = 0x0U,
	IAG_ID_MASK = 0xffffU,
	IAG_ID_DEFAULT = 0x0U,
	VS_IAG_RSVD_OFFSET = 0x10U,
	VS_IAG_RSVD_MASK = 0xffff0000U,
	VS_IAG_RSVD_DEFAULT = 0x0U,
};

enum vs_cqes_bitfields {
	CQES_CQID_OFFSET = 0x0U,
	CQES_CQID_MASK = 0xffffU,
	CQES_CQID_DEFAULT = 0x0U,
	VS_CQES_RSVD_OFFSET = 0x10U,
	VS_CQES_RSVD_MASK = 0xffff0000U,
	VS_CQES_RSVD_DEFAULT = 0x0U,
};

enum hclkdiv_bitfields {
	HCLKDIV_OFFSET = 0x0U,
	HCLKDIV_MASK = 0xffffU,
	HCLKDIV_DEFAULT = 0x190U,
	HCLKDIV_RSVD_31_16_OFFSET = 0x10U,
	HCLKDIV_RSVD_31_16_MASK = 0xffff0000U,
	HCLKDIV_RSVD_31_16_DEFAULT = 0x0U,
};

enum extnd_vendor_reg_pointer_bitfields {
	SECTION_OFFSET_OFFSET = 0x0U,
	SECTION_OFFSET_MASK = 0xffffffffU,
	SECTION_OFFSET_DEFAULT = 0x200U,
};

enum ccap_bitfields {
	CC_OFFSET = 0x0U,
	CC_MASK = 0xffU,
	CC_DEFAULT = 0x2U,
	CFGC_OFFSET = 0x8U,
	CFGC_MASK = 0xff00U,
	CFGC_DEFAULT = 0x3fU,
	CCAP_RSVD_23_16_OFFSET = 0x10U,
	CCAP_RSVD_23_16_MASK = 0xff0000U,
	CCAP_RSVD_23_16_DEFAULT = 0x0U,
	CFGPTR_OFFSET = 0x18U,
	CFGPTR_MASK = 0xff000000U,
	CFGPTR_DEFAULT = 0x5U,
};

enum cryptocap_0_bitfields {
	CRYPTOCAP_0_ALGID_OFFSET = 0x0U,
	CRYPTOCAP_0_ALGID_MASK = 0xffU,
	CRYPTOCAP_0_ALGID_DEFAULT = 0x0U,
	CRYPTOCAP_0_SDUSB_OFFSET = 0x8U,
	CRYPTOCAP_0_SDUSB_MASK = 0xff00U,
	CRYPTOCAP_0_SDUSB_DEFAULT = 0x7fU,
	CRYPTOCAP_0_KS_OFFSET = 0x10U,
	CRYPTOCAP_0_KS_MASK = 0xff0000U,
	CRYPTOCAP_0_KS_DEFAULT = 0x3U,
	CRYPTOCAP_0_RSVD_31_24_OFFSET = 0x18U,
	CRYPTOCAP_0_RSVD_31_24_MASK = 0xff000000U,
	CRYPTOCAP_0_RSVD_31_24_DEFAULT = 0x0U,
};

enum cryptocap_1_bitfields {
	CRYPTOCAP_1_ALGID_OFFSET = 0x0U,
	CRYPTOCAP_1_ALGID_MASK = 0xffU,
	CRYPTOCAP_1_ALGID_DEFAULT = 0x0U,
	CRYPTOCAP_1_SDUSB_OFFSET = 0x8U,
	CRYPTOCAP_1_SDUSB_MASK = 0xff00U,
	CRYPTOCAP_1_SDUSB_DEFAULT = 0x7fU,
	CRYPTOCAP_1_KS_OFFSET = 0x10U,
	CRYPTOCAP_1_KS_MASK = 0xff0000U,
	CRYPTOCAP_1_KS_DEFAULT = 0x3U,
	CRYPTOCAP_1_RSVD_31_24_OFFSET = 0x18U,
	CRYPTOCAP_1_RSVD_31_24_MASK = 0xff000000U,
	CRYPTOCAP_1_RSVD_31_24_DEFAULT = 0x0U,
};

enum ufs_sfty_mechanism_monitor_en_reg_bitfields {
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_OFFSET = 0x0U,
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_MASK = 0xffffffffU,
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_DEFAULT = 0x0U,
};

enum config_bitfields {
	QT_OFFSET = 0x0U,
	QT_MASK = 0x1U,
	QT_DEFAULT = 0x0U,
	ESIE_OFFSET = 0x1U,
	ESIE_MASK = 0x2U,
	ESIE_DEFAULT = 0x0U,
	DW2PRDTEN_OFFSET = 0x2U,
	DW2PRDTEN_MASK = 0x4U,
	DW2PRDTEN_DEFAULT = 0x0U,
	CONFIG_RSVD_31_3_OFFSET = 0x3U,
	CONFIG_RSVD_31_3_MASK = 0xfffffff8U,
	CONFIG_RSVD_31_3_DEFAULT = 0x0U,
};

enum mcqconfig_bitfields {
	AS_OFFSET = 0x0U,
	AS_MASK = 0x3U,
	AS_DEFAULT = 0x0U,
	MCQCONFIG_RSVD_7_2_OFFSET = 0x2U,
	MCQCONFIG_RSVD_7_2_MASK = 0xfcU,
	MCQCONFIG_RSVD_7_2_DEFAULT = 0x0U,
	MAC_OFFSET = 0x8U,
	MAC_MASK = 0x1ff00U,
	MAC_DEFAULT = 0x1fU,
	MCQCONFIG_RSVD_31_17_OFFSET = 0x11U,
	MCQCONFIG_RSVD_31_17_MASK = 0xfffe0000U,
	MCQCONFIG_RSVD_31_17_DEFAULT = 0x0U,
};
/* End autogen region hc */

/* Begin autogen region top signature: 91ad6a9c */
enum top_offset {
	REG_HSIOS_UFS_VERSION = 0x0,
	REG_HSIOS_UFS_CARD_DET = 0x4,
	REG_HSIOS_UFS_ENC_STAT = 0x8,
	REG_HSIOS_UFS_MONITOR_1 = 0x10,
	REG_HSIOS_UFS_MONITOR_2 = 0x14,
	REG_HSIOS_UFS_MONITOR_3 = 0x18,
	REG_HSIOS_UFS_MONITOR_4 = 0x20,
	REG_HSIOS_UFS_UNIPRO_MON_1 = 0x24,
	REG_HSIOS_UFS_UNIPRO_MON_2 = 0x28,
	REG_HSIOS_UFS_UNIPRO_MON_3 = 0x30,
	REG_HSIOS_UFS_MPHY_DTB = 0x40,
	REG_HSIOS_UFS_PWR_CTRL = 0x100,
	REG_HSIOS_UFS_REXT_CTRL = 0x110,
	REG_HSIOS_UFS_AXQOS_OVRD = 0x200,
	REG_HSIOS_UFS_PHYCLK_SEL = 0x208,
	REG_HSIOS_UFS_CFG_CLKSEL = 0x210,
	REG_HSIOS_UFS_MPHY_CFG = 0x214,
	REG_HSIOS_UFS_SRAM_APB_MODE = 0x510,
	REG_HSIOS_UFS_LA_RSTMODE_REQ = 0x514,
};

enum hsios_ufs_version_bitfields {
	UFS_MAJOR_VERSION_OFFSET = 0x0U,
	UFS_MAJOR_VERSION_MASK = 0xffU,
	UFS_MAJOR_VERSION_DEFAULT = 0x1U,
	UFS_MINOR_VERSION_OFFSET = 0x8U,
	UFS_MINOR_VERSION_MASK = 0xff00U,
	UFS_MINOR_VERSION_DEFAULT = 0x2U,
};

enum hsios_ufs_card_det_bitfields {
	UFS_REG_CARD_DET_OFFSET = 0x0U,
	UFS_REG_CARD_DET_MASK = 0x1U,
	UFS_REG_CARD_DET_DEFAULT = 0x1U,
};

enum hsios_ufs_enc_stat_bitfields {
	CRYPTO_KAT_FAIL_STAT_OFFSET = 0x0U,
	CRYPTO_KAT_FAIL_STAT_MASK = 0xfU,
	CRYPTO_KAT_FAIL_STAT_DEFAULT = 0x0U,
	CRYPTO_KAT_STAT_OFFSET = 0x4U,
	CRYPTO_KAT_STAT_MASK = 0x10U,
	CRYPTO_KAT_STAT_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_1_bitfields {
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_2_bitfields {
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_3_bitfields {
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_4_bitfields {
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_1_bitfields {
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_MASK = 0xffffffffU,
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_2_bitfields {
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_MASK = 0xffffffffU,
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_3_bitfields {
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_MASK = 0xffffU,
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_mphy_dtb_bitfields {
	MPHY_DTB_OUT_OFFSET = 0x0U,
	MPHY_DTB_OUT_MASK = 0x3U,
	MPHY_DTB_OUT_DEFAULT = 0x0U,
};

enum hsios_ufs_pwr_ctrl_bitfields {
	UFS_SRAM_BYPASS_OFFSET = 0x10U,
	UFS_SRAM_BYPASS_MASK = 0x30000U,
	UFS_SRAM_BYPASS_DEFAULT = 0x0U,
	UFS_SRAM_BOOTLOAD_BYPASS_OFFSET = 0x12U,
	UFS_SRAM_BOOTLOAD_BYPASS_MASK = 0xc0000U,
	UFS_SRAM_BOOTLOAD_BYPASS_DEFAULT = 0x0U,
	UFS_SRAM_EXT_LD_DONE_OFFSET = 0x14U,
	UFS_SRAM_EXT_LD_DONE_MASK = 0x100000U,
	UFS_SRAM_EXT_LD_DONE_DEFAULT = 0x0U,
	UFS_SRAM_INIT_DONE_OFFSET = 0x15U,
	UFS_SRAM_INIT_DONE_MASK = 0x200000U,
	UFS_SRAM_INIT_DONE_DEFAULT = 0x0U,
};

enum hsios_ufs_rext_ctrl_bitfields {
	UFS_REXT_CONTROL_OFFSET = 0x0U,
	UFS_REXT_CONTROL_MASK = 0x3fU,
	UFS_REXT_CONTROL_DEFAULT = 0x0U,
	UFS_REXT_EN_OFFSET = 0x6U,
	UFS_REXT_EN_MASK = 0x40U,
	UFS_REXT_EN_DEFAULT = 0x0U,
	UFS_PRE_VREG_BYPASS_OFFSET = 0x7U,
	UFS_PRE_VREG_BYPASS_MASK = 0x80U,
	UFS_PRE_VREG_BYPASS_DEFAULT = 0x0U,
};

enum hsios_ufs_axqos_ovrd_bitfields {
	UFS_R_VC_OVRD_EN_OFFSET = 0x0U,
	UFS_R_VC_OVRD_EN_MASK = 0x1U,
	UFS_R_VC_OVRD_EN_DEFAULT = 0x0U,
	UFS_R_VC_OVRD_VAL_OFFSET = 0x4U,
	UFS_R_VC_OVRD_VAL_MASK = 0xf0U,
	UFS_R_VC_OVRD_VAL_DEFAULT = 0x0U,
	UFS_W_VC_OVRD_EN_OFFSET = 0x8U,
	UFS_W_VC_OVRD_EN_MASK = 0x100U,
	UFS_W_VC_OVRD_EN_DEFAULT = 0x0U,
	UFS_W_VC_OVRD_VAL_OFFSET = 0xcU,
	UFS_W_VC_OVRD_VAL_MASK = 0xf000U,
	UFS_W_VC_OVRD_VAL_DEFAULT = 0x0U,
	UFS_ARQOS_OVRD_EN_OFFSET = 0x10U,
	UFS_ARQOS_OVRD_EN_MASK = 0x10000U,
	UFS_ARQOS_OVRD_EN_DEFAULT = 0x0U,
	UFS_ARQOS_OVRD_VAL_OFFSET = 0x14U,
	UFS_ARQOS_OVRD_VAL_MASK = 0xf00000U,
	UFS_ARQOS_OVRD_VAL_DEFAULT = 0x0U,
	UFS_AWQOS_OVRD_EN_OFFSET = 0x18U,
	UFS_AWQOS_OVRD_EN_MASK = 0x1000000U,
	UFS_AWQOS_OVRD_EN_DEFAULT = 0x0U,
	UFS_AWQOS_OVRD_VAL_OFFSET = 0x1cU,
	UFS_AWQOS_OVRD_VAL_MASK = 0xf0000000U,
	UFS_AWQOS_OVRD_VAL_DEFAULT = 0x0U,
};

enum hsios_ufs_phyclk_sel_bitfields {
	REF_CLK_SEL_OFFSET = 0x0U,
	REF_CLK_SEL_MASK = 0x7U,
	REF_CLK_SEL_DEFAULT = 0x2U,
};

enum hsios_ufs_cfg_clksel_bitfields {
	CFG_CLK_SEL_OFFSET = 0x0U,
	CFG_CLK_SEL_MASK = 0x7U,
	CFG_CLK_SEL_DEFAULT = 0x2U,
};

enum hsios_ufs_mphy_cfg_bitfields {
	UFS_MPHY_CFG_OFFSET = 0x0U,
	UFS_MPHY_CFG_MASK = 0x3U,
	UFS_MPHY_CFG_DEFAULT = 0x1U,
};

enum hsios_ufs_sram_apb_mode_bitfields {
	UFS_SRAM_APB_MODE_OFFSET = 0x0U,
	UFS_SRAM_APB_MODE_MASK = 0x1U,
	UFS_SRAM_APB_MODE_DEFAULT = 0x0U,
};

enum hsios_ufs_la_rstmode_req_bitfields {
	UFS_LA_RSTMODE_REQ_OFFSET = 0x0U,
	UFS_LA_RSTMODE_REQ_MASK = 0x1U,
	UFS_LA_RSTMODE_REQ_DEFAULT = 0x0U,
};
/* End autogen region top */

/* Begin autogen region ss signature: 19c05a2a */
enum ss_offset {
	REG_REFCLK_GATING_CONTROL = 0x0,
	REG_REFCLK_SWITCHOFF_TIME = 0x4,
	REG_REFCLK_SWITCHON_TIME = 0x8,
	REG_MPHY_CFGBUSY_STATUS = 0x14,
};

enum refclk_gating_control_bitfields {
	REFCLK_GATE_ENABLE_OFFSET = 0x0U,
	REFCLK_GATE_ENABLE_MASK = 0x1U,
	REFCLK_GATE_ENABLE_DEFAULT = 0x0U,
	RESERVED_31_1_OFFSET = 0x1U,
	RESERVED_31_1_MASK = 0xfffffffeU,
	RESERVED_31_1_DEFAULT = 0x0U,
};

enum refclk_switchoff_time_bitfields {
	REFCLK_SWOFF_TIME_OFFSET = 0x0U,
	REFCLK_SWOFF_TIME_MASK = 0xffU,
	REFCLK_SWOFF_TIME_DEFAULT = 0x0U,
	REFCLK_SWITCHOFF_TIME_RESERVED_31_8_OFFSET = 0x8U,
	REFCLK_SWITCHOFF_TIME_RESERVED_31_8_MASK = 0xffffff00U,
	REFCLK_SWITCHOFF_TIME_RESERVED_31_8_DEFAULT = 0x0U,
};

enum refclk_switchon_time_bitfields {
	REFCLK_SWON_TIME_OFFSET = 0x0U,
	REFCLK_SWON_TIME_MASK = 0xffU,
	REFCLK_SWON_TIME_DEFAULT = 0x0U,
	REFCLK_SWITCHON_TIME_RESERVED_31_8_OFFSET = 0x8U,
	REFCLK_SWITCHON_TIME_RESERVED_31_8_MASK = 0xffffff00U,
	REFCLK_SWITCHON_TIME_RESERVED_31_8_DEFAULT = 0x0U,
};

enum mphy_cfgbusy_status_bitfields {
	MPHY_TX_BUSY_STATUS_OFFSET = 0x0U,
	MPHY_TX_BUSY_STATUS_MASK = 0x3U,
	MPHY_TX_BUSY_STATUS_DEFAULT = 0x0U,
	MPHY_RX_BUSY_STATUS_OFFSET = 0x2U,
	MPHY_RX_BUSY_STATUS_MASK = 0xcU,
	MPHY_RX_BUSY_STATUS_DEFAULT = 0x0U,
	RESERVED_31_4_OFFSET = 0x4U,
	RESERVED_31_4_MASK = 0xfffffff0U,
	RESERVED_31_4_DEFAULT = 0x0U,
};
/* End autogen region ss */

/* Begin autogen region cg_hsio_s_gpio_ref_clk signature: a6818de0 */
enum cg_hsio_s_gpio_ref_clk_offset {
	REG_CLK_GATE_CTRL_MODE = 0x0,
	REG_CLK_GATE_CLK_EN = 0x4,
	REG_CLK_GATE_AUTO_GATE = 0x18,
};

enum clk_gate_ctrl_mode_bitfields {
	CTRL_MODE_OFFSET = 0x0U,
	CTRL_MODE_MASK = 0x1U,
	CTRL_MODE_DEFAULT = 0x1U,
};

enum clk_gate_clk_en_bitfields {
	CLK_EN_OFFSET = 0x0U,
	CLK_EN_MASK = 0x1U,
	CLK_EN_DEFAULT = 0x0U,
};

enum clk_gate_auto_gate_bitfields {
	AUTO_GATE_OFFSET = 0x0U,
	AUTO_GATE_MASK = 0x1U,
	AUTO_GATE_DEFAULT = 0x0U,
	HYSTERESIS_VAL_OFFSET = 0x1U,
	HYSTERESIS_VAL_MASK = 0x1feU,
	HYSTERESIS_VAL_DEFAULT = 0x20U,
};
/* End autogen region cg_hsio_s_gpio_ref_clk */

/* Begin autogen region lpm_hsi1 signature: 5b7277a1 */
enum lpm_hsi1_offset {
	REG_PSM_1__STATUS = 0x210,
	REG_GSPAN_UFS_INITIATOR_ICD_GSPAN_STATUS = 0x554,
};

enum psm_1_status_bitfields {
	CURR_STATE_OFFSET = 0x0U,
	CURR_STATE_MASK = 0xfU,
	CURR_STATE_DEFAULT = 0x0U,
	STATE_VALID_OFFSET = 0x4U,
	STATE_VALID_MASK = 0x10U,
	STATE_VALID_DEFAULT = 0x0U,
	PSM_STS_OFFSET = 0x5U,
	PSM_STS_MASK = 0x60U,
	PSM_STS_DEFAULT = 0x0U,
	SW_SEQ_DONE_OFFSET = 0x7U,
	SW_SEQ_DONE_MASK = 0x80U,
	SW_SEQ_DONE_DEFAULT = 0x0U,
	PSM_ERR_OFFSET = 0x8U,
	PSM_ERR_MASK = 0x100U,
	PSM_ERR_DEFAULT = 0x0U,
	SEQ_ERR_OFFSET = 0x9U,
	SEQ_ERR_MASK = 0x200U,
	SEQ_ERR_DEFAULT = 0x0U,
};

enum gspan_ufs_initiator_icd_gspan_status_bitfields {
	INT_IDOREQ_OFFSET = 0x0U,
	INT_IDOREQ_MASK = 0x1U,
	INT_IDOREQ_DEFAULT = 0x0U,
	INT_IDOACK_OFFSET = 0x1U,
	INT_IDOACK_MASK = 0x2U,
	INT_IDOACK_DEFAULT = 0x0U,
	INT_IDONAK_OFFSET = 0x2U,
	INT_IDONAK_MASK = 0x4U,
	INT_IDONAK_DEFAULT = 0x0U,
	INT_IDOMODE_OFFSET = 0x3U,
	INT_IDOMODE_MASK = 0x8U,
	INT_IDOMODE_DEFAULT = 0x0U,
	IDIREQ_OFFSET = 0x4U,
	IDIREQ_MASK = 0x10U,
	IDIREQ_DEFAULT = 0x0U,
	IDIACK_OFFSET = 0x5U,
	IDIACK_MASK = 0x20U,
	IDIACK_DEFAULT = 0x0U,
	IDINAK_OFFSET = 0x6U,
	IDINAK_MASK = 0x40U,
	IDINAK_DEFAULT = 0x0U,
	IDIMODE_OFFSET = 0x7U,
	IDIMODE_MASK = 0x80U,
	IDIMODE_DEFAULT = 0x0U,
	FENCE_OFFSET = 0x8U,
	FENCE_MASK = 0x100U,
	FENCE_DEFAULT = 0x1U,
	OUTSTANDING_OFFSET = 0x9U,
	OUTSTANDING_MASK = 0x200U,
	OUTSTANDING_DEFAULT = 0x0U,
	LINK_CONN_OFFSET = 0xaU,
	LINK_CONN_MASK = 0x400U,
	LINK_CONN_DEFAULT = 0x0U,
	LINK_DSCGT_OFFSET = 0xbU,
	LINK_DSCGT_MASK = 0x800U,
	LINK_DSCGT_DEFAULT = 0x1U,
	FSM_STATE_OFFSET = 0xcU,
	FSM_STATE_MASK = 0x1f000U,
	FSM_STATE_DEFAULT = 0x0U,
};
/* End autogen region lpm_hsi1 */

#endif /* _UFS_REGS_GEN_H_ */
