# SPDX-License-Identifier: GPL-2.0-or-later

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch")
load("//private/devices/google/common/kleaf:device_build.bzl", "device_build", "gki_module", "intree_module")
load(":constants.bzl", "MALIBU_DTBS", "MALIBU_MODULE_OUTS")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

device_build(
    name = "malibu_base",
    bste_test_suites = [
        "//private/google-modules/soc/rdo/power-controller/tests:mbu_test_suites",
    ],
    build_configs = ["build.config.malibu"],
    ddk_uapi_headers = [
        # keep sorted
        "//private/google-modules/aoc/alsa:uapi_headers",
        "//private/google-modules/display/common:uapi_headers",
        "//private/google-modules/display/vsi-drm:uapi_headers",
        "//private/google-modules/image/cnm:uapi_headers",
        "//private/google-modules/soc/gs:misc_uapi_headers",
        "//private/google-modules/touch/common:uapi_headers",
        "//private/google-modules/video/cnm:uapi_headers",
    ],
    defconfig_fragments = ["malibu_defconfig"],
    kconfig_exts = ["Kconfig.ext.malibu"],
    kconfigs = [
        # keep sorted
        "//private/google-modules/aoc:aoc.kconfig",
        "//private/google-modules/aoc/alsa:alsa.kconfig",
        "//private/google-modules/aoc/usb:aoc.usb.kconfig",
        "//private/google-modules/bms/misc:bms-misc.kconfig",
        "//private/google-modules/display/common:common.kconfig",
        "//private/google-modules/display/interfaces/synopsys/dwc_dptx:dwc_dptx.kconfig",
        "//private/google-modules/display/vsi-drm:vsi-drm.kconfig",
        "//private/google-modules/display/vsi-g2d:drm-g2d.kconfig",
        "//private/google-modules/iommu/arm-smmu-v3:arm-smmu-v3.kconfig",
        "//private/google-modules/lwis:lwis.kconfig",
        "//private/google-modules/misc/h2omg:h2omg.kconfig",
        "//private/google-modules/perf:perf.kconfig",
        "//private/google-modules/power/mitigation:bcl.kconfig",
        "//private/google-modules/power/reset:reset.kconfig",
        "//private/google-modules/powervr:powervr.kconfig",
        "//private/google-modules/radio/common/metrics_collection:metrics_collection.kconfig",
        "//private/google-modules/radio/common/radio-bridge:radio-bridge.kconfig",
        "//private/google-modules/soc/gs/drivers/bts:kconfig",
        "//private/google-modules/soc/gs/drivers/char/hw_random:kconfig",
        "//private/google-modules/soc/gs/drivers/clk/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/clocksource:kconfig",
        "//private/google-modules/soc/gs/drivers/cpufreq:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq-whi/google:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq/google:kconfig",
        "//private/google-modules/soc/gs/drivers/dma:kconfig",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:dmabuf-heaps-kconfig_group",
        "//private/google-modules/soc/gs/drivers/gpu/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/gpu/exynos/g2d:kconfig",
        "//private/google-modules/soc/gs/drivers/i2c/busses:kconfig",
        "//private/google-modules/soc/gs/drivers/iio:kconfig",
        "//private/google-modules/soc/gs/drivers/iio/power:kconfig",
        "//private/google-modules/soc/gs/drivers/input:kconfig",
        "//private/google-modules/soc/gs/drivers/input/keyboard:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc/vl53l1:kconfig",
        "//private/google-modules/soc/gs/drivers/iommu:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos/mfc:kconfig",
        "//private/google-modules/soc/gs/drivers/mfd:kconfig",
        "//private/google-modules/soc/gs/drivers/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump:sscoredump.kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc:kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc-whi:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/gs_perf_mon:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/lat_governors:kconfig",
        "//private/google-modules/soc/gs/drivers/phy/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/power:kconfig",
        "//private/google-modules/soc/gs/drivers/power/reset:kconfig",
        "//private/google-modules/soc/gs/drivers/pwm:kconfig",
        "//private/google-modules/soc/gs/drivers/regulator:kconfig",
        "//private/google-modules/soc/gs/drivers/rtc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/boot_control:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gcma:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gnssif_spi:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa.kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pa_kill:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pkvm-smc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/s2mpu:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/smra:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:kconfig",
        "//private/google-modules/soc/gs/drivers/spi:kconfig",
        "//private/google-modules/soc/gs/drivers/spmi:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/google:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/tty/serial:kconfig",
        "//private/google-modules/soc/gs/drivers/ufs:kconfig",
        "//private/google-modules/soc/gs/drivers/usb:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/dwc3:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/gadget:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/host:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:role-sw.kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:kconfig",
        "//private/google-modules/soc/gs/drivers/video/backlight:kconfig",
        "//private/google-modules/soc/gs/drivers/watchdog:kconfig",
        "//private/google-modules/soc/rdo:kconfig",
        "//private/google-modules/soc/rdo/aoss-ssr-notifier:kconfig",
        "//private/google-modules/soc/rdo/ap-pmic:kconfig",
        "//private/google-modules/soc/rdo/boot-diary:google_boot_diary.kconfig",
        "//private/google-modules/soc/rdo/cap-sysfs:google_cap_sysfs.kconfig",
        "//private/google-modules/soc/rdo/clk/google:lcm-google.kconfig",
        "//private/google-modules/soc/rdo/clocksource/google/sst:google_sst.kconfig",
        "//private/google-modules/soc/rdo/cpm-cli:google_cpm_cli.kconfig",
        "//private/google-modules/soc/rdo/cpu-lpm-stats:google_cpu_lpm_stats.kconfig",
        "//private/google-modules/soc/rdo/cs-ets:cs-ets.kconfig",
        "//private/google-modules/soc/rdo/cstate-ctrl:cstate-ctrl.kconfig",
        "//private/google-modules/soc/rdo/drivers/clk/google:clk-cpm.kconfig",
        "//private/google-modules/soc/rdo/drivers/dma:google_dma.kconfig",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:kconfig",
        "//private/google-modules/soc/rdo/drivers/i3c/master:kconfig",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:kconfig",
        "//private/google-modules/soc/rdo/drivers/iis:iis.kconfig",
        "//private/google-modules/soc/rdo/drivers/irqchip:kconfig",
        "//private/google-modules/soc/rdo/drivers/mailbox:kconfig",
        "//private/google-modules/soc/rdo/drivers/perf:kconfig",
        "//private/google-modules/soc/rdo/drivers/pinctrl/google:kconfig",
        "//private/google-modules/soc/rdo/drivers/power:kconfig",
        "//private/google-modules/soc/rdo/drivers/rst/google:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google:soc_google.kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd-cpu:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwmt:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp.kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:kconfig",
        "//private/google-modules/soc/rdo/drivers/spi:kconfig",
        "//private/google-modules/soc/rdo/drivers/spmi:kconfig",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:kconfig",
        "//private/google-modules/soc/rdo/drivers/tty/serial/modem-uart:kconfig",
        "//private/google-modules/soc/rdo/drivers/ufs:ufs.kconfig",
        "//private/google-modules/soc/rdo/ebu:kconfig",
        "//private/google-modules/soc/rdo/edac:kconfig",
        "//private/google-modules/soc/rdo/experimental:kconfig",
        "//private/google-modules/soc/rdo/gadget/dta:kconfig",
        "//private/google-modules/soc/rdo/gadget/perf_test:kconfig",
        "//private/google-modules/soc/rdo/gpca:kconfig",
        "//private/google-modules/soc/rdo/hardlockup-debug:kconfig",
        "//private/google-modules/soc/rdo/interconnect:kconfig",
        "//private/google-modules/soc/rdo/ip-idle-notifier:kconfig",
        "//private/google-modules/soc/rdo/lpcm:kconfig",
        "//private/google-modules/soc/rdo/mem-qos:google-mem-qos.kconfig",
        "//private/google-modules/soc/rdo/odpm:kconfig",
        "//private/google-modules/soc/rdo/pci:Kconfig",
        "//private/google-modules/soc/rdo/phy:kconfig",
        "//private/google-modules/soc/rdo/power-controller:kconfig",
        "//private/google-modules/soc/rdo/powerdashboard:kconfig",
        "//private/google-modules/soc/rdo/pwm:kconfig",
        "//private/google-modules/soc/rdo/soc/google:kconfig",
        "//private/google-modules/soc/rdo/thermal:kconfig",
        "//private/google-modules/soc/rdo/trace:kconfig",
        "//private/google-modules/soc/rdo/usb:kconfig",
        "//private/google-modules/soc/rdo/watchdog:kconfig",
        "//private/google-modules/touch/common:touch.common.kconfig",
        "//private/google-modules/trusty:trusty.kconfig",
        "//private/google-modules/video/cnm:cnm.kconfig",
    ],
    kunit_modules = [
        # keep sorted
        "//private/google-modules/perf/core/apc_irm:apc_irm_test",
        "//private/google-modules/perf/core/gs_domain_idle:gs_domain_idle_kunit_test",
        "//private/google-modules/perf/infra/mbfs:mbfs_api_test",
        "//private/google-modules/perf/infra/mbfs:mbfs_kunit_test",
        "//private/google-modules/perf/thermal:thermal_tests",
        "//private/google-modules/power/mitigation:google_da918x_bcl_test",
        "//private/google-modules/power/mitigation:google_max77779_bcl_irq_test",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw-kunit",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gdmc_dhub_test_",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:towerci_test_",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:google-vdu-test",
    ],
    # TODO: b/447013182 - Remove unused modules.
    system_dlkm_modules = [
        # keep sorted
        gki_module("drivers/android/binder/rust_binder.ko"),
        gki_module("drivers/block/virtio_blk.ko"),
        gki_module("drivers/bluetooth/btbcm.ko"),
        gki_module("drivers/bluetooth/btqca.ko"),
        gki_module("drivers/bluetooth/btsdio.ko"),
        gki_module("drivers/bluetooth/hci_uart.ko"),
        gki_module("drivers/char/hw_random/cctrng.ko"),
        gki_module("drivers/char/virtio_console.ko"),
        gki_module("drivers/gnss/gnss.ko"),
        gki_module("drivers/misc/open-dice.ko"),
        gki_module("drivers/misc/vcpu_stall_detector.ko"),
        gki_module("drivers/net/macsec.ko"),
        gki_module("drivers/net/mii.ko"),
        gki_module("drivers/net/ppp/bsd_comp.ko"),
        gki_module("drivers/net/ppp/ppp_deflate.ko"),
        gki_module("drivers/net/ppp/ppp_generic.ko"),
        gki_module("drivers/net/ppp/ppp_mppe.ko"),
        gki_module("drivers/net/ppp/pppox.ko"),
        gki_module("drivers/net/slip/slhc.ko"),
        gki_module("drivers/net/usb/aqc111.ko"),
        gki_module("drivers/net/usb/asix.ko"),
        gki_module("drivers/net/usb/ax88179_178a.ko"),
        gki_module("drivers/net/usb/cdc_eem.ko"),
        gki_module("drivers/net/usb/cdc_ether.ko"),
        gki_module("drivers/net/usb/cdc_ncm.ko"),
        gki_module("drivers/net/usb/r8152.ko"),
        gki_module("drivers/net/usb/r8153_ecm.ko"),
        gki_module("drivers/net/usb/rtl8150.ko"),
        gki_module("drivers/net/usb/usbnet.ko"),
        gki_module("drivers/net/wwan/wwan.ko"),
        gki_module("drivers/power/sequencing/pwrseq-core.ko"),
        gki_module("drivers/pps/pps_core.ko"),
        gki_module("drivers/ptp/ptp.ko"),
        gki_module("drivers/usb/class/cdc-acm.ko"),
        gki_module("drivers/usb/serial/ftdi_sio.ko"),
        gki_module("drivers/usb/serial/usbserial.ko"),
        gki_module("drivers/virt/halla/exynos-hvm.ko"),
        gki_module("drivers/virtio/virtio_balloon.ko"),
        gki_module("drivers/virtio/virtio_pci.ko"),
        gki_module("drivers/virtio/virtio_pci_legacy_dev.ko"),
        gki_module("drivers/virtio/virtio_pci_modern_dev.ko"),
        gki_module("fs/netfs/netfs.ko"),
        gki_module("kernel/kheaders.ko"),
        gki_module("lib/crypto/libarc4.ko"),
        gki_module("mm/zsmalloc.ko"),
        gki_module("net/6lowpan/6lowpan.ko"),
        gki_module("net/6lowpan/nhc_dest.ko"),
        gki_module("net/6lowpan/nhc_fragment.ko"),
        gki_module("net/6lowpan/nhc_hop.ko"),
        gki_module("net/6lowpan/nhc_ipv6.ko"),
        gki_module("net/6lowpan/nhc_mobility.ko"),
        gki_module("net/6lowpan/nhc_routing.ko"),
        gki_module("net/6lowpan/nhc_udp.ko"),
        gki_module("net/8021q/8021q.ko"),
        gki_module("net/9p/9pnet.ko"),
        gki_module("net/9p/9pnet_fd.ko"),
        gki_module("net/bluetooth/bluetooth.ko"),
        gki_module("net/bluetooth/hidp/hidp.ko"),
        gki_module("net/bluetooth/rfcomm/rfcomm.ko"),
        gki_module("net/ieee802154/6lowpan/ieee802154_6lowpan.ko"),
        gki_module("net/ieee802154/ieee802154.ko"),
        gki_module("net/ieee802154/ieee802154_socket.ko"),
        gki_module("net/l2tp/l2tp_core.ko"),
        gki_module("net/l2tp/l2tp_ppp.ko"),
        gki_module("net/mac802154/mac802154.ko"),
        gki_module("net/nfc/nfc.ko"),
        gki_module("net/rfkill/rfkill.ko"),
        gki_module("net/tipc/tipc.ko"),
        gki_module("net/tipc/tipc_diag.ko"),
        gki_module("net/vmw_vsock/vmw_vsock_virtio_transport.ko"),
    ],
    system_dlkm_modules_blocklisted = [
        # keep sorted
        gki_module("drivers/usb/mon/usbmon.ko"),
    ],
    vendor_dlkm_modules = [
        # keep sorted
        intree_module("drivers/gpio/gpio-pca953x.ko"),
        intree_module("drivers/hwtracing/coresight/coresight.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-catu.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-dummy.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-etm4x.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-funnel.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-replicator.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-stm.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-tmc.ko"),
        intree_module("drivers/hwtracing/coresight/coresight-trbe.ko"),
        intree_module("drivers/hwtracing/stm/stm_core.ko"),
        intree_module("drivers/pci/pwrctrl/pci-pwrctrl-core.ko"),
        intree_module("drivers/perf/arm_spe_pmu.ko"),
        intree_module("drivers/spi/spi-loopback-test.ko"),
        intree_module("drivers/watchdog/softdog.ko"),
        "//private/google-modules/aoc:aoc_mbox_full_sdev",
        "//private/google-modules/aoc:aoc_tbn_service_dev",
        "//private/google-modules/aoc:aoc_unit_test_dev",
        "//private/google-modules/aoc:aoc_uwb_platform_drv",
        "//private/google-modules/aoc:aoc_uwb_service_dev",
        "//private/google-modules/aoc:mailbox-wc",
        "//private/google-modules/aoc/usb:aoc_usb_driver",
        "//private/google-modules/bms:google_ccd",
        "//private/google-modules/bms:google_dock",
        "//private/google-modules/bms:google_dual_batt_gauge",
        "//private/google-modules/bms:hl7132",
        "//private/google-modules/bms:ln8282_regulator",
        "//private/google-modules/bms:max1720x-battery",
        "//private/google-modules/bms:max20339",
        "//private/google-modules/bms:max77729-pmic",
        "//private/google-modules/bms:max77759-charger",
        "//private/google-modules/bms:max77779-charger-i2c",
        "//private/google-modules/bms:max77779-fg-i2c",
        "//private/google-modules/bms:max77779-fwupdate",
        "//private/google-modules/bms:max77779-sp-i2c",
        "//private/google-modules/bms:max77779-vimon-i2c",
        "//private/google-modules/bms:max77779_i2cm_i2c",
        "//private/google-modules/bms:max77779_pmic_i2c",
        "//private/google-modules/bms:p9221",
        "//private/google-modules/bms:pca9468",
        "//private/google-modules/bms:rt9471_charger",
        "//private/google-modules/display/vsi-g2d:drm-g2d",
        "//private/google-modules/dpa:google-dpa.pixel",
        "//private/google-modules/edgetpu/santafe/drivers/edgetpu:edgetpu.santafe",
        "//private/google-modules/gxp/malibu:gxp",
        "//private/google-modules/iif",
        "//private/google-modules/image/cnm:jpu",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/perf:arm_smmuv3_pmu",
        "//private/google-modules/lwis:lwis.erie",
        "//private/google-modules/misc/h2omg",
        "//private/google-modules/perf/core/lat_govs:cmefreq_gov",
        "//private/google-modules/perf/thermal",
        "//private/google-modules/powervr",
        "//private/google-modules/soc/gs/drivers/mfd:slg51002-core",
        "//private/google-modules/soc/gs/drivers/pinctrl:pinctrl-slg51002",
        "//private/google-modules/soc/gs/drivers/regulator:rt6160-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sgm38122-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sgm38125-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:slg51002-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sy70206-regulator",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/cgroup:vh_cgroup",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/metrics:pixel_metrics",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/thermal:vh_thermal",
        "//private/google-modules/soc/rdo/cpu-lpm-stats:google_cpu_lpm_stats",
        "//private/google-modules/soc/rdo/drivers/i2c/busses/test:i2c-test",
        "//private/google-modules/soc/rdo/drivers/iis",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-extended-sysfs",
        "//private/google-modules/soc/rdo/drivers/perf:google_gem",
        "//private/google-modules/soc/rdo/drivers/power:genpd-test-consumer",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gdmc_dhub",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd-cpu:goog-cpu-idle-info",
        "//private/google-modules/soc/rdo/interconnect:google-icc-helper-mock-client",
        "//private/google-modules/soc/rdo/interconnect:google-irm-stub",
        "//private/google-modules/soc/rdo/pci:google-pcie-v2",
        "//private/google-modules/soc/rdo/pci:phy-google-pcie",
        "//private/google-modules/soc/rdo/trace:generic_source",
        "//private/google-modules/soc/rdo/usb:dwc3-google-aux",
        "//private/google-modules/touch/common:goog_touch_interface",
        "//private/google-modules/touch/common:heatmap",
        "//private/google-modules/touch/common:touch_bus_negotiator",
        "//private/google-modules/touch/common:touch_offload",
        "//private/google-modules/video/cnm:vpu",
    ],
    vendor_dlkm_modules_blocklisted = [
        # keep sorted
        "//private/google-modules/display/common/panel_tests:gs-panel-common-test",
        "//private/google-modules/misc/sscoredump:sscoredump_sample_test",
        "//private/google-modules/misc/sscoredump:sscoredump_test",
        "//private/google-modules/soc/gs/drivers/iommu:iommu_map_benchmark",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-google-test",
        "//private/google-modules/soc/rdo/drivers/perf:google_gem_test_module",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface-test",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-ebu-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-gdmc-iface-test",
        "//private/google-modules/soc/rdo/ebu:ebu-google",
        "//private/google-modules/soc/rdo/gadget/dta:google_dta",
    ],
    vendor_ramdisk_modules = [
        # keep sorted
        gki_module("mm/zsmalloc.ko"),
        intree_module("drivers/gpu/drm/display/drm_display_helper.ko"),
        intree_module("drivers/i2c/i2c-dev.ko"),
        intree_module("drivers/misc/eeprom/at24.ko"),
        intree_module("drivers/nvmem/nvmem-rmem.ko"),
        intree_module("drivers/perf/arm-ni.ko"),
        intree_module("drivers/perf/arm_dsu_pmu.ko"),
        intree_module("drivers/scsi/sg.ko"),
        intree_module("drivers/spi/spi-dw.ko"),
        "//private/google-modules/amplifiers/audiometrics",
        "//private/google-modules/aoc:aoc_channel_dev",
        "//private/google-modules/aoc:aoc_char_dev",
        "//private/google-modules/aoc:aoc_control_dev",
        "//private/google-modules/aoc:aoc_core",
        "//private/google-modules/aoc/alsa:aoc_alsa_dev",
        "//private/google-modules/aoc/alsa:aoc_alsa_dev_util",
        "//private/google-modules/aoc_ipc",
        "//private/google-modules/bms:google-battery",
        "//private/google-modules/bms:google-bms",
        "//private/google-modules/bms:google-charger",
        "//private/google-modules/bms:google-cpm",
        "//private/google-modules/bms:google-wlc",
        "//private/google-modules/bms:ln8411",
        "//private/google-modules/bms:max77779-charger",
        "//private/google-modules/bms:max77779-charger-spmi",
        "//private/google-modules/bms:max77779-fg",
        "//private/google-modules/bms:max77779-fg-spmi",
        "//private/google-modules/bms:max77779-sp",
        "//private/google-modules/bms:max77779-sp-spmi",
        "//private/google-modules/bms:max77779-usecase",
        "//private/google-modules/bms:max77779-vimon",
        "//private/google-modules/bms:max77779-vimon-spmi",
        "//private/google-modules/bms:max77779_i2cm",
        "//private/google-modules/bms:max77779_i2cm_spmi",
        "//private/google-modules/bms:max77779_pmic",
        "//private/google-modules/bms:max77779_pmic_irq",
        "//private/google-modules/bms:max77779_pmic_pinctrl",
        "//private/google-modules/bms:max77779_pmic_sgpio",
        "//private/google-modules/bms:max77779_pmic_spmi",
        "//private/google-modules/bms:max77779_vdroop",
        "//private/google-modules/bms/misc:gvotable",
        "//private/google-modules/bms/misc:logbuffer",
        "//private/google-modules/bms/pe26100:pe26100-buck-charger",
        "//private/google-modules/bms/pe26100:pe26100-cp-charger",
        "//private/google-modules/bms/pe26100:pe26100-usecase",
        "//private/google-modules/bms/pe26100:pe26100_driver",
        "//private/google-modules/display/common/gs_drm:gs-drm-connector",
        "//private/google-modules/display/common/gs_panel:gs-panel",
        "//private/google-modules/display/common/panels:panel-gs-simple",
        "//private/google-modules/display/interfaces/synopsys/dwc_dptx",
        "//private/google-modules/display/vsi-drm/bridge/synopsys/dsi2host:mipi-dsi2h",
        "//private/google-modules/display/vsi-drm/phy/synopsys:mipi-cdphy",
        "//private/google-modules/display/vsi-drm/verisilicon:vs_drm",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:acfw-debug",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:arm/arm-smmu-v3/arm_smmu_v3",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:arm/arm-smmu-v3/arm_smmu_v3_kvm",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:io-pgtable-pixel",
        "//private/google-modules/perf/core/apc_irm:apc_irm_drv",
        "//private/google-modules/perf/core/google_pm_qos",
        "//private/google-modules/perf/core/google_pm_qos:google_vote_manager",
        "//private/google-modules/perf/core/gs_domain_idle",
        "//private/google-modules/perf/core/gs_perf_domain:perf_domain",
        "//private/google-modules/perf/core/gs_perf_mon",
        "//private/google-modules/perf/core/irm_devfreq:google_irm_devfreq",
        "//private/google-modules/perf/core/lat_govs:gs_governor_dsulat",
        "//private/google-modules/perf/core/lat_govs:gs_governor_memlat",
        "//private/google-modules/perf/core/lat_govs:gs_governor_utils",
        "//private/google-modules/perf/infra/mbfs",
        "//private/google-modules/perf/infra/mbfs:mbfs_cpm_backend",
        "//private/google-modules/perf/thermal:google_thermal_cpm_mbox",
        "//private/google-modules/power/mitigation:google_bcl",
        "//private/google-modules/power/mitigation:max77779_bcl_irq",
        "//private/google-modules/power/reset:pixel-reboot",
        "//private/google-modules/radio/common/metrics_collection",
        "//private/google-modules/radio/common/radio-bridge",
        "//private/google-modules/soc/gs/drivers/block/zram:zcomp_cpu",
        "//private/google-modules/soc/gs/drivers/block/zram:zram_gs",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:deferred-free-helper",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:page_pool",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps/samsung:samsung_dma_heap",
        "//private/google-modules/soc/gs/drivers/input:keycombo",
        "//private/google-modules/soc/gs/drivers/input:keydebug",
        "//private/google-modules/soc/gs/drivers/input:power_keydebug",
        "//private/google-modules/soc/gs/drivers/iommu:dma-iommu-vendor-hooks",
        "//private/google-modules/soc/gs/drivers/iommu:samsung-secure-iova",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump",
        "//private/google-modules/soc/gs/drivers/power/reset:debug-reboot",
        "//private/google-modules/soc/gs/drivers/regulator:s2dos07x02-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:tps628600-regulator",
        "//private/google-modules/soc/gs/drivers/soc/google:hardlockup-watchdog",
        "//private/google-modules/soc/gs/drivers/soc/google:kernel-top",
        "//private/google-modules/soc/gs/drivers/soc/google:perf_trace_counters",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:pixel-debug-test",
        "//private/google-modules/soc/gs/drivers/soc/google/gcma",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa_gsc",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa_ko",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:tzprot",
        "//private/google-modules/soc/gs/drivers/soc/google/pa_kill",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat:pixel_stat_sysfs",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat/mm:pixel_stat_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_trim",
        "//private/google-modules/soc/gs/drivers/soc/google/smra",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:systrace",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/fs:vh_fs",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/mm:vh_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/pixel_em",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:sched_tp",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_preemptirq_long",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_sched",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:bc_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:google_tcpci_shim",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_helper",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77779_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max777x9_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max777x9_spmi",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usb_psy",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usbc_cooling_dev",
        "//private/google-modules/soc/rdo/aoss-ssr-notifier:aoss_ssr_notifier",
        "//private/google-modules/soc/rdo/ap-pmic:da9188-core",
        "//private/google-modules/soc/rdo/ap-pmic/gpio:da9188-gpio",
        "//private/google-modules/soc/rdo/ap-pmic/regulator:da9188-regulator",
        "//private/google-modules/soc/rdo/ap-pmic/rtc:da9188-rtc",
        "//private/google-modules/soc/rdo/ap-pmic/vgpio:da9188-vgpio",
        "//private/google-modules/soc/rdo/cap-sysfs:google_cap_sysfs",
        "//private/google-modules/soc/rdo/clocksource/google/sst:google_sst",
        "//private/google-modules/soc/rdo/drivers/clk/google:clk-cpm",
        "//private/google-modules/soc/rdo/drivers/dma:google-gpdma",
        "//private/google-modules/soc/rdo/drivers/dma:pl330",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:i2c-designware-core",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:i2c-designware-platform",
        "//private/google-modules/soc/rdo/drivers/i3c/master:dw-i3c-master",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:dw-i3c-master-thi",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:dw-i3c-xfer-host-ap",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-google",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-lib",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-google-cpm",
        "//private/google-modules/soc/rdo/drivers/mailbox:goog-mba-ctrl",
        "//private/google-modules/soc/rdo/drivers/pinctrl/google:pinctrl",
        "//private/google-modules/soc/rdo/drivers/rst/google:rst-cpm",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-aoss-wdt-handler",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-chip-info",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-aggr",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-doorbell-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-gdmc-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gtc",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_timestamp_sync",
        "//private/google-modules/soc/rdo/drivers/soc/google:gs-debug-test",
        "//private/google-modules/soc/rdo/drivers/soc/google:pixel-debug-kinfo",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd:gcdd",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:google-ehld-coreinstr",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:google-skip-s2m-voter",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:towerci",
        "//private/google-modules/soc/rdo/drivers/soc/google/dvfs-helper:dvfs_helper",
        "//private/google-modules/soc/rdo/drivers/soc/google/dvfs-target-frontend:dvfs_target_frontend",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwmt",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp_cpm",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp_google_gdmc",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp_lib",
        "//private/google-modules/soc/rdo/drivers/soc/google/lpm-pm-domains:lpm_pm_domains",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:gvdu",
        "//private/google-modules/soc/rdo/drivers/spi:spi-dw-mmio",
        "//private/google-modules/soc/rdo/drivers/spmi:regmap-goog-spmi",
        "//private/google-modules/soc/rdo/drivers/spmi:spmi-smartdv",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250_base",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250_dw",
        "//private/google-modules/soc/rdo/drivers/tty/serial/modem-uart",
        "//private/google-modules/soc/rdo/drivers/ufs",
        "//private/google-modules/soc/rdo/hardlockup-debug",
        "//private/google-modules/soc/rdo/interconnect:google_icc",
        "//private/google-modules/soc/rdo/interconnect:google_irm",
        "//private/google-modules/soc/rdo/lpcm/gpu:gpu_pf_state",
        "//private/google-modules/soc/rdo/odpm:google_odpm",
        "//private/google-modules/soc/rdo/phy:google-eusb2-repeater",
        "//private/google-modules/soc/rdo/phy:google-usb-phy",
        "//private/google-modules/soc/rdo/power-controller:power_controller",
        "//private/google-modules/soc/rdo/powerdashboard:google_powerdashboard",
        "//private/google-modules/soc/rdo/usb:dwc3-google",
        "//private/google-modules/soc/rdo/watchdog:google_wdt",
        "//private/google-modules/trusty:trusty-core",
        "//private/google-modules/trusty:trusty-ipc",
        "//private/google-modules/trusty:trusty-log",
        "//private/google-modules/trusty:trusty-test",
        "//private/google-modules/trusty:trusty-virtio",
        "//private/google-modules/trusty:trusty-wakelock",
    ],
)

device_build(
    name = "malibu",
    base_device = "malibu_base",
    build_dtb = True,
    build_dtbo = True,
    build_system_dlkm = True,
    build_vendor_dlkm = True,
    build_vendor_kernel_boot = True,
    dtb_outs = MALIBU_DTBS,
    dts_makefile = "dts/Makefile",
    dts_srcs = glob(["dts/**"]) + [
        "//private/google-modules/soc/gs:gs.dt-bindings",
        "//private/google-modules/soc/rdo:rdo.dt-bindings",
    ],
    fs_type = "erofs",
    module_outs = MALIBU_MODULE_OUTS,
)
