import("//build_overrides/noa.gni")
import("$dir_noa_packages/noa_common/sim/ncp/wlan_fw/wlan_service.gni")

wlan_source_set("headers") {
  public = [ "$dir_wlan_fw/modules/wlan_ring_manager/wlan_ring_manager.h" ]
  public_deps = [
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/modules/wlan_ring",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
}

wlan_source_set("wlan_ring_manager") {
  public_deps = [ ":headers" ]
  deps = [
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [ "$dir_wlan_fw/modules/wlan_ring_manager/wlan_ring_manager.cc" ]
}

wlan_test_group("tests") {
  tests = []
}
