# SPDX-License-Identifier: GPL-2.0-or-later

"""
This file was automatically generated from config_kernel.mk.
"""

CONFIG_KERNEL_VARS = {
    "BUILD": "debug",
    "COMPRESS_DEBUG_SECTIONS": "1",
    "DISABLE_COMPILE_TIME_BVNC": "1",
    "HOST_32BIT_ARCH": "host_i386",
    "HOST_ALL_ARCH": "host_x86_64 host_i386",
    "HOST_FORCE_32BIT": "-m32",
    "HOST_PRIMARY_ARCH": "host_x86_64",
    "METAG_VERSION_NEEDED": "2.8.1.0.3",
    "OPTIM": "-O2",
    "PDVFS_COM": "PDVFS_COM_HOST",
    "PDVFS_COM_AP": "2",
    "PDVFS_COM_HOST": "1",
    "PDVFS_COM_IMG_CLKDIV": "4",
    "PDVFS_COM_PIXEL_LPCM": "5",
    "PDVFS_COM_PMC": "3",
    "PVRHMMU_MODNAME": "pvrhmmu",
    "PVRSRV_ANDROID_TRACE_GPU_FREQ": "1",
    "PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD": "1",
    "PVRSRV_DIR": "services",
    "PVRSRV_ENABLE_HTB": "1",
    "PVRSRV_FORCE_HWPERF_TO_SCHED_CLK": "1",
    "PVRSRV_MODNAME": "pvrsrvkm",
    "PVR_ARCH": "volcanic",
    "PVR_BUILD_DIR": "pixel_android",
    "PVR_BUILD_TYPE": "debug",
    "PVR_GPIO_MODE": "PVR_GPIO_MODE_GENERAL",
    "PVR_GPIO_MODE_GENERAL": "1",
    "PVR_GPIO_MODE_POWMON_PIN": "2",
    "PVR_HANDLE_BACKEND": "idr",
    "PVR_LOADER": "",
    "PVR_SYSTEM": "",
    "RGX_BNC": "70.V.2448.1041",
    "RGX_FW_HEAP_OSID_ASSIGNMENT": "RGX_FW_HEAP_USES_FIRMWARE_OSID",
    "RGX_NUM_DRIVERS_SUPPORTED": "1",
    "RGX_TIMECORR_CLOCK": "sched",
    "RISCV_VERSION_NEEDED": "1.7.1",
    "SORT_BRIDGE_STRUCTS": "1",
    "SUPPORT_ANDROID_PLATFORM": "1",
    "SUPPORT_DI_BRG_IMPL": "1",
    "SUPPORT_DMABUF_BRIDGE": "1",
    "SUPPORT_DMA_FENCE": "1",
    "SUPPORT_FW_CORE_CLK_RATE_CHANGE_NOTIFY": "1",
    "SUPPORT_NATIVE_FENCE_SYNC": "1",
    "SUPPORT_PHYSMEM_TEST": "1",
    "SUPPORT_POWMON_COMPONENT": "1",
    "SUPPORT_RGX": "1",
    "SUPPORT_RGXKICKSYNC_BRIDGE": "1",
    "SUPPORT_WRAP_EXTMEM": "1",
    "TARGET_ALL_ARCH": "target_aarch64",
    "TARGET_FORCE_32BIT": "",
    "TARGET_PRIMARY_ARCH": "target_aarch64",
    "TARGET_SECONDARY_ARCH": "",
    "USE_PVRSYNC_DEVNODE": "1",
    "VMM_TYPE": "stub",
}
