// SPDX-License-Identifier: BSD-3-Clause-Clear
/*
 * Copyright (c) 2022, MediaTek Inc.
 */

#include "mtk_cldma.h"
#include "mtk_port.h"
#include "mtk_trans_ctrl.h"
#ifdef CONFIG_UT_PCIE_CTRL_CFG
#include "ut_ctrl_cfg_m9xx.h"
#endif

#define TRB_SRV_NUM	(1)

static const int mtk_srv_cfg_m9xx[NR_CLDMA][HW_QUE_NUM] = {
	{0},
	{0},
};

/* the number of RX GPDs should be at last two */
static const struct queue_info mtk_queue_info_m9xx[] = {
	{FBOOT_INDEX_TX, FBOOT_INDEX_RX, CLDMA0, TXQ(1), RXQ(1),
	 Q_MTU_7K, Q_MTU_63K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_7K, Q_FRAG_63K, 0},
	{FW_INDEX_TX, FW_INDEX_RX, CLDMA0, TXQ(0), RXQ(0),
	 Q_MTU_32K, Q_MTU_32K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_32K, Q_FRAG_32K, 0},

	{BROM_INDEX_TX, BROM_INDEX_RX, CLDMA0, TXQ(0), RXQ(0),
	 Q_MTU_2K, Q_MTU_2K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_2K, Q_FRAG_2K, 0},
	{DUMP_INDEX_TX, DUMP_INDEX_RX, CLDMA0, TXQ(1), RXQ(1),
	 Q_MTU_7K, Q_MTU_63K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_7K, Q_FRAG_63K, 0},

	{CCCI_UART2_TX, CCCI_UART2_RX, CLDMA1, TXQ(5), RXQ(5),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_MIPC_TX, CCCI_MIPC_RX, CLDMA1, TXQ(2), RXQ(2),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_MIPC7_TX, CCCI_MIPC7_RX, CLDMA1, TXQ(2), RXQ(2),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_MD_LOG_TX, CCCI_MD_LOG_RX, CLDMA1, TXQ(7), RXQ(7),
	 Q_MTU_3_5K, Q_MTU_63K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_63K, 1},
	{CCCI_LB_IT_TX, CCCI_LB_IT_RX, CLDMA1, TXQ(1), RXQ(1),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_MBIM_TX, CCCI_MBIM_RX, CLDMA1, TXQ(2), RXQ(2),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_UART1_TX, CCCI_UART1_RX, CLDMA1, TXQ(1), RXQ(1),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_MD_RFS_TX, CCCI_MD_RFS_RX, CLDMA1, TXQ(4), RXQ(4),
	 Q_MTU_63K, Q_MTU_63K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_63K, Q_FRAG_63K, 0},
	{CCCI_MD_LOG_NTFY_TX, CCCI_MD_LOG_NTFY_RX, CLDMA1, TXQ(5), RXQ(5),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},

	{CCCI_SAP_LBIT_TX, CCCI_SAP_LBIT_RX, CLDMA0, TXQ(4), RXQ(4),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GNSS_TX, CCCI_SAP_GNSS_RX, CLDMA0, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_META_TX, CCCI_SAP_META_RX, CLDMA0, TXQ(1), RXQ(1),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_LOG_TX, CCCI_SAP_LOG_RX, CLDMA0, TXQ(2), RXQ(2),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 1},
	{CCCI_SAP_ADB_TX, CCCI_SAP_ADB_RX, CLDMA0, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_MINIDUMP_NOTIFY_TX, CCCI_SAP_MINIDUMP_NOTIFY_RX, CLDMA0, TXQ(5), RXQ(5),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},

	{CCCI_DSS0_TX, CCCI_DSS0_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS1_TX, CCCI_DSS1_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS2_TX, CCCI_DSS2_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS3_TX, CCCI_DSS3_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS4_TX, CCCI_DSS4_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS5_TX, CCCI_DSS5_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS6_TX, CCCI_DSS6_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_DSS7_TX, CCCI_DSS7_RX, CLDMA1, TXQ(3), RXQ(3),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},

	{CCCI_CONTROL_TX, CCCI_CONTROL_RX, CLDMA1, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_CONTROL_TX, CCCI_SAP_CONTROL_RX, CLDMA0, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI0_TX, CCCI_SAP_GCCI0_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI1_TX, CCCI_SAP_GCCI1_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI2_TX, CCCI_SAP_GCCI2_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI3_TX, CCCI_SAP_GCCI3_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI4_TX, CCCI_SAP_GCCI4_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_GCCI5_TX, CCCI_SAP_GCCI5_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_TIMESYNC_TX, CCCI_SAP_TIMESYNC_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_AGPS_TX, CCCI_SAP_AGPS_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_RFS_TX, CCCI_SAP_RFS_RX, CLDMA0, TXQ(7), RXQ(7),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_LPM_TX, CCCI_SAP_LPM_RX, CLDMA0, TXQ(5), RXQ(5),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_ATA_TX, CCCI_SAP_ATA_RX, CLDMA0, TXQ(6), RXQ(6),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},
	{CCCI_SAP_AUD_CFG_TX, CCCI_SAP_AUD_CFG_RX, CLDMA0, TXQ(4), RXQ(4),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 0},

	{CCCI_GNSS_CONTROL_TX, CCCI_GNSS_CONTROL_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_0_TX, CCCI_GC4_0_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_1_TX, CCCI_GC4_1_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_2_TX, CCCI_GC4_2_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_3_TX, CCCI_GC4_3_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_4_TX, CCCI_GC4_4_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
	{CCCI_GC4_5_TX, CCCI_GC4_5_RX, CLDMA4, TXQ(0), RXQ(0),
	 Q_MTU_3_5K, Q_MTU_3_5K, TX_GPD_NUM, RX_GPD_NUM, Q_FRAG_3_5K, Q_FRAG_3_5K, 2},
};

static const struct mtk_port_cfg port_cfg_m9xx[] = {
	{FBOOT_INDEX_TX, FBOOT_INDEX_RX, PORT_TYPE_CHAR, "FBootDownload",
		PORT_F_RAW_DATA | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{FW_INDEX_TX, FW_INDEX_RX, PORT_TYPE_CHAR, "FWDownload",
		PORT_F_RAW_DATA | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{BROM_INDEX_TX, BROM_INDEX_RX, PORT_TYPE_CHAR, "BromDownload",
		PORT_F_RAW_DATA | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{DUMP_INDEX_TX, DUMP_INDEX_RX, PORT_TYPE_CHAR, "CoreDump",
		PORT_F_RAW_DATA | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{CCCI_UART2_TX, CCCI_UART2_RX, PORT_TYPE_WWAN, "AT",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MIPC_TX, CCCI_MIPC_RX, PORT_TYPE_CHAR, "MIPC0",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MIPC7_TX, CCCI_MIPC7_RX, PORT_TYPE_CHAR, "MIPC7",
		PORT_F_ALLOW_DROP | PORT_F_DUMP | PORT_F_MDEE_SPT,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MD_LOG_TX, CCCI_MD_LOG_RX, PORT_TYPE_RELAYFS, "MDLog",
		PORT_F_DUMP | PORT_F_MDEE_SPT, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_LB_IT_TX, CCCI_LB_IT_RX, PORT_TYPE_CHAR, "MDLB",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MBIM_TX, CCCI_MBIM_RX, PORT_TYPE_WWAN, "MBIM",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_UART1_TX, CCCI_UART1_RX, PORT_TYPE_CHAR, "MDMETA",
		PORT_F_DUMP | PORT_F_MDEE_SPT, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MD_RFS_TX, CCCI_MD_RFS_RX, PORT_TYPE_CHAR, "MDRFS",
		PORT_F_RAW_DATA | PORT_F_FORCE_NO_SPILT_PACKET | PORT_F_DUMP | PORT_F_MDEE_SPT,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_MD_LOG_NTFY_TX, CCCI_MD_LOG_NTFY_RX, PORT_TYPE_CHAR, "MDLogNtfy",
		PORT_F_ALLOW_DROP | PORT_F_DUMP | PORT_F_MDEE_SPT,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{CCCI_SAP_LBIT_TX, CCCI_SAP_LBIT_RX, PORT_TYPE_CHAR, "SAPLB",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GNSS_TX, CCCI_SAP_GNSS_RX, PORT_TYPE_WWAN, "GNSS",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_META_TX, CCCI_SAP_META_RX, PORT_TYPE_CHAR, "SAPMETA",
		PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_LOG_TX, CCCI_SAP_LOG_RX, PORT_TYPE_CHAR, "SAPLog",
		PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_ADB_TX, CCCI_SAP_ADB_RX, PORT_TYPE_CHAR, "ADB",
		PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_MINIDUMP_NOTIFY_TX, CCCI_SAP_MINIDUMP_NOTIFY_RX, PORT_TYPE_INTERNAL,
		"minidump_notify", PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{CCCI_DSS0_TX, CCCI_DSS0_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(0),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS1_TX, CCCI_DSS1_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(1),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS2_TX, CCCI_DSS2_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(2),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS3_TX, CCCI_DSS3_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(3),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS4_TX, CCCI_DSS4_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(4),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS5_TX, CCCI_DSS5_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(5),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS6_TX, CCCI_DSS6_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(6),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_DSS7_TX, CCCI_DSS7_RX, PORT_TYPE_CHAR, MTK_DSS_PORT(7),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{CCCI_CONTROL_TX, CCCI_CONTROL_RX, PORT_TYPE_INTERNAL, "MDCTRL",
		PORT_F_ALLOW_DROP | PORT_F_DUMP | PORT_F_FORCE_SEND | PORT_F_MDEE_SPT,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_CONTROL_TX, CCCI_SAP_CONTROL_RX, PORT_TYPE_INTERNAL, "SAPCTRL",
		PORT_F_ALLOW_DROP | PORT_F_DUMP | PORT_F_FORCE_SEND,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},

	{CCCI_SAP_GCCI0_TX, CCCI_SAP_GCCI0_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(0),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GCCI1_TX, CCCI_SAP_GCCI1_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(1),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GCCI2_TX, CCCI_SAP_GCCI2_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(2),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GCCI3_TX, CCCI_SAP_GCCI3_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(3),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GCCI4_TX, CCCI_SAP_GCCI4_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(4),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_GCCI5_TX, CCCI_SAP_GCCI5_RX, PORT_TYPE_CHAR, MTK_GCCI_PORT(5),
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_TIMESYNC_TX, CCCI_SAP_TIMESYNC_RX, PORT_TYPE_PROPRIETARY,
		"TimeSync", PORT_F_ALLOW_DROP | PORT_F_DUMP,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_AGPS_TX, CCCI_SAP_AGPS_RX, PORT_TYPE_CHAR, "AGNSS",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_RFS_TX, CCCI_SAP_RFS_RX, PORT_TYPE_CHAR, "SAPRFS",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_LPM_TX, CCCI_SAP_LPM_RX, PORT_TYPE_CHAR, "LPM",
		PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_ATA_TX, CCCI_SAP_ATA_RX, PORT_TYPE_CHAR, "ATA",
		PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_GNSS_CONTROL_TX, CCCI_GNSS_CONTROL_RX, PORT_TYPE_INTERNAL, "GNSSCTRL",
		PORT_F_ALLOW_DROP | PORT_F_DUMP | PORT_F_FORCE_SEND,
		MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
	{CCCI_SAP_AUD_CFG_TX, CCCI_SAP_AUD_CFG_RX, PORT_TYPE_CHAR, "Speech",
		PORT_F_ALLOW_DROP | PORT_F_DUMP, MTK_DFLT_TX_DUMP_CNT, MTK_DFLT_RX_DUMP_CNT},
};

static int mtk_ctrl_get_port_cnt_m9xx(void)
{
	return ARRAY_SIZE(port_cfg_m9xx);
}

static struct mtk_port_layer_cfg port_layer_cfg_m9xx = {
	.port_cfg = (struct mtk_port_cfg *)port_cfg_m9xx,
	.get_port_cnt = mtk_ctrl_get_port_cnt_m9xx,
};

static unsigned int mtk_fsm_get_hs_done_flags_m9xx(struct mtk_md_dev *mdev, u32 dev_state)
{
	u32 dev_cfg = dev_state >> DEVICE_CFG_SHIFT & DEVICE_CFG_REGION_MASK;
	u32 firmware_cfg = dev_state >> FIRMWARE_CFG_SHIFT  & 0x1;
	unsigned int hs_done_flag;

	if (dev_cfg == DEV_CFG_MD_ONLY)
		hs_done_flag = FSM_F_MD_HS_START | FSM_F_MD_HS2_DONE;
	else
		hs_done_flag = FSM_HS_START_MASK | FSM_HS2_DONE_MASK;

	if (firmware_cfg)
		hs_done_flag |= FSM_F_MD_HS4_DONE;

	return hs_done_flag;
}

static struct mtk_fsm_cfg mtk_fsm_cfg_m9xx = {
	.sync_mode = BOOT_SYNC_MODE_INTERRUPT,
	.get_hs_done_flags = mtk_fsm_get_hs_done_flags_m9xx,
};

static struct mtk_ctrl_cfg mtk_ctrl_cfg_m9xx = {
	.port_layer_cfg = &port_layer_cfg_m9xx,
	.fsm_cfg = &mtk_fsm_cfg_m9xx,
};

static struct mtk_ctrl_drv_cfg mtk_ctrl_drv_cfg_m9xx = {
	.tx_done_work = mtk_cldma_tx_done_work,
	.rx_done_work = mtk_cldma_rx_done_work_optimize,
};

struct mtk_ctrl_info mtk_ctrl_info_m9xx = {
	.ctrl_cfg = &mtk_ctrl_cfg_m9xx,
	.srv_cfg = (int **)mtk_srv_cfg_m9xx,
	.drv_cfg = &mtk_ctrl_drv_cfg_m9xx,
	.queue_info = (struct queue_info *)mtk_queue_info_m9xx,
	.queue_info_num = ARRAY_SIZE(mtk_queue_info_m9xx),
	.trb_srv_num = TRB_SRV_NUM,
};
