/* SPDX-License-Identifier: BSD-3-Clause-Clear */
#ifndef __MTK_DPMAIF_DRV_M9XX_H__
#define __MTK_DPMAIF_DRV_M9XX_H__

#include "mtk_dpmaif_reg.h"

#define DPMAIF_DEV_PD_BASE		0x1022D000
#define DPMAIF_DEV_PD2_BASE		0x10260000
#define DPMAIF_DEV_AO_BASE		0x10011000

#define NRL2_DPMAIF_AO_UL_CH0_STA	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0xE0)

/* DPMAIF AO register */
#define DPMAIF_AP_RGU_ASSERT		0x10001120
#define DPMAIF_AP_RGU_DEASSERT		0x10001124
#define DPMAIF_AP_RST_BIT		BIT(4)
#define DPMAIF_AP_AO_RGU_ASSERT		0x10001140
#define DPMAIF_AP_AO_RGU_DEASSERT	0x10001144
#define DPMAIF_AP_AO_RST_BIT		BIT(3)
#define DPMAIF_AP_INFRA_CG_CLR          0x100010E0
#define DPMAIF_AP_INFRA_CG_SET          0x100010E4
#define DPMAIF_AP_INFRA_CG_BIT          BIT(15)
#define DPMAIF_AP_INFRA_GLITCH_PORT     0x10001208
#define DPMAIF_AP_GLITCH_PROT_BIT       BIT(15)
#define DPMAIF_AP_PD_SRAM_EN_BIT	BIT(31)

#define NRL2_DPMAIF_AP_MISC_SRAM_INIT_SET0		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0xC0)
#define NRL2_DPMAIF_AP_MISC_SRAM_INIT_SET1		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0xC4)
#define DPMAIF_PD_AP_UL_L2TIMR0_NEXT			(BASE_ADDR_MMW_DPMAIF_PD_MISC2_CFG + 0x60)
#define DPMAIF_PD_AP_UL_L2TICR0_NEXT			(BASE_ADDR_MMW_DPMAIF_PD_MISC2_CFG + 0x5C)
#define DPMAIF_PD_AP_UL_L2TISR0_NEXT			(BASE_ADDR_MMW_DPMAIF_PD_MISC2_CFG + 0x58)

#define NRL2_DPMAIF_PD_DL_LROPIT_TIMEOUT5       0x40

#define DPMAIF_HPC_NUM_EXT		8
#define DPMAIF_HPC_NUM_M9XX		(DPMAIF_HPC_NUM_DF + DPMAIF_HPC_NUM_EXT)
#endif
