/* SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_DPMAIF_REG_H__
#define __MTK_DPMAIF_REG_H__

/* 2ms -> 2 * 1000 / 10 = 200 */
#define POLL_MAX_TIMES		200
#define POLL_INTERVAL_US	10
#define REWRITE_TIMES		20

/* dpmaif pd domain regisers */
#define DPMAIF_AO_BASE			0
#define BASE_NADDR_NRL2_DPMAIF_AO_UL		((unsigned long)(DPMAIF_AO_BASE))
#define BASE_NADDR_NRL2_DPMAIF_AO_DL		((unsigned long)(DPMAIF_AO_BASE + 0x400))

/* dpmaif uplink */
#define NRL2_DPMAIF_AO_UL_INIT_SET		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x0)
#define NRL2_DPMAIF_AO_UL_CHNL_ARB0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x1C)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x80)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMCR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x84)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMSR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x88)
#define NRL2_DPMAIF_AO_UL_AP_L1TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x8C)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x90)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMCR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x94)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMSR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x98)
#define NRL2_DPMAIF_AO_UL_AP_DL_UL_IP_BUSY_MASK	(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x9C)

/* dpmaif downlink. */
#define NRL2_DPMAIF_AO_DL_INIT_SET		(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x0)
#define NRL2_DPMAIF_AO_DL_LROPIT_INIT_CON5	(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x28)
#define NRL2_DPMAIF_AO_DL_LROPIT_TRIG_THRES	(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x34)
#define NRL2_DPMAIF_AO_DL_IRQ_MASK		(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0xC)

/* dpmaif uplink config. */
#define DPMAIF_PD_UL_CHNL_ARB0		NRL2_DPMAIF_AO_UL_CHNL_ARB0

#define DPMAIF_PD_AP_UL_L2TIMR0		NRL2_DPMAIF_AO_UL_AP_L2TIMR0
#define DPMAIF_PD_AP_UL_L2TICR0		NRL2_DPMAIF_AO_UL_AP_L2TIMCR0
#define DPMAIF_PD_AP_UL_L2TISR0		NRL2_DPMAIF_AO_UL_AP_L2TIMSR0

#define DPMAIF_PD_AP_DL_L2TIMR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMR0
#define DPMAIF_PD_AP_DL_L2TICR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMCR0
#define DPMAIF_PD_AP_DL_L2TISR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMSR0

#define DPMAIF_PD_AP_DLUL_IP_BUSY_MASK	NRL2_DPMAIF_AO_UL_AP_DL_UL_IP_BUSY_MASK

/* dpmaif pd domain regisers */
#define DPMAIF_PD_BASE			0
#define BASE_NADDR_NRL2_DPMAIF_UL	((unsigned long)(DPMAIF_PD_BASE))
#define BASE_NADDR_NRL2_DPMAIF_DL	((unsigned long)(DPMAIF_PD_BASE + 0x100))
#define BASE_NADDR_NRL2_DPMAIF_AP_MISC	((unsigned long)(DPMAIF_PD_BASE + 0x400))
#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL	((unsigned long)(DPMAIF_PD_BASE + 0xD00))
#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL	((unsigned long)(DPMAIF_PD_BASE + 0xC00))
#define BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX	((unsigned long)(DPMAIF_PD_BASE + 0x900))
#define BASE_NADDR_NRL2_DPMAIF_MMW_HPC		((unsigned long)(DPMAIF_PD_BASE + 0x600))

/* dpmaif uplink . */
#define NRL2_DPMAIF_UL_DBG_STA2		(BASE_NADDR_NRL2_DPMAIF_UL + 0x88)
#define NRL2_DPMAIF_UL_RESERVE_AO_RW	(BASE_NADDR_NRL2_DPMAIF_UL + 0xAC)
#define NRL2_DPMAIF_UL_ADD_DESC_CH0	(BASE_NADDR_NRL2_DPMAIF_UL + 0xB0)
#define NRL2_DPMAIF_UL_ADD_DESC_CH4	(BASE_NADDR_NRL2_DPMAIF_UL + 0xE0)

/* dpmaif downlink. */
#define NRL2_DPMAIF_DL_BAT_INIT			(BASE_NADDR_NRL2_DPMAIF_DL + 0x00)
#define NRL2_DPMAIF_DL_BAT_ADD			(BASE_NADDR_NRL2_DPMAIF_DL + 0x04)
#define NRL2_DPMAIF_DL_BAT_INIT_CON0		(BASE_NADDR_NRL2_DPMAIF_DL + 0x08)
#define NRL2_DPMAIF_DL_BAT_INIT_CON1		(BASE_NADDR_NRL2_DPMAIF_DL + 0x0C)
#define NRL2_DPMAIF_DL_PIT_INIT_CON5		(BASE_NADDR_NRL2_DPMAIF_DL + 0x14)
#define NRL2_DPMAIF_DL_PIT_INIT			(BASE_NADDR_NRL2_DPMAIF_DL + 0x20)
#define NRL2_DPMAIF_DL_PIT_ADD			(BASE_NADDR_NRL2_DPMAIF_DL + 0x24)
#define NRL2_DPMAIF_DL_PIT_INIT_CON0		(BASE_NADDR_NRL2_DPMAIF_DL + 0x28)
#define NRL2_DPMAIF_DL_PIT_INIT_CON1		(BASE_NADDR_NRL2_DPMAIF_DL + 0x2C)
#define NRL2_DPMAIF_DL_PIT_INIT_CON2		(BASE_NADDR_NRL2_DPMAIF_DL + 0x30)
#define NRL2_DPMAIF_DL_PIT_INIT_CON3		(BASE_NADDR_NRL2_DPMAIF_DL + 0x34)
#define NRL2_DPMAIF_DL_BAT_INIT_CON3		(BASE_NADDR_NRL2_DPMAIF_DL + 0x50)
#define NRL2_DPMAIF_DL_PIT_INIT_CON4		(BASE_NADDR_NRL2_DPMAIF_DL + 0x54)
#define NRL2_DPMAIF_DL_UL_INTR_TRAS_CON		(BASE_NADDR_NRL2_DPMAIF_DL + 0xAC)
#define NRL2_DPMAIF_DL_DBG_STA1			(BASE_NADDR_NRL2_DPMAIF_DL + 0xB4)

/* dpmaif misc. */
#define NRL2_DPMAIF_AP_MISC_AP_L2TISAR0		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x00)
#define NRL2_DPMAIF_AP_MISC_APDL_L2TISAR0	(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x50)
#define NRL2_DPMAIF_AP_MISC_AP_IP_BUSY		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x60)
#define NRL2_DPMAIF_AP_MISC_CG_EN		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x68)
#define NRL2_DPMAIF_AP_MISC_OVERWRITE_CFG	(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x90)
#define NRL2_DPMAIF_AP_MISC_MEM_CLR		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x94)

/* dpmaif uplink sram. */
#define NRL2_DPMAIF_AO_UL_CHNL0_CON0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x10)
#define NRL2_DPMAIF_AO_UL_CHNL0_CON1		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x14)
#define NRL2_DPMAIF_AO_UL_CHNL0_CON2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x18)

/* dpmaif downlink sram. */
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x0)
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON1		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x4)
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x8)
#define NRL2_DPMAIF_AO_DL_RDY_CHK_THRES		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xC)
#define NRL2_DPMAIF_AO_DL_RDY_CHK_FRG_THRES	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x10)
#define NRL2_DPMAIF_AO_DL_LRO_AGG_CFG		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x20)
#define NRL2_DPMAIF_AO_DL_LROPIT_TIMEOUT0	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x24)
#define NRL2_DPMAIF_AO_DL_LROPIT_TIMEOUT1	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x28)
#define NRL2_DPMAIF_AO_DL_HPC_CNTL		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x38)
#define NRL2_DPMAIF_AO_DL_PIT_SEQ_END		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x40)
#define NRL2_DPMAIF_AO_DL_BAT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xD8)
#define NRL2_DPMAIF_AO_DL_BAT_STA3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xDC)
#define NRL2_DPMAIF_AO_DL_PIT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xEC)
#define NRL2_DPMAIF_AO_DL_PIT_STA3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x60)
#define NRL2_DPMAIF_AO_DL_FRGBAT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x78)
#define NRL2_DPMAIF_AO_DL_LRO_STA5		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xA4)
#define NRL2_DPMAIF_AO_DL_LRO_STA6		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xA8)

/* dpmaif hpc. */
#define NRL2_DPMAIF_HPC_INTR_MASK		(BASE_NADDR_NRL2_DPMAIF_MMW_HPC + 0xF4)

/* dpmaif LRO. */
#define NRL2_DPMAIF_DL_LROPIT_INIT		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x0)
#define NRL2_DPMAIF_DL_LROPIT_ADD		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x10)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON0		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x14)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON1		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x18)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON2		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x1C)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON3		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x20)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON4		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x24)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON5		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x28)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON6		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x2C)

/* dpmaif uplink config. */
#define DPMAIF_PD_UL_CHNL0_CON0		NRL2_DPMAIF_AO_UL_CHNL0_CON0
#define DPMAIF_PD_UL_CHNL0_CON1		NRL2_DPMAIF_AO_UL_CHNL0_CON1
#define DPMAIF_PD_UL_CHNL0_CON2		NRL2_DPMAIF_AO_UL_CHNL0_CON2
#define DPMAIF_PD_UL_ADD_DESC_CH	NRL2_DPMAIF_UL_ADD_DESC_CH0
#define DPMAIF_PD_UL_DBG_STA2		NRL2_DPMAIF_UL_DBG_STA2

/* dpmaif downlink config. */
#define DPMAIF_PD_DL_BAT_INIT		NRL2_DPMAIF_DL_BAT_INIT
#define DPMAIF_PD_DL_BAT_ADD		NRL2_DPMAIF_DL_BAT_ADD
#define DPMAIF_PD_DL_BAT_INIT_CON0	NRL2_DPMAIF_DL_BAT_INIT_CON0
#define DPMAIF_PD_DL_BAT_INIT_CON1	NRL2_DPMAIF_DL_BAT_INIT_CON1
#define DPMAIF_PD_DL_BAT_INIT_CON3	NRL2_DPMAIF_DL_BAT_INIT_CON3
#define DPMAIF_PD_DL_DBG_STA1		NRL2_DPMAIF_DL_DBG_STA1
#define DPMAIF_PD_DL_UL_TRAS_INTR_CON   NRL2_DPMAIF_DL_UL_INTR_TRAS_CON

/* dpmaif pd ap misc, ul misc config. */
#define DPMAIF_PD_AP_UL_L2TISAR0	NRL2_DPMAIF_AP_MISC_AP_L2TISAR0
#define DPMAIF_PD_AP_DL_L2TISAR0	NRL2_DPMAIF_AP_MISC_APDL_L2TISAR0
#define DPMAIF_PD_AP_IP_BUSY		NRL2_DPMAIF_AP_MISC_AP_IP_BUSY

/* dpmaif dl config. */
#define DPMAIF_AO_DL_PKTINFO_CONO	NRL2_DPMAIF_AO_DL_PKTINFO_CON0
#define DPMAIF_AO_DL_PKTINFO_CON1	NRL2_DPMAIF_AO_DL_PKTINFO_CON1
#define DPMAIF_AO_DL_PKTINFO_CON2	NRL2_DPMAIF_AO_DL_PKTINFO_CON2
#define DPMAIF_AO_DL_RDY_CHK_THRES	NRL2_DPMAIF_AO_DL_RDY_CHK_THRES
#define DPMAIF_AO_DL_BAT_STA2		NRL2_DPMAIF_AO_DL_BAT_STA2
#define DPMAIF_AO_DL_BAT_STA3		NRL2_DPMAIF_AO_DL_BAT_STA3
#define DPMAIF_AO_DL_PIT_STA2		NRL2_DPMAIF_AO_DL_PIT_STA2
#define DPMAIF_AO_DL_PIT_STA3		NRL2_DPMAIF_AO_DL_PIT_STA3
#define DPMAIF_AO_DL_FRG_CHK_THRES	NRL2_DPMAIF_AO_DL_RDY_CHK_FRG_THRES
#define DPMAIF_AO_DL_FRG_STA2		NRL2_DPMAIF_AO_DL_FRGBAT_STA2

#define NRL2_DPMAIF_DLY_IRQ_TIMER3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x1C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER4		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x2C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER5		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x3C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER6		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x60)
#define NRL2_DPMAIF_DLY_IRQ_TIMER7		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x64)
#define NRL2_DPMAIF_AO_DL_DLY_IRQ_TIMER1	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x58)
#define NRL2_DPMAIF_AO_DL_DLY_IRQ_TIMER2	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x5C)

#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2	((unsigned long)(DPMAIF_PD_BASE + 0xF00))
#define NRL2_REG_TOE_HASH_EN		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x0)
#define NRL2_REG_HASH_CFG_CON		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x4)
#define NRL2_REG_HASH_SEC_KEY_0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x8)
#define NRL2_REG_HPC_STATS_THRES	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x30)
#define NRL2_REG_HPC_STATS_TIMER_CFG	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x34)
#define NRL2_REG_HASH_SEC_KEY_UPD	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x70)

/* dpmaif dl2 config. */
#define BASE_ADDR_NRL2_DPMAIF_DL_2_CFG			0x1000UL
#define BASE_ADDR_NRL2_DPMAIF_AP_MISC_CFG		0x400UL
#define BASE_ADDR_MMW_DPMAIF_PD_MISC_CFG		0xE00UL
#define BASE_ADDR_MMW_DPMAIF_PD_MISC2_CFG		0xF00UL
#define BASE_ADDR_NRL2_DPMAIF_DL_2_CFG_SRAM		0UL

#define DPMAIF_DL_2_BAT_INIT_CON0                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x08)
#define DPMAIF_DL_2_BAT_INIT_CON3                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x50)
#define DPMAIF_DL_2_BAT_INIT_CON1                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x0C)
#define DPMAIF_DL_2_BAT_INIT                     (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x00)
#define DPMAIF_DL_2_PIT_INIT_CON0                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x28)
#define DPMAIF_DL_2_PIT_INIT_CON4                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x54)
#define DPMAIF_DL_2_PIT_INIT_CON1                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x2C)
#define DPMAIF_DL_2_PIT_INIT_CON3                (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x34)
#define DPMAIF_DL_2_PIT_INIT                     (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x20)
#define DPMAIF_DL_2_STA13                        (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x18)
#define DPMAIF_DL_2_STA14                        (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x1C)
#define DPMAIF_DL_2_STA4                         (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x90)
#define DPMAIF_DL_2_FRG_STA4                     (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0xF0)
#define DPMAIF_DL_2_BAT_ADD                      (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x04)
#define DPMAIF_DL_2_PIT_ADD                      (BASE_ADDR_NRL2_DPMAIF_DL_2_CFG + 0x24)

#define NRL2_DPMAIF_AP_MISC_APDL_L2TISAR1        (BASE_ADDR_NRL2_DPMAIF_AP_MISC_CFG + 0x54)

#define NRL2_DPMAIF_MISC_PD_APDL12_MASK_SET		(BASE_ADDR_MMW_DPMAIF_PD_MISC_CFG + 0x60)
#define NRL2_DPMAIF_MISC_PD_APDL12_MASK_CLR		(BASE_ADDR_MMW_DPMAIF_PD_MISC_CFG + 0x64)
#define NRL2_DPMAIF_MISC_PD_APDL12_MASK_RW		(BASE_ADDR_MMW_DPMAIF_PD_MISC_CFG + 0x68)
#define DPMAIF_DL_RESOURCE_DOMAIN			(BASE_ADDR_NRL2_DPMAIF_DL_2_CFG_SRAM + 0x8)

#define DPMAIF_ULQS			0x1F
#define DPMAIF_UL_ADD_NOT_READY		BIT(31)
#define DPMAIF_UL_ADD_UPDATE		BIT(31)
#define DPMAIF_UL_ALL_QUE_ARB_EN	(DPMAIF_ULQS << 8)

#define DPMAIF_DL_ADD_UPDATE		BIT(31)
#define DPMAIF_DL_ADD_NOT_READY		BIT(31)
#define DPMAIF_DL_FRG_ADD_UPDATE	BIT(16)

#define DPMAIF_DL_BAT_INIT_ALLSET	BIT(0)
#define DPMAIF_DL_BAT_FRG_INIT		BIT(16)
#define DPMAIF_DL_BAT_INIT_EN		BIT(31)
#define DPMAIF_DL_BAT_INIT_NOT_READY	BIT(31)
#define DPMAIF_DL_BAT_INIT_ONLY_ENABLE_BIT	0

#define DPMAIF_DL_PIT_INIT_ALLSET	BIT(0)
#define DPMAIF_DL_PIT_INIT_EN		BIT(31)
#define DPMAIF_DL_PIT_INIT_NOT_READY	BIT(31)

#define DPMAIF_PKT_ALIGN64_MODE		0
#define DPMAIF_PKT_ALIGN128_MODE	1

#define DPMAIF_BAT_REMAIN_SZ_BASE	16
#define DPMAIF_BAT_BUFFER_SZ_BASE	128
#define DPMAIF_FRG_BUFFER_SZ_BASE	128

#define DPMAIF_PIT_SIZE_MSK		0x3FFFF

#define DPMAIF_BAT_EN_MSK		BIT(16)
#define DPMAIF_FRG_EN_MSK		BIT(28)
#define DPMAIF_BAT_SIZE_MSK		0xFFFF

#define DPMAIF_BAT_BID_MAXCNT_MSK	0xFFFF0000
#define DPMAIF_BAT_REMAIN_MINSZ_MSK	0x0000FF00
#define DPMAIF_PIT_CHK_NUM_MSK		0xFF000000
#define DPMAIF_BAT_BUF_SZ_MSK		0x0001FF00
#define DPMAIF_FRG_BUF_SZ_MSK		0x0001FF00
#define DPMAIF_BAT_RSV_LEN_MSK		0x000000FF
#define DPMAIF_PKT_ALIGN_MSK		(0x3 << 22)

#define DPMAIF_BAT_CHECK_THRES_MSK	(0x3F << 16)
#define DPMAIF_FRG_CHECK_THRES_MSK	0xFF
#define DPMAIF_PKT_ALIGN_EN		BIT(23)
#define DPMAIF_DRB_SIZE_MSK		0x0000FFFF

#define DPMAIF_DL_PIT_WRIDX_MSK		0x3FFFF
#define DPMAIF_DL_BAT_WRIDX_MSK		0x3FFFF
#define DPMAIF_DL_FRG_WRIDX_MSK		0x3FFFF

/* DPMAIF_PD_UL_DBG_STA2 */
#define DPMAIF_UL_IDLE_STS_MSK		BIT(11)
#define DPMAIF_UL_IDLE_STS		BIT(11)

/* DPMAIF_PD_DL_DBG_STA1 */
#define DPMAIF_DL_IDLE_STS		BIT(23)
#define DPMAIF_DL_PKT_CHECKSUM_EN	BIT(31)
#define DPMAIF_PORT_MODE_MSK		BIT(30)
#define DPMAIF_PORT_MODE_PCIE		BIT(30)

/* BASE_NADDR_NRL2_DPMAIF_WDMA */
#define DPMAIF_DL_BAT_CACHE_PRI		BIT(22)
#define DPMAIF_DL_BURST_PIT_EN		BIT(13)
#define DPMAIF_MEM_CLR_MASK		BIT(0)
#define DPMAIF_SRAM_SYNC_MASK		BIT(0)
#define DPMAIF_UL_INIT_DONE_MASK	BIT(0)
#define DPMAIF_DL_INIT_DONE_MASK	BIT(0)

#define DPMAIF_DL_PIT_SEQ_MSK		0xFF
#define DPMAIF_PCIE_MODE_SET_VALUE	0x55

#define DPMAIF_UDL_IP_BUSY_MSK		BIT(0)

#define DP_UL_INT_DONE_OFFSET		0
#define DP_UL_INT_EMPTY_OFFSET		5
#define DP_UL_INT_MD_NOTRDY_OFFSET	10
#define DP_UL_INT_PWR_NOTRDY_OFFSET	15
#define DP_UL_INT_LEN_ERR_OFFSET	20

/* Enable and mask/unmaks UL interrupt mask */
#define DPMAIF_UL_INT_QDONE_MSK			(DPMAIF_ULQS << DP_UL_INT_DONE_OFFSET)
#define DPMAIF_UL_TOP0_INT_MSK			BIT(9)
#define DPMAIF_UL_INT_VALID_MSK			0x1FFFFFF
#define DPMAIF_UL3_INT_VALID_MSK		0x3FFFFFFF

/* UL interrupt status */
#define DPMAIF_UL_INT_QDONE		(DPMAIF_ULQS << DP_UL_INT_DONE_OFFSET)

/* Enable and  Mask/unmask DL interrupt mask */
#define DPMAIF_DL_INT_DLQ_QDONE_MSK		BIT(0)
#define DPMAIF_DL_INT_BATCNT_LEN_ERR_MSK	BIT(2)
#define DPMAIF_DL_INT_DLQ_PITCNT_LEN_ERR_MSK	BIT(3)
#define DPMAIF_DL_INT_FRG_LEN_ERR_MSK		BIT(7)
#define DPMAIF_DL_INT_DLQ0_QDONE_MSK		BIT(8)
#define DPMAIF_DL_INT_DLQ1_QDONE_MSK		BIT(9)
#define DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR_MSK	BIT(10)
#define DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR_MSK	BIT(11)
#define DPMAIF_DL_INT_Q2TOQ1_MSK		BIT(24)
#define DPMAIF_DL_INT_Q2APTOP_MSK		BIT(25)
#define DPMAIF_DL_INT_VALID_MSK			0x1FFF

/* DL interrupt status */
#define DPMAIF_DL_INT_DLQ_QDONE			BIT(0)
#define DPMAIF_DL_INT_BATCNT_LEN_ERR		BIT(2)
#define DPMAIF_DL_INT_DLQ_PITCNT_LEN_ERR	BIT(3)
#define DPMAIF_DL_INT_FRG_LEN_ERR		BIT(7)
#define DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR	BIT(8)
#define DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR	BIT(9)
#define DPMAIF_DL_INT_DLQ0_QDONE		BIT(13)
#define DPMAIF_DL_INT_DLQ1_QDONE		BIT(14)

/* DPMAIF LRO HW configure */
#define DPMAIF_HPC_LRO_PATH_DF			3

/* 0: HPC rules add by HW; 1: HPC rules add by Host */
#define DPMAIF_HPC_ADD_MODE_DF			0
#define DPMAIF_HPC_NUM_DF			8
#define DPMAIF_AGG_MAX_LEN_DF			65535
#define DPMAIF_AGG_TBL_ENT_NUM_DF		50
#define DPMAIF_HASH_PRIME_DF			13
#define DPMAIF_MID_TIMEOUT_THRES_DF		100
#define DPMAIF_LRO_TIMEOUT_THRES_DF		100
#define DPMAIF_LRO_PRS_THRES_DF			10
#define DPMAIF_LRO_HASH_BIT_CHOOSE_DF		0

#define DPMAIF_LROPIT_EN_MSK			0x100000
#define DPMAIF_LROPIT_CHAN_OFS			16
#define DPMAIF_ADD_LRO_PIT_CHAN_OFS		20

#define DPMAIF_DL_PIT_BYTE_SIZE		16
#define DPMAIF_DL_BAT_BYTE_SIZE		8
#define DPMAIF_DL_FRG_BYTE_SIZE		8
#define DPMAIF_UL_DRB_BYTE_SIZE		16

#define DPMAIF_UL_DRB_ENTRY_WORD	(DPMAIF_UL_DRB_BYTE_SIZE >> 2)
#define DPMAIF_DL_PIT_ENTRY_WORD	(DPMAIF_DL_PIT_BYTE_SIZE >> 2)
#define DPMAIF_DL_BAT_ENTRY_WORD	(DPMAIF_DL_BAT_BYTE_SIZE >> 2)

#define DPMAIF_HW_BAT_REMAIN		64
#define DPMAIF_HW_PKT_BIDCNT		1

#define DPMAIF_HW_CHK_BAT_NUM		62
#define DPMAIF_HW_CHK_FRG_NUM		DPMAIF_HW_CHK_BAT_NUM
#define DPMAIF_HW_CHK_PIT_NUM		(2 * DPMAIF_HW_CHK_BAT_NUM)

#define DPMAIF_TOEPLITZ_HASH_EN		1

/* word num */
#define DPMAIF_HASH_SEC_KEY_NUM		40
#define DPMAIF_HASH_DEFAULT_VALUE	0

/* 10k */
#define DPMAIF_HPC_STATS_THRESHOLD	0x2800

/* 0x7A1- 1s: unit:512us */
#define DPMAIF_HPC_STATS_TIMER_CFG	0

#define DPMAIF_HASH_INDR_SIZE       0x8
#define DPMAIF_HASH_INDR_MASK       0xFF00FFFF
#define DPMAIF_HASH_DEFAULT_V_MASK  0xFFFFFF00
#define DPMAIF_DL_2_BAT_WRIDX_MSK   0xFFFF
#define DPMAIF_DL2_PIT_EN_MSK       BIT(0)

/* Mask/unmask DL2 interrupt mask */
#define DPMAIF_DL_INT_DLQ2_QDONE_MSK            BIT(0)
#define DPMAIF_DL2_INT_BATCNT_LEN_ERR_MSK       BIT(2)
#define DPMAIF_DL_INT_DLQ2_PITCNT_LEN_ERR_MSK   BIT(3)
#define DPMAIF_DL2_INT_FRG_LEN_ERR_MSK          BIT(7)
#define DPMAIF_DL2_INT_OTHER_MSK                0xFF00FF

/* DL2 interrupt status */
#define DPMAIF_DL2_INT_DLQ2_QDONE           BIT(0)
#define DPMAIF_DL2_INT_BATCNT_LEN_ERR       BIT(2)
#define DPMAIF_DL2_INT_DLQ2_PITCNT_LEN_ERR  BIT(3)
#define DPMAIF_DL2_INT_FRG_LEN_ERR          BIT(7)
#define DLQ2_INTR_MSK                       0xFF

void mtk_dpmaif_drv_ul_mask_intr(struct dpmaif_drv_info *drv_info, u32 mask);
void mtk_dpmaif_drv_dlq_mask_pit_cnt_len_err_intr(struct dpmaif_drv_info *drv_info, u8 qno);
void mtk_dpmaif_drv_mask_dl_frgcnt_len_err_intr(struct dpmaif_drv_info *drv_info, u8 bat_id);
void mtk_dpmaif_drv_mask_dl_batcnt_len_err_intr(struct dpmaif_drv_info *drv_info, u8 bat_id);
void mtk_dpmaif_drv_ul_mask_multi_tx_done_intr(struct dpmaif_drv_info *drv_info, u8 q_mask);
u32 mtk_dpmaif_drv_get_dl_lv2_sts(struct dpmaif_drv_info *drv_info, u8 q_id);
u32 mtk_dpmaif_drv_get_dl_intr_mask(struct dpmaif_drv_info *drv_info, u8 q_id);
int mtk_dpmaif_drv_dlq_mask_rx_done_intr(struct dpmaif_drv_info *drv_info, u8 q_id);
u32 mtk_dpmaif_drv_get_ul_lv2_sts(struct dpmaif_drv_info *drv_info);
void mtk_dpmaif_drv_clr_ip_busy_sts(struct dpmaif_drv_info *drv_info);
int mtk_dpmaif_drv_ul_intr_init(struct dpmaif_drv_info *drv_info);

u32 mtk_dpmaif_drv_get_ul_intr_mask(struct dpmaif_drv_info *drv_info);

int mtk_dpmaif_drv_init_com(struct dpmaif_drv_info *drv_info, void *data);
int mtk_dpmaif_drv_start_queue(struct dpmaif_drv_info *drv_info,
			       enum dpmaif_drv_dir dir);
int mtk_dpmaif_drv_stop_queue(struct dpmaif_drv_info *drv_info,
			      enum dpmaif_drv_dir dir);
int mtk_dpmaif_drv_intr_complete_com(struct dpmaif_drv_info *drv_info,
				     enum dpmaif_drv_intr_type type, u8 id, u64 data);
int mtk_dpmaif_drv_send_doorbell_com(struct dpmaif_drv_info *drv_info,
				     enum dpmaif_drv_ring_type type, u8 id, u32 cnt);
int mtk_dpmaif_drv_get_ring_idx(struct dpmaif_drv_info *drv_info,
				enum dpmaif_drv_ring_idx index, u8 q_id);
int mtk_dpmaif_drv_feature_cmd_com(struct dpmaif_drv_info *drv_info,
				   enum dpmaif_drv_cmd cmd, void *data);
int mtk_dpmaif_drv_intr_handle_com(struct dpmaif_drv_info *drv_info, void *data, u8 irq_id);
void mtk_dpmaif_drv_dump(struct dpmaif_drv_info *drv_info);

#endif
