/* SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_PCI_REG_H__
#define __MTK_PCI_REG_H__

#define REG_PCIE_DEBUG_MONITOR			0x002C
#define REG_PCIE_CFG_MSI_MERGED			0x00A8
#define REG_PCIE_SW_TRIG_INT			0x00BC
#define REG_PCIE_LTSSM_STATUS			0x0150
#define REG_PCIE_DEBUG_SEL_0			0x0164
#define REG_PCIE_DEBUG_SEL_1			0x0168
#define REG_IMASK_LOCAL				0x0180
#define REG_ISTATUS_LOCAL			0x0184
#define REG_INT_ENABLE_HOST			0x0188
#define REG_ISTATUS_HOST			0x018C
#define A_ATR_EVT_DOORBELL			BIT(19)
#define REG_PCIE_LOW_POWER_CTRL			0x0194
#define REG_ISTATUS_HOST_CTRL			0x01AC
#define REG_ISTATUS_PENDING_ADT			0x01D4
#define REG_ISTATUS_A_ADT_SLV0			0x01E0
#define REG_ISTATUS_A_ADT_SLV1			0x01E4
#define REG_ISTATUS_A_ADT_SLV2			0x01E8
#define REG_ISTATUS_A_ADT_SLV3			0x01EC
#define REG_INT_ENABLE_HOST_SET			0x01F0
#define REG_INT_ENABLE_HOST_CLR			0x01F4
#define REG_PCIE_DMA_DUMMY_0			0x01F8
#define REG_RC2EP_SW_TRIG_LOCAL_INTR_MASK	0x0310
#define REG_ISTATUS_HOST_CTRL_NEW		0x031C
#define REG_PCIE_MISC_CTRL			0x0348
#define REG_PCIE_DUMMY_0			0x03C0
#define REG_SW_TRIG_INTR_SET			0x03C8
#define REG_SW_TRIG_INTR_CLR			0x03CC
#define REG_PCIE_CFG_MSIX			0x03EC
#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_LSB	0x0600
#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_MSB	0x0604
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_LSB	0x0608
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_MSB	0x060C
#define REG_ATR_PCIE_WIN0_T0_TRSL_PARAM		0x0610
#if IS_ENABLED(CONFIG_GOOGLE_B495424578_DEBUG)
#define REG_ATR_PCIE_WIN0_T1_SRC_ADDR_LSB	0x0620
#define REG_ATR_PCIE_WIN0_T1_SRC_ADDR_MSB	0x0624
#define REG_ATR_PCIE_WIN0_T1_TRSL_ADDR_LSB	0x0628
#define REG_ATR_PCIE_WIN0_T1_TRSL_ADDR_MSB	0x062C
#define REG_ATR_PCIE_WIN0_T1_TRSL_PARAM		0x0630
#endif
#define REG_PCIE_DEBUG_DUMMY_0			0x0D00
#define REG_PCIE_DEBUG_DUMMY_1			0x0D04
#define REG_PCIE_DEBUG_DUMMY_2			0x0D08
#define REG_PCIE_DEBUG_DUMMY_3			0x0D0C
#define REG_PCIE_DEBUG_DUMMY_4			0x0D10
#define REG_PCIE_DEBUG_DUMMY_5			0x0D14
#define REG_PCIE_DEBUG_DUMMY_6			0x0D18
#define REG_PCIE_DEBUG_DUMMY_7			0x0D1C
#define REG_PCIE_DEBUG_DUMMY_3490		0x3490
#define REG_PCIE_DEBUG_DUMMY_34DC		0x34DC
#define REG_PCIE_RESOURCE_STATUS		0x0D28
#define REG_RC2EP_SW_TRIG_LOCAL_INTR_STAT	0x0D94
#define REG_RC2EP_SW_TRIG_LOCAL_INTR_SET	0x0D98
#define REG_RC2EP_SW_TRIG_LOCAL_INTR_CLR	0x0D9C
#define REG_DIS_ASPM_LOWPWR_SET_0		0x0E50
#define REG_DIS_ASPM_LOWPWR_CLR_0		0x0E54
#define REG_DIS_ASPM_LOWPWR_SET_1		0x0E58
#define REG_DIS_ASPM_LOWPWR_CLR_1		0x0E5C
#define REG_DIS_ASPM_LOWPWR_STS_0		0x0E60
#define REG_DIS_ASPM_LOWPWR_STS_1		0x0E64
#define REG_PCIE_PEXTP_MAC_SLEEP_CTRL		0x0E70
#define REG_PCIE_PEXTP_MAC_ACTIVE_CTRL		0x0E74
#define REG_MSIX_SW_TRIG_SET_GRP0_0		0x0E80
#define REG_PCIE_MSIX_CAP_CTRL			0x10D0
#define REG_PCIE_AER_UNC_STATUS			0x1204
#define REG_PCIE_AER_CO_STATUS			0x1210
#define REG_PCIE_AER_CAPCTL			0x1218
#define REG_PCIE_ERR_ADDR_L			0x0E40
#define REG_PCIE_ERR_ADDR_H			0x0E44
#define REG_PCIE_ERR_INFO			0x0E48

#define REG_MSIX_ISTATUS_HOST_GRP0_0		0x0F00
#define REG_MSIX_PBA_GRP0_0			0x0F80
#define REG_IMASK_HOST_MSIX_SET_GRP0_0		0x3000
#define REG_IMASK_HOST_MSIX_CLR_GRP0_0		0x3080
#define REG_IMASK_HOST_MSIX_GRP0_0		0x3100
#define REG_MSIX_TABLE_GRP0_ENT_0_0		0x4000
#define REG_DEV_INFRA_BASE			0x10001000

#define REG_PWR_PROFILE_L0_STATE_CNT		0x3400
#define REG_PWR_PROFILE_SETTING			0x3440

/* mhccif registers */
#define MHCCIF_RC2EP_SW_BSY			0x4
#define MHCCIF_RC2EP_SW_INT_START		0x8
#define MHCCIF_RC2EP_SW_TCHNUM			0xC
#define MHCCIF_RC2EP_SPARE_REG_4		0x0150
#define MHCCIF_RC2EP_SPARE_REG_6		0x0158
#define MHCCIF_RC2EP_SPARE_REG_7		0x015C
#define MHCCIF_RC2EP_SPARE_REG_15		0x017C
#define MHCCIF_RC2EP_EVT_EXCEPT_ACK		BIT(1)
#define MHCCIF_RC2EP_EVT_EXCEPT_CLEARQ_ACK	BIT(2)
#define MHCCIF_RC2EP_EVT_PCIE_DS_LOCK		BIT(3)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA0	BIT(4)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA1	BIT(5)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA3	BIT(6)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA2	BIT(7)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_DPMAIF	BIT(8)
#define MHCCIF_RC2EP_EVT_PCIE_PM_SUSPEND_REQ	BIT(9)
#define MHCCIF_RC2EP_EVT_PCIE_PM_RESUME_REQ	BIT(10)
#define MHCCIF_RC2EP_EVT_PCIE_PM_SUSPEND_REQ_AP	BIT(11)
#define MHCCIF_RC2EP_EVT_PCIE_PM_RESUME_REQ_AP	BIT(12)
#define MHCCIF_RC2EP_EVT_DEVICE_RESET		BIT(13)
#define MHCCIF_RC2EP_EVT_DRM_DISABLE_AP		BIT(14)
#define MHCCIF_RC2EP_EVT_MD_REBOOT_ACK		BIT(19)
#define MHCCIF_RC2EP_EVT_TRM_NOTIFY		BIT(21)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_TEST	BIT(31)

#define MHCCIF_EP2RC_SW_INT_STS			0x10
#define MHCCIF_EP2RC_SW_INT_ACK			0x14
#define MHCCIF_EP2RC_SW_INT_EAP_MASK		0x20
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_SET	0x30
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_CLR	0x40
#define MHCCIF_EP2RC_SPARE_REG_1		0x0104
#define MHCCIF_EP2RC_SPARE_REG_3		0x010C
#define MHCCIF_EP2RC_SPARE_REG_5		0x0114
#define MHCCIF_EP2RC_SPARE_REG_13		0x0134
#define MHCCIF_EP2RC_SPARE_REG_14		0x0138
#define MHCCIF_EP2RC_EVT_PCIE_DS_LOCK_ACK	BIT(0)
#define MHCCIF_EP2RC_EVT_D2H_EXCEPT_INIT	BIT(1)
#define MHCCIF_EP2RC_EVT_EXCEPT_INIT_DONE	BIT(2)
#define MHCCIF_EP2RC_EVT_EXCEPT_CLEARQ_DONE	BIT(3)
#define MHCCIF_EP2RC_EVT_EXCEPT_ALLQ_RESET	BIT(4)
#define MHCCIF_EP2RC_EVT_BOOT_FLOW_SYNC		BIT(5)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA0	BIT(6)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA1	BIT(7)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA3	BIT(8)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA2	BIT(9)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_DPMAIF	BIT(10)
#define MHCCIF_EP2RC_EVT_PCIE_PM_SUSPEND_ACK	BIT(11)
#define MHCCIF_EP2RC_EVT_PCIE_PM_RESUME_ACK	BIT(12)
#define MHCCIF_EP2RC_EVT_PCIE_PM_SUSPEND_ACK_AP	BIT(13)
#define MHCCIF_EP2RC_EVT_PCIE_PM_RESUME_ACK_AP	BIT(14)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_SAP	BIT(15)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_MD	BIT(16)
#define MHCCIF_EP2RC_EVT_SOFT_OFF_NOTIFY	BIT(17)
#define MHCCIF_EP2RC_EVT_MD_REBOOT		BIT(19)
#define MHCCIF_EP2RC_EVT_MD_POWEROFF		BIT(20)
#define MHCCIF_EP2RC_EVT_GNSS_ENABLE		BIT(21)
#define MHCCIF_EP2RC_EVT_GNSS_DISABLE		BIT(22)
#define MHCCIF_EP2RC_EVT_FRC_DONE_NOTIFY	BIT(24)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_TEST1	BIT(30)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_TEST2	BIT(31)

#define PCIE_SUSPEND_CNT_MAGIC			(0x53550000)
#define PCIE_RESUME_CNT_MAGIC			(0x52450000)

#endif /* __MTK_PCI_REG_H__ */
