/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * This header provides macros for hwirq of MBU ISP custom internal GIAs.
 *
 * Copyright 2024 Google LLC
 */

#ifndef _DT_BINDINGS_IRQ_GIA_GOOGLE_MBU_ISP_H
#define _DT_BINDINGS_IRQ_GIA_GOOGLE_MBU_ISP_H

#define ISPBE_GIA_MSA_HDR_PIPE_LEVEL_AGGR_0_MSA_HDR_QCHWRAP_LEVEL_AGGR_0			3
#define ISPBE_GIA_MSA_TNR_PIPE_LEVEL_AGGR_0_MSA_TNR_QCHWRAP_LEVEL_AGGR_0			3
#define ISPBE_GIA_PIPE_LEVEL_AGGR_0_YUV_LEVEL_AGGR_0						3
#define ISPBE_GIA_PIPE_LEVEL_AGGR_0_BTR2_LEVEL_AGGR_0						4
#define ISPBE_GIA_PIPE_LEVEL_AGGR_0_BTR1_LEVEL_AGGR_0						5
#define ISPBE_GIA_PIPE_LEVEL_AGGR_0_BTR0_LEVEL_AGGR_0						6

#define GCV_GIA_GSW_LEVEL_AGGR_0_GWE_LEVEL_AGGR_0						3
#define GCV_GIA_GSW_LEVEL_AGGR_0_GSE_LEVEL_AGGR_0						4
#define GCV_GIA_GWE_LEVEL_AGGR_0_GWE_CORE_LEVEL_AGGR_0						1
#define GCV_GIA_CRE_PIPE_LEVEL_AGGR_0_CRE_LEVEL_AGGR_0						3

#endif /* _DT_BINDINGS_IRQ_GIA_GOOGLE_MBU_ISP_H */
