/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!!!! THIS IS A GENERATED FILE, DO NOT EDIT !!!!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * This header provides constants for interrupts on MBU.
 *
 * Copyright 2024 Google LLC
 *
 */
#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_MBU_H
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_MBU_H

#include <dt-bindings/interrupt-controller/arm-gic.h>

#define SSWRP_AOSS_AOSS_AP_INTR_VM1_REQ                              0
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_0                               1
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_1                               2
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_2                               3
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_3                               4
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_4                               5
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_5                               6
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_6                               7
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_7                               8
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_8                               9
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_9                               10
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_10                              11
#define SSWRP_AOSS_AOSS_AP_INTR_MBOX_11                              12
#define SSWRP_AOSS_AOSS_AP_INTR_NS_AOSSAMBSS_0                       13
#define SSWRP_AOSS_AOSS_AP_INTR_NS_AOSSAMBSS_1                       14
#define SSWRP_AOSS_AOSS_AP_INTR_NS_CPM_REQ                           15
#define SSWRP_AOSS_AOSS_AP_INTR_NS_CPM_RESP                          16
#define SSWRP_AOSS_AOSS_AP_INTR_S_AOSSAMBSS_0                        17
#define SSWRP_AOSS_AOSS_AP_INTR_S_AOSSAMBSS_1                        18
#define SSWRP_AOSS_AOSS_AP_INTR_S_CPM_REQ                            19
#define SSWRP_AOSS_AOSS_AP_INTR_S_CPM_RESP                           20
#define SSWRP_AOSS_AOSS_GIA_OUT_AP                                   21
#define SSWRP_AOSS_AOSS_GIA_OUT_AP_GIC                               22
#define SSWRP_AOSS_AOSS_GIA_OUT_AP_NS_0                              23
#define SSWRP_AOSS_AOSS_GIA_OUT_AP_S                                 24
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_0                       25
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_1                       26
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_2                       27
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_3                       28
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_4                       29
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU0_5                       30
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_0                       31
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_1                       32
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_2                       33
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_3                       34
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_4                       35
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_5                       36
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_6                       37
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU1_7                       38
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_0                       39
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_1                       40
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_2                       41
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_3                       42
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_4                       43
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_5                       44
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_6                       45
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPM_CPU2_7                       46
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU0_0                           47
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU0_1                           48
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU0_2                           49
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU1_0                           50
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU1_1                           51
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU1_2                           52
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU2_0                           53
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU2_1                           54
#define SSWRP_AOSS_AOSS_CPUACC_INTR_CPU2_2                           55
#define SSWRP_AOSS_AOSS_AP_INTR_VM1_RESP                             56
#define SSWRP_AOSS_AOSS_AP_INTR_VM2_REQ                              57
#define SSWRP_AOSS_AOSS_AP_INTR_VM2_RESP                             58
#define SSWRP_AOSS_AOSS_AP_INTR_VM3_REQ                              59
#define SSWRP_AOSS_AOSS_AP_INTR_VM3_RESP                             60
#define SSWRP_AOSS_AOSS_AP_INTR_HYP_REQ                              61
#define SSWRP_AOSS_AOSS_AP_INTR_HYP_RESP                             62
#define SSWRP_AOSS_AOSS_AP_INTR_KERNEL_REQ                           63
#define SSWRP_AOSS_AOSS_AP_INTR_KERNEL_RESP                          64
#define SSWRP_AOSS_AOSS_AP_INTR_NS_CPM_REQ_DBA                       65
#define SSWRP_AOSS_AOSS_AP_INTR_NS_CPM_RESP_DBA                      66
#define SSWRP_AOSS_AOSS_AP_INTR_S_CPM_REQ_DBA                        67
#define SSWRP_AOSS_AOSS_AP_INTR_S_CPM_RESP_DBA                       68
#define SSWRP_AOSS_AOSS_AP_INTR_VM1_REQ_DBA                          69
#define SSWRP_AOSS_AOSS_AP_INTR_VM1_RESP_DBA                         70
#define SSWRP_AOSS_AOSS_AP_INTR_VM2_REQ_DBA                          71
#define SSWRP_AOSS_AOSS_AP_INTR_VM2_RESP_DBA                         72
#define SSWRP_AOSS_AOSS_AP_INTR_VM3_REQ_DBA                          73
#define SSWRP_AOSS_AOSS_AP_INTR_VM3_RESP_DBA                         74
#define SSWRP_AOSS_AOSS_AP_INTR_HYP_REQ_DBA                          75
#define SSWRP_AOSS_AOSS_AP_INTR_HYP_RESP_DBA                         76
#define SSWRP_AOSS_AOSS_AP_INTR_KERNEL_REQ_DBA                       77
#define SSWRP_AOSS_AOSS_AP_INTR_KERNEL_RESP_DBA                      78
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_0_MBA_IRQ_0          79
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_0_MBA_IRQ_1          80
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_0_MBA_IRQ_2          81
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_1_MBA_IRQ_0          82
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_1_MBA_IRQ_1          83
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_CORE_1_MBA_IRQ_2          84
#define SSWRP_AURORA_AURDSP_AP_INTR_DSP_AP_WDOG_BITE_IRQ             85
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_0   86
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_1   87
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_2   88
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_3   89
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_4   90
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_ISP_NS_MCU_MBA_IRQ_5   91
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_0       92
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_1       93
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_2       94
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_3       95
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_4       96
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_5       97
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_6       98
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_7       99
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_8       100
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_9       101
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_10      102
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_11      103
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_12      104
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_13      105
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_14      106
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_15      107
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_16      108
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_17      109
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_18      110
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_19      111
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_20      112
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_21      113
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_22      114
#define SSWRP_AURORA_AURDSP_AP_INTR_NS_DSP_AP_VM_MCU_MBA_IRQ_23      115
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_ISP_TZ_MCU_MBA_IRQ_0    116
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_ISP_TZ_MCU_MBA_IRQ_1    117
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_ISP_TZ_MCU_MBA_IRQ_2    118
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_TZ_MCU_MBA_IRQ_0        119
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_TZ_MCU_MBA_IRQ_1        120
#define SSWRP_AURORA_AURDSP_AP_INTR_S_DSP_AP_TZ_MCU_MBA_IRQ_2        121
#define SSWRP_AURORA_AURDSP_GIA_OUT_AP                               122
#define SSWRP_AURORA_AURDSP_GIA_OUT_AP_NS_0                          123
#define SSWRP_AURORA_AURDSP_GIA_OUT_AP_NS_1                          124
#define SSWRP_AURORA_AURDSP_GIA_OUT_AP_S_0                           125
#define SSWRP_AURORA_AURDSP_GIA_OUT_AP_S_1                           126
#define SSWRP_BMSM_BMSM_AP_INTR_GROOT_MBA_CLIENT_IRQ                 127
#define SSWRP_BMSM_BMSM_AP_INTR_NS_GROOT_RFW_NS                      128
#define SSWRP_BMSM_BMSM_AP_INTR_NS_NS_DEBUG_STATE                    129
#define SSWRP_BMSM_BMSM_AP_INTR_NS_OTP_AP_NS_AGGR_IRQ                130
#define SSWRP_BMSM_BMSM_AP_INTR_S_GROOT_RFW_S                        131
#define SSWRP_BMSM_BMSM_AP_INTR_S_OTP_AP_S_AGGR_IRQ                  132
#define SSWRP_BMSM_BMSM_AP_INTR_S_S_DEBUG_STATE                      133
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_NS_C3P_VM0_IRQ                134
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_NS_C3P_VM1_IRQ                135
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_NS_C3P_VM2_IRQ                136
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_NS_C3P_VM3_IRQ                137
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_NS_JPU_IRQ                    138
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_TZ_C3P_VM0_IRQ                139
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_TZ_C3P_VM1_IRQ                140
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_TZ_C3P_VM2_IRQ                141
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_TZ_C3P_VM3_IRQ                142
#define SSWRP_CODEC_3P_CODEC3P_AP_INTR_TZ_JPU_IRQ                    143
#define SSWRP_CODEC_3P_CODEC3P_GIA_OUT_AP_NS                         144
#define SSWRP_CODEC_3P_CODEC3P_GIA_OUT_AP_TZ                         145
#define SSWRP_APC_GEM_DSU_0                                          146
#define SSWRP_APC_GEM_DSU_1                                          147
#define SSWRP_APC_GEM_DSU_2                                          148
#define SSWRP_APC_GEM_DSU_3                                          149
#define SSWRP_APC_NCLUSTERCRITIRQ                                    150
#define SSWRP_APC_NCLUSTERERRIRQ                                     151
#define SSWRP_APC_NCLUSTERFAULTIRQ                                   152
#define SSWRP_APC_NCLUSTERPMUIRQ                                     153
#define SSWRP_APC_NCMEERRIRQ                                         154
#define SSWRP_APC_NCMEFAULTIRQ                                       155
#define SSWRP_APC_NCOREERRIRQ_0                                      156
#define SSWRP_APC_NCOREERRIRQ_1                                      157
#define SSWRP_APC_NCOREERRIRQ_2                                      158
#define SSWRP_APC_NCOREERRIRQ_3                                      159
#define SSWRP_APC_NCOREERRIRQ_4                                      160
#define SSWRP_APC_NCOREERRIRQ_5                                      161
#define SSWRP_APC_NCOREERRIRQ_6                                      162
#define SSWRP_APC_NCOREFAULTIRQ_0                                    163
#define SSWRP_APC_NCOREFAULTIRQ_1                                    164
#define SSWRP_APC_NCOREFAULTIRQ_2                                    165
#define SSWRP_APC_NCOREFAULTIRQ_3                                    166
#define SSWRP_APC_NCOREFAULTIRQ_4                                    167
#define SSWRP_APC_NCOREFAULTIRQ_5                                    168
#define SSWRP_APC_NCOREFAULTIRQ_6                                    169
#define SSWRP_APC_NMPAMNSIRQ                                         170
#define SSWRP_APC_NMPAMSIRQ                                          171
#define SSWRP_APC_CAP_AP_NS_DOORBELL_IRQ                             172
#define SSWRP_APC_CAP_AP_NS_REQ_IRQ                                  173
#define SSWRP_APC_CAP_AP_NS_RSP_IRQ                                  174
#define SSWRP_APC_CAP_NON_TZ_IRQ                                     175
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_GCB_NS                       176
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_RAS_ERI_NS                   177
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_RAS_FHI_NS                   178
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_GCB_NS                       179
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_RAS_ERI_NS                   180
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_RAS_FHI_NS                   181
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_GCB_NS                       182
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_RAS_ERI_NS                   183
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_RAS_FHI_NS                   184
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_GCB_NS                       185
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_RAS_ERI_NS                   186
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_RAS_FHI_NS                   187
#define SSWRP_APC_U_TOWER_CI_PD0_NS_INTERRUPT_CPUACC                 188
#define SSWRP_APC_CAP_AP_S_DOORBELL_IRQ                              189
#define SSWRP_APC_CAP_AP_S_REQ_IRQ                                   190
#define SSWRP_APC_CAP_AP_S_RSP_IRQ                                   191
#define SSWRP_APC_CAP_TZ_IRQ                                         192
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_GCB_S                        193
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_MSF_FE_S                     194
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_MSF_TMP_S                    195
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_PMU_OVFLW_S                  196
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_RAS_ERI_S                    197
#define SSWRP_APC_U_TOWER_CI_MCN_0_IRPT_RAS_FHI_S                    198
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_GCB_S                        199
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_MSF_FE_S                     200
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_MSF_TMP_S                    201
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_PMU_OVFLW_S                  202
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_RAS_ERI_S                    203
#define SSWRP_APC_U_TOWER_CI_MCN_1_IRPT_RAS_FHI_S                    204
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_GCB_S                        205
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_MSF_FE_S                     206
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_MSF_TMP_S                    207
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_PMU_OVFLW_S                  208
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_RAS_ERI_S                    209
#define SSWRP_APC_U_TOWER_CI_MCN_2_IRPT_RAS_FHI_S                    210
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_GCB_S                        211
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_MSF_FE_S                     212
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_MSF_TMP_S                    213
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_PMU_OVFLW_S                  214
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_RAS_ERI_S                    215
#define SSWRP_APC_U_TOWER_CI_MCN_3_IRPT_RAS_FHI_S                    216
#define SSWRP_APC_U_TOWER_CI_PD0_INTERRUPT_CPUACC                    217
#define SSWRP_APC_TIMER0_INTR                                        218
#define SSWRP_APC_TIMER1_INTR                                        219
#define SSWRP_APC_TOWER_AP_INTR_0                                    220
#define SSWRP_APC_TOWER_AP_INTR_1                                    221
#define SSWRP_APC_TOWER_GDMC_AP_INTR_0                               222
#define SSWRP_APC_TOWER_GDMC_AP_INTR_1                               223
#define SSWRP_APC_U_WDT_TOP0_WDT_AP_INTR_CPUACC                      224
#define SSWRP_APC_CPU_AP_NS_INTR                                     226
#define SSWRP_APC_CPU_AP_S_INTR                                      228
#define SSWRP_DPU_DPU_GIA_OUT_AP_NS                                  229
#define SSWRP_DPU_DPU_GIA_OUT_AP_TZ                                  230
#define SSWRP_FABDISP_FABDISP_GIA_OUT_AP                             231
#define SSWRP_FABDISP_FABDISP_GIA_OUT_AP_NS_0                        232
#define SSWRP_FABDISP_FABDISP_GIA_OUT_AP_NS_1                        233
#define SSWRP_FABDISP_FABDISP_GIA_OUT_AP_S_0                         234
#define SSWRP_FABDISP_FABDISP_GIA_OUT_AP_S_1                         235
#define SSWRP_FABHBW_FABHBW_GIA_OUT_AP_NS                            236
#define SSWRP_FABHBW_FABHBW_GIA_OUT_AP_S                             237
#define SSWRP_FABMED_FABMED_GIA_OUT_AP                               238
#define SSWRP_FABMED_FABMED_GIA_OUT_AP_NS_0                          239
#define SSWRP_FABMED_FABMED_GIA_OUT_AP_NS_1                          240
#define SSWRP_FABMED_FABMED_GIA_OUT_AP_S_0                           241
#define SSWRP_FABMED_FABMED_GIA_OUT_AP_S_1                           242
#define SSWRP_FABSTBY_FABSTBY_GIA_OUT_AP                             243
#define SSWRP_FABSTBY_FABSTBY_GIA_OUT_AP_NS_0                        244
#define SSWRP_FABSTBY_FABSTBY_GIA_OUT_AP_NS_1                        245
#define SSWRP_FABSTBY_FABSTBY_GIA_OUT_AP_S_0                         246
#define SSWRP_FABSTBY_FABSTBY_GIA_OUT_AP_S_1                         247
#define SSWRP_FABSYSS_FABSYSS_GIA_OUT_AP_NS                          248
#define SSWRP_FABSYSS_FABSYSS_GIA_OUT_AP_S                           249
#define SSWRP_G2D_G2D_GIA_OUT_AP_NS                                  250
#define SSWRP_G2D_G2D_GIA_OUT_AP_TZ                                  251
#define SSWRP_GCV_GCV_AP_INTR_NS_CRE                                 252
#define SSWRP_GCV_GCV_AP_INTR_NS_GSW                                 253
#define SSWRP_GCV_GCV_GIA_OUT_AP_NS                                  254
#define SSWRP_GCV_GCV_GIA_OUT_AP_TZ                                  255
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP1_REQ                       256
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP1_REQ_DBA_IRQ               257
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP1_RESP                      258
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP1_RSP_DBA_IRQ               259
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP2_REQ                       260
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP2_REQ_DBA_IRQ               261
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP2_RESP                      262
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP2_RSP_DBA_IRQ               263
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP3_REQ                       264
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP3_REQ_DBA_IRQ               265
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP3_RESP                      266
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP3_RSP_DBA_IRQ               267
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_CRITICAL_REQ               268
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_CRITICAL_REQ_DBA_IRQ       269
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_CRITICAL_RESP              270
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_CRITICAL_RSP_DBA_IRQ       271
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_NON_SECURE_REQ             272
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_NON_SECURE_RESP            273
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_NS_REQ_DBA_IRQ             274
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_AP_NS_RSP_DBA_IRQ             275
#define SSWRP_DTA_GDMC_AP_INTR_NS_GDMC_WDT_IRQ                       276
#define SSWRP_DTA_GDMC_AP_INTR_S_GDMC_AP_S_REQ_DBA_IRQ               277
#define SSWRP_DTA_GDMC_AP_INTR_S_GDMC_AP_S_RESP_DBA_IRQ              278
#define SSWRP_DTA_GDMC_AP_INTR_S_GDMC_AP_SECURE_REQ                  279
#define SSWRP_DTA_GDMC_AP_INTR_S_GDMC_AP_SECURE_RESP                 280
#define SSWRP_DTA_GDMC_GIA_OUT_AP_NS                                 281
#define SSWRP_DTA_GDMC_GIA_OUT_AP_S                                  282
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_NS_RT1                            283
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_NS                                284
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_NS_ACS                            285
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_NS_RT0                            286
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_TZ                                287
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_TZ_ACS                            288
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_TZ_RT                             289
#define SSWRP_GMC0_GMC0_GIA_OUT_AP_IME_TZ                            290
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_NS_RT1                            291
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_NS                                292
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_NS_ACS                            293
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_NS_RT0                            294
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_TZ                                295
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_TZ_ACS                            296
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_TZ_RT                             297
#define SSWRP_GMC1_GMC1_GIA_OUT_AP_IME_TZ                            298
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_NS_RT1                            299
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_NS                                300
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_NS_ACS                            301
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_NS_RT0                            302
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_TZ                                303
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_TZ_ACS                            304
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_TZ_RT                             305
#define SSWRP_GMC2_GMC2_GIA_OUT_AP_IME_TZ                            306
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_NS_RT1                            307
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_NS                                308
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_NS_ACS                            309
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_NS_RT0                            310
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_TZ                                311
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_TZ_ACS                            312
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_TZ_RT                             313
#define SSWRP_GMC3_GMC3_GIA_OUT_AP_IME_TZ                            314
#define SSWRP_GPCA_GPCA_AP_INTR_GPCA_PD0_IRQ                         315
#define SSWRP_GPCA_GPCA_AP_INTR_GPCA_PD1_IRQ                         316
#define SSWRP_GPCA_GPCA_AP_INTR_GPCA_PD2_IRQ                         317
#define SSWRP_GPCA_GPCA_AP_INTR_GPCA_PD3_IRQ                         318
#define SSWRP_GPCA_GPCA_GIA_OUT_AP_NS                                319
#define SSWRP_GPCA_GPCA_GIA_OUT_AP_S                                 320
#define SSWRP_GPCM_AMB_GPCMAMB_GIA_OUT_AP_NS                         321
#define SSWRP_GPCM_AMB_GPCMAMB_GIA_OUT_AP_S                          322
#define SSWRP_GPCM_INFRA_GPCMINFRA_GIA_OUT_AP_NS                     323
#define SSWRP_GPCM_INFRA_GPCMINFRA_GIA_OUT_AP_S                      324
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_0                              325
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_1                              326
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_2                              327
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_3                              328
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_4                              329
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_5                              330
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_6                              331
#define SSWRP_GPU_GPU_AP_INTR_GPU_IRQ_7                              332
#define SSWRP_GPU_GPU_AP_INTR_GPU_WDT_IRQ                            333
#define SSWRP_GPU_GPU_GIA_OUT_AP_NS                                  334
#define SSWRP_GPU_GPU_GIA_OUT_AP_S                                   335
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_0                336
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_1                337
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_2                338
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_3                339
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_4                340
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_5                341
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_6                342
#define SSWRP_GSA_GSA_AP_INTR_MAILBOX_AP_CLIENT_IRQ_7                343
#define SSWRP_GSA_GSA_GIA_OUT_AP_NS                                  344
#define SSWRP_GSA_GSA_GIA_OUT_AP_S                                   345
#define SSWRP_HSIO_N_HSION_AP_INTR_N_0                               346
#define SSWRP_HSIO_N_HSION_AP_INTR_N_1                               347
#define SSWRP_HSIO_N_HSION_AP_INTR_N_2                               348
#define SSWRP_HSIO_N_HSION_AP_INTR_S_AP_S_MBOX_ACK                   349
#define SSWRP_HSIO_N_HSION_AP_INTR_S_AP_S_MBOX_DB                    350
#define SSWRP_HSIO_N_HSION_AP_INTR_S_AP_S_MBOX_REQ                   351
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_I2S                            352
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_NS_0                           353
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_NS_1                           354
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_NS_2                           355
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_NS_3                           356
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_S_0                            357
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_S_1                            358
#define SSWRP_HSIO_N_HSION_GIA_OUT_AP_S_2                            359
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_0                             360
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_1                             361
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_2                             362
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_3                             363
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_4                             364
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_5                             365
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_6                             366
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_7                             367
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_8                             368
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_9                             369
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_10                            370
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_11                            371
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_12                            372
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_13                            373
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_14                            374
#define SSWRP_HSIO_S_HSIOS_AP_INTR_UFS_15                            375
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_NS_0                           376
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_NS_1                           377
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_NS_2                           378
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_NS_3                           379
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_S_0                            380
#define SSWRP_HSIO_S_HSIOS_GIA_OUT_AP_S_1                            381
#define SSWRP_ISPBE_ISPBE_AP_INTR_NS_ISPBE                           382
#define SSWRP_ISPBE_ISPBE_AP_INTR_NS_MSA_HDR                         383
#define SSWRP_ISPBE_ISPBE_AP_INTR_NS_MSA_TNR                         384
#define SSWRP_ISPBE_ISPBE_GIA_OUT_AP_NS                              385
#define SSWRP_ISPBE_ISPBE_GIA_OUT_AP_TZ                              386
#define SSWRP_ISPFE_ISPFE_AP_INTR_NS_CORE0                           387
#define SSWRP_ISPFE_ISPFE_AP_INTR_NS_CORE1                           388
#define SSWRP_ISPFE_ISPFE_AP_INTR_NS_CORE2                           389
#define SSWRP_ISPFE_ISPFE_AP_INTR_NS_LITECORE0                       390
#define SSWRP_ISPFE_ISPFE_AP_INTR_NS_LITECORE1                       391
#define SSWRP_ISPFE_ISPFE_GIA_OUT_AP_NS                              392
#define SSWRP_ISPFE_ISPFE_GIA_OUT_AP_NS_CSISFE                       393
#define SSWRP_ISPFE_ISPFE_GIA_OUT_AP_TZ                              394
#define SSWRP_LSIOE_LSIOE_GIA_OUT_AP_NS_0                            395
#define SSWRP_LSIOE_LSIOE_GIA_OUT_AP_NS_1                            396
#define SSWRP_LSIOE_LSIOE_GIA_OUT_AP_NS_2                            397
#define SSWRP_LSIOE_LSIOE_GIA_OUT_AP_S_0                             398
#define SSWRP_LSIOE_LSIOE_GIA_OUT_AP_S_1                             399
#define SSWRP_LSIOS_LSIOS_AP_INTR_NS_LSIOS_UART3_INTR                400
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_NS_0                            401
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_NS_1                            402
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_NS_2                            403
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_NS_3                            404
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_NS_4                            405
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_S_0                             406
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_S_1                             407
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_S_2                             408
#define SSWRP_LSIOS_LSIOS_GIA_OUT_AP_S_3                             409
#define SSWRP_MEMSS_MEMSS_GIA_OUT_AP                                 410
#define SSWRP_MEMSS_MEMSS_GIA_OUT_AP_NS                              411
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NCP_MBA_AP_NS0_DB_IRQ             412
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NCP_MBA_AP_NS0_IRQ                413
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NCP_MBA_AP_NS1_DB_IRQ             414
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NCP_MBA_AP_NS1_IRQ                415
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS0_DB_IRQ             416
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS0_IRQ                417
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS1_DB_IRQ             418
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS1_IRQ                419
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS2_DB_IRQ             420
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS2_IRQ                421
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS3_DB_IRQ             422
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS3_IRQ                423
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS4_DB_IRQ             424
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS4_IRQ                425
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS5_DB_IRQ             426
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_MBA_AP_NS5_IRQ                427
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_0          428
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_1          429
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_2          430
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_3          431
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_4          432
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_5          433
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_6          434
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE0_MSI_CTRL_INT_VEC_7          435
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_0          436
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_1          437
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_2          438
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_3          439
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_4          440
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_5          441
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_6          442
#define SSWRP_PCIE_PCIE_AP_INTR_NS_PCIE1_MSI_CTRL_INT_VEC_7          443
#define SSWRP_PCIE_PCIE_AP_INTR_S_NCP_MBA_AP_S0_DB_IRQ               444
#define SSWRP_PCIE_PCIE_AP_INTR_S_NCP_MBA_AP_S0_IRQ                  445
#define SSWRP_PCIE_PCIE_AP_INTR_S_NCP_MBA_AP_S1_DB_IRQ               446
#define SSWRP_PCIE_PCIE_AP_INTR_S_NCP_MBA_AP_S1_IRQ                  447
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S0_DB_IRQ               448
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S0_IRQ                  449
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S1_DB_IRQ               450
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S1_IRQ                  451
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S2_DB_IRQ               452
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S2_IRQ                  453
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S3_DB_IRQ               454
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S3_IRQ                  455
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S4_DB_IRQ               456
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S4_IRQ                  457
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S5_DB_IRQ               458
#define SSWRP_PCIE_PCIE_AP_INTR_S_NEP_MBA_AP_S5_IRQ                  459
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_0           460
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_1           461
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_2           462
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_3           463
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_4           464
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_5           465
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_6           466
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE0_MSI_CTRL_INT_VEC_7           467
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_0           468
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_1           469
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_2           470
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_3           471
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_4           472
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_5           473
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_6           474
#define SSWRP_PCIE_PCIE_AP_INTR_S_PCIE1_MSI_CTRL_INT_VEC_7           475
#define SSWRP_PCIE_PCIE_GIA_OUT_AP_NS                                476
#define SSWRP_PCIE_PCIE_GIA_OUT_AP_S                                 477
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NCP_WDT_GDMC_IRQ                  478
#define SSWRP_PCIE_PCIE_AP_INTR_NS_NEP_WDT_GDMC_IRQ                  479
#define SSWRP_TPU_TPU_AP_INTR_NS_GRP0                                480
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_EL2_NS_IRQ             481
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_0           482
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_1           483
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_2           484
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_3           485
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_4           486
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_5           487
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_6           488
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_7           489
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_8           490
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_9           491
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_10          492
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_11          493
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_12          494
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_13          495
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_14          496
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_15          497
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_16          498
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_17          499
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_18          500
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_19          501
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_20          502
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_21          503
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_22          504
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_23          505
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_24          506
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_25          507
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_26          508
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_27          509
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_28          510
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_29          511
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_30          512
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_31          513
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_32          514
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_33          515
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_34          516
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_35          517
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_36          518
#define SSWRP_TPU_TPU_AP_INTR_NS_SSWRP_TPU_AP_NS_MBA_IRQ_37          519
#define SSWRP_TPU_TPU_AP_INTR_S_SSWRP_TPU_AP_EL2_S_IRQ               520
#define SSWRP_TPU_TPU_AP_INTR_TZ_SSWRP_TPU_AP_TZ_MBA_IRQ_0           521
#define SSWRP_TPU_TPU_AP_INTR_TZ_SSWRP_TPU_AP_TZ_MBA_IRQ_1           522
#define SSWRP_TPU_TPU_AP_INTR_TZ_SSWRP_TPU_AP_TZ_MBA_IRQ_2           523
#define SSWRP_TPU_TPU_AP_INTR_TZ_SSWRP_TPU_AP_TZ_MBA_IRQ_3           524
#define SSWRP_TPU_TPU_GIA_OUT_AP_NS_GRP0                             525
#define SSWRP_TPU_TPU_GIA_OUT_AP_S_GRP0                              526
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_0                 527
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_1                 528
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_2                 529
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_3                 530
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_4                 531
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_5                 532
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_6                 533
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_7                 534
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_8                 535
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_9                 536
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_10                537
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_11                538
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_12                539
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_13                540
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_14                541
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_APNS_MB_15                542
#define SSWRP_CPUACC_CPUACC_AP_INTR_S_SSU_APS_MB_0                   543
#define SSWRP_CPUACC_CPUACC_AP_INTR_S_SSU_APS_MB_1                   544
#define SSWRP_CPUACC_CPUACC_AP_INTR_S_SSU_APS_MB_2                   545
#define SSWRP_CPUACC_CPUACC_AP_INTR_S_SSU_APS_MB_3                   546
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_SSU_WD                    547
#define SSWRP_CPUACC_CPUACC_AP_INTR_NS_SSU_UART                      548
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_0_0                           549
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_0_1                           550
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_0_2                           551
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_0_3                           552
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_0_4                           553
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_NS_0                          554
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_NS_1                          555
#define SSWRP_CPUACC_CPUACC_GIA_OUT_AP_S                             556
#define SSWRP_APC_U_DEBUG_BLOCK_CTIIRQ_7                             557

#endif  /* _DT_BINDINGS_INTERRUPT_CONTROLLER_MBU_H */
