# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "rust_minimal",
    srcs = ["rust_minimal.rs"],
    out = "rust_minimal.ko",
    crate_root = "rust_minimal.rs",
    defconfig = "defconfig",
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
    ],
)
