import("//build_overrides/noa.gni")
import("$dir_noa_packages/noa_common/sim/ncp/wlan_fw/wlan_service.gni")

wlan_source_set("chip_brcm") {
  public_deps = [
    ":headers",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
  deps = [
    "$dir_noa_drivers/hwio",
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/modules/wlan_ring:wlan_ring",
    "$dir_wlan_fw/sys_if:interrupt",
    "$dir_wlan_fw/sys_if:io",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [
    "$dir_wlan_fw/wdev_if/chip/brcm4390/wdev_if_chip_brcm_4390.cc",
    "$dir_wlan_fw/wdev_if/chip/fake_brcm/wdev_if_chip_fake_brcm.cc",
  ]
}

wlan_source_set("chip_wcn") {
  public_deps = [
    ":headers",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
  deps = [
    "$dir_noa_drivers/hwio",
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/modules/wlan_ring:wlan_ring",
    "$dir_wlan_fw/sys_if:interrupt",
    "$dir_wlan_fw/sys_if:io",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [
    "$dir_wlan_fw/wdev_if/chip/wcn7760/wdev_if_chip_wcn_7760.cc",
  ]
}

wlan_source_set("hw_arch_brcm") {
  public_deps = [
    ":headers",
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
  deps = [
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/modules/wlan_buffer_management",
    "$dir_wlan_fw/sys_if:memory",
    "$dir_wlan_fw/wlan_debug_controller:wlan_debug_packet_sniffer",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [
    "$dir_wlan_fw/wdev_if/hw_arch/brcm/wdev_if_hw_arch_brcm.cc",
    "$dir_wlan_fw/wdev_if/hw_arch/brcm/wdev_if_hw_arch_brcm.h",
  ]
}

wlan_test("hw_arch_brcm_test") {
  # These tests are currently unsupported in the device unit test
  # environment due to limited memory resources.
  enable_if = current_os == "linux"
  sources = [ "$dir_wlan_fw/wdev_if/hw_arch/brcm/wdev_if_hw_arch_brcm_test.cc" ]
  deps = [
    ":hw_arch_brcm",
    "$dir_wlan_fw/modules/wlan_buffer_management",
  ]
}

wlan_source_set("hw_arch_wcn") {
  public_deps = [
    ":headers",
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
  deps = [
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/modules/wlan_buffer_management",
    "$dir_wlan_fw/sys_if:memory",
    "$dir_wlan_fw/wlan_debug_controller:wlan_debug_packet_sniffer",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [
    "$dir_wlan_fw/wdev_if/hw_arch/wcn7760/wdev_if_hw_arch_wcn7760.cc",
    "$dir_wlan_fw/wdev_if/hw_arch/wcn7760/wdev_if_hw_arch_wcn7760.h",
  ]
}

wlan_source_set("wdev_if") {
  public_deps = [
    ":headers",
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw/ext_svc",
    "$dir_wlan_fw/modules/sta_table",
    "$dir_wlan_fw/modules/wlan_buffer_management",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
  deps = [
    ":chip_brcm",
    ":hw_arch_brcm",
    ":chip_wcn",
    ":hw_arch_wcn",
    "$dir_wlan_fw:wlan_cast",
    "$dir_wlan_fw/wlan_log",
  ]
  sources = [ "$dir_wlan_fw/wdev_if/wdev_if.cc" ]
}

wlan_source_set("headers") {
  public = [
    "$dir_wlan_fw/wdev_if/chip/brcm4390/wdev_if_chip_brcm_4390.h",
    "$dir_wlan_fw/wdev_if/chip/fake_brcm/wdev_if_chip_fake_brcm.h",
    "$dir_wlan_fw/wdev_if/hw_arch/brcm/brcm_msgbuf.h",
    "$dir_wlan_fw/wdev_if/hw_arch/brcm/wdev_if_hw_arch_brcm.h",
    "$dir_wlan_fw/wdev_if/wdev_if.h",
    "$dir_wlan_fw/wdev_if/chip/wcn7760/wdev_if_chip_wcn_7760.h",
    "$dir_wlan_fw/wdev_if/hw_arch/wcn7760/wcn7760_msgbuf.h",
    "$dir_wlan_fw/wdev_if/hw_arch/wcn7760/wdev_if_hw_arch_wcn7760.h",
  ]
  public_deps = [
    "$dir_wlan_fw:noa_desc",
    "$dir_wlan_fw/modules/sta_table",
    "$dir_wlan_fw/modules/wlan_buffer_management",
    "$dir_wlan_fw/sys_if:common",
    "$dir_wlan_fw/sys_if:types",
  ]
}

wlan_test("wdev_if_test") {
  # These tests are currently unsupported in the device unit test
  # environment due to limited memory resources.
  enable_if = current_os == "linux" &&
              pw_unit_test_BACKEND == "$dir_pigweed/pw_unit_test:googletest"
  sources = [ "$dir_wlan_fw/wdev_if/wdev_if_test.cc" ]
  deps = [ ":wdev_if" ]
}

wlan_test_group("tests") {
  tests = [
    ":wdev_if_test",
    ":hw_arch_brcm_test",
  ]
}
