/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Google LWIS MALIBU ISP_GCV_PIPE Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_GCV_PIPE_H_
#define DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_GCV_PIPE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define ISP_GCV_PIPE_GSW_PIPE_BATCH_DONE_IRQ_BASE (HW_EVENT_MASK + 0)

#define ISP_GCV_PIPE_GSW_PIPE_BATCH_DONE_IRQ_GSW_PIPE_BATCH_DONE 0



#define ISP_GCV_PIPE_GSW_PIPE_RESET_DONE_IRQ_BASE (HW_EVENT_MASK + 32)

#define ISP_GCV_PIPE_GSW_PIPE_RESET_DONE_IRQ_GSW_PIPE_RESET_DONE 0



#define ISP_GCV_PIPE_CRE_PIPE_BATCH_DONE_IRQ_BASE (HW_EVENT_MASK + 64)

#define ISP_GCV_PIPE_CRE_PIPE_BATCH_DONE_IRQ_CRE_PIPE_BATCH_DONE 0



#define ISP_GCV_PIPE_CRE_PIPE_RESET_DONE_IRQ_BASE (HW_EVENT_MASK + 96)

#define ISP_GCV_PIPE_CRE_PIPE_RESET_DONE_IRQ_CRE_PIPE_RESET_DONE 0




/* clang-format on */


#define LWIS_PLATFORM_EVENT_ID_ISP_GCV_PIPE_GSW_PIPE_BATCH_DONE_IRQ_GSW_PIPE_BATCH_DONE \
	EVENT_ID(ISP_GCV_PIPE_GSW_PIPE_BATCH_DONE_IRQ_BASE, \
		 ISP_GCV_PIPE_GSW_PIPE_BATCH_DONE_IRQ_GSW_PIPE_BATCH_DONE)



#define LWIS_PLATFORM_EVENT_ID_ISP_GCV_PIPE_GSW_PIPE_RESET_DONE_IRQ_GSW_PIPE_RESET_DONE \
	EVENT_ID(ISP_GCV_PIPE_GSW_PIPE_RESET_DONE_IRQ_BASE, \
		 ISP_GCV_PIPE_GSW_PIPE_RESET_DONE_IRQ_GSW_PIPE_RESET_DONE)



#define LWIS_PLATFORM_EVENT_ID_ISP_GCV_PIPE_CRE_PIPE_BATCH_DONE_IRQ_CRE_PIPE_BATCH_DONE \
	EVENT_ID(ISP_GCV_PIPE_CRE_PIPE_BATCH_DONE_IRQ_BASE, \
		 ISP_GCV_PIPE_CRE_PIPE_BATCH_DONE_IRQ_CRE_PIPE_BATCH_DONE)



#define LWIS_PLATFORM_EVENT_ID_ISP_GCV_PIPE_CRE_PIPE_RESET_DONE_IRQ_CRE_PIPE_RESET_DONE \
	EVENT_ID(ISP_GCV_PIPE_CRE_PIPE_RESET_DONE_IRQ_BASE, \
		 ISP_GCV_PIPE_CRE_PIPE_RESET_DONE_IRQ_CRE_PIPE_RESET_DONE)



#endif /* DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_GCV_PIPE_H_ */
