/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Google LWIS MALIBU ISP_BE_MSA_HDR Interrupt And Event Defines
 *
 * Copyright (c) 2024 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_MSA_HDR_H_
#define DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_MSA_HDR_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE (HW_EVENT_MASK + 0)

#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_RESET_DONE 0
#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_INPUT_FLUSH_DONE 1
#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_MODE 2
#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_APB_GKP_ERR 3
#define ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_AXI_GKP_ERR 4



#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE (HW_EVENT_MASK + 32)

#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_PREV_L15_RDMA_AXI_ERR 0
#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_CURR_L15_RDMA_AXI_ERR 1
#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_O_LMV_WDMA_AXI_ERR 2
#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_START_OF_FRAME 3
#define ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_FRAME_DONE 4

/* clang-format on */


#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_MODE \
	EVENT_ID(ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_RSTCTL_AP_IRQ_AXI_GKP_ERR)



#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_PREV_L15_RDMA_AXI_ERR \
	EVENT_ID(ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_PREV_L15_RDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_CURR_L15_RDMA_AXI_ERR \
	EVENT_ID(ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_I_CURR_L15_RDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_O_LMV_WDMA_AXI_ERR \
	EVENT_ID(ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_MSA_O_LMV_WDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_START_OF_FRAME \
	EVENT_ID(ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_START_OF_FRAME)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_FRAME_DONE \
	EVENT_ID(ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_BASE, \
		 ISP_BE_MSA_HDR_FRAMECTL_AP_IRQ_FRAME_DONE)

#endif /* DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_MSA_HDR_H_ */
