/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Google LWIS MALIBU ISP_BE_ITCC Interrupt And Event Defines
 *
 * Copyright (c) 2025 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_ITCC_H_
#define DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_ITCC_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 0)

#define ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 32)

#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 64)

#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 96)

#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 128)

#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE (HW_EVENT_MASK + 160)

#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 192)

#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE (HW_EVENT_MASK + 224)

#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 256)

#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 288)

#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL 0
#define ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL 1



#define ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 640)

#define ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_1_AP_IRQ_BASE (HW_EVENT_MASK + 672)

#define ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 704)

#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L3_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 736)

#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L4_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 768)

#define ISP_BE_ITCC_YUV_LFNR_I_VAR_L4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 800)

#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_1_AP_IRQ_BASE (HW_EVENT_MASK + 832)

#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL3_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 864)

#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL4_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 896)

#define ISP_BE_ITCC_YUV_LFNR_I_YUV_GL4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0



#define ISP_BE_ITCC_YUV_PFR_I_Y_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE (HW_EVENT_MASK + 928)

#define ISP_BE_ITCC_YUV_PFR_I_Y_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR 0

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_PFRP_O_Y_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_VAR_L4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_Y_GL0_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL2_WDMA_PRODUCER_ITCC_1_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL3_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                             \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_CMD_CREDIT_FULL)
#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL \
	EVENT_ID(ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_BASE,                              \
		 ISP_BE_ITCC_BTR2_TNR_O_YUV_GL4_WDMA_PRODUCER_ITCC_0_AP_IRQ_CFG_DATA_CREDIT_FULL)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_1_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_GU_I_Y_GL0_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_VAR_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_VAR_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_VAR_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_VAR_L3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_VAR_L3_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_VAR_L3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_VAR_L4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_VAR_L4_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_VAR_L4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_1_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_YUV_GL2_RDMA_CONSUMER_ITCC_1_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_YUV_GL3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_YUV_GL3_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_YUV_GL3_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_LFNR_I_YUV_GL4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_LFNR_I_YUV_GL4_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_LFNR_I_YUV_GL4_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#define LWIS_PLATFORM_EVENT_ID_ISP_BE_ITCC_YUV_PFR_I_Y_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR \
	EVENT_ID(ISP_BE_ITCC_YUV_PFR_I_Y_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_BASE,                 \
		 ISP_BE_ITCC_YUV_PFR_I_Y_L2_RDMA_CONSUMER_ITCC_0_AP_IRQ_CFG_ERR)

#endif /* DT_BINDINGS_LWIS_PLATFORM_MALIBU_ISP_BE_ITCC_H_ */
