# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "pl330",
    out = "pl330.ko",
    conditional_srcs = {
        "CONFIG_PL330_DMA_GS": {
            True: [
                "pl330.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)

ddk_module(
    name = "samsung-dma",
    out = "samsung-dma.ko",
    conditional_srcs = {
        "CONFIG_SAMSUNG_DMADEV": {
            True: [
                "samsung-dma.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        ":pl330",
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)
