# SPDX-License-Identifier: GPL-2.0-only

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch", "ddk_headers", "ddk_uapi_headers")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

filegroup(
    name = "gs.dt-bindings",
    srcs = glob([
        "include/dt-bindings/**",
        "include/dtc/**",
    ]),
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_headers(
    name = "headers",
    hdrs = glob([
        # Standard pixel headers
        "include/**/*.h",
    ]),
    includes = [
        "include",
        "include/uapi",
    ],
)

ddk_headers(
    name = "gs_meminfo_headers",
    hdrs = [
        "include/soc/google/meminfo.h",
    ],
    includes = [
        "include",
    ],
    visibility = [
        "//private/google-modules/soc/rdo:__subpackages__",
    ],
)

ddk_uapi_headers(
    name = "misc_uapi_headers",
    srcs = [
        "include/uapi/misc/crashinfo.h",
    ],
    out = "misc-uapi-headers.tar.gz",
    kernel_build = "//private/devices/google/common:kernel",
    visibility = ["//private/devices/google:__subpackages__"],
)

ddk_uapi_headers(
    name = "exynos_uapi_headers",
    srcs = [
        "include/uapi/linux/videodev2_exynos_media.h",
    ],
    out = "exynos-uapi-headers.tar.gz",
    kernel_build = "//private/devices/google/common:kernel",
    visibility = ["//private/devices/google:__subpackages__"],
)
