# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "da9186-rtc",
    out = "da9186-rtc.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_DA9186_RTC": {
            True: [
                "da9186-rtc.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)

ddk_module(
    name = "da9188-rtc",
    out = "da9188-rtc.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_DA9188_RTC": {
            True: [
                "da9188-rtc.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/soc/rdo/ap-pmic:da9188-core",
    ],
)
