# SPDX-License-Identifier: GPL-2.0-only

load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "clk-cpm.kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/soc/rdo:__subpackages__",
    ],
)

ddk_module(
    name = "clk-cpm",
    out = "clk-cpm.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_CPM_CLK": {
            True: [
                "clk-cpm.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    local_defines = ["DYNAMIC_DEBUG_MODULE"],
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface",
    ] + select({
        "//private/devices/google/common:soc_is_malibu": [
            "//private/google-modules/soc/rdo/aoss-ssr-notifier:aoss_ssr_notifier",
        ],
        "//private/devices/google/common:soc_is_laguna": [
            "//private/google-modules/soc/rdo/aoss-ssr-notifier:aoss_ssr_notifier",
        ],
        "//conditions:default": [],
    }),
)
