#ifndef WLAN_SERVICE_PUCLIC_WLAN_SERVICE_RPC_PROTOCOL_H__
#define WLAN_SERVICE_PUCLIC_WLAN_SERVICE_RPC_PROTOCOL_H__

#include "sys_if/types/types.h"
#include "sys_if/common.h"

/// @def RING_MAX_NAME_LEN
/// Maximum length (in characters) for a ring name.
///
/// @brief Ring Name Maximum Length
#define RING_MAX_NAME_LEN 32

/// @def PRIORITY_CLASS_NUM
/// Number of priority classes supported.
///
/// @brief Priority Class Count
#define PRIORITY_CLASS_NUM 8

/// @def MAC_ADDR_LEN
/// Length (in bytes) of a MAC address.
///
/// @brief MAC Address Length
#define MAC_ADDR_LEN 6

/// @def MAX_SHELL_CMD_LEN
/// @brief Maximum length of a shell command string.
#define MAX_SHELL_CMD_LEN 128

/// @def MAX_SHELL_ARGV_LEN
/// @brief Maximum length of the shell argument vector.
#define MAX_SHELL_ARGV_LEN 128

/// @def MAX_TX_RING_NUM
/// @brief Maximum number of the TX flow rings.
#define MAX_TX_RING_NUM 40

/// @def MAX_NETWORK_BUF_NUM
/// @brief Maximum number of the network TX buffers.
#define MAX_NETWORK_BUF_NUM 4096

#define MAX_IRQ_NUM 8
#define MAX_WLAN_PCIE_MSI_NUM 1

#define MAXPRIO 7
#define NUMPRIO (MAXPRIO + 1)

/// @enum WlanCmdId
/// Represents the different types of WLAN commands.
///
/// @brief WLAN Command IDs
///
/// This enumeration defines the identifiers for various commands used to
/// interact with the NCP WLAN firmware.
///
/// @var kWlanCmdRxbmSync Command to synchronize receive
/// buffer manager (RXBM) information.
/// @var kWlanCmdFwInit Command to initialize the firmware.
/// @var kWlanCmdFwStart Command to start the firmware.
/// @var kWlanCmdFwExit Command to terminate the firmware.
/// @var kWlanCmdFwStop Command to stop the firmware.
/// @var kWlanCmdRingUpdate Command to update ring
/// configurations.
/// @var kWlanCmdTxRingActivate Command to activate the
/// transmit ring.
/// @var kWlanCmdStaActivate Command to activate a station.
/// @var kWlanCmdRegReceiver Command to register a receiver.
/// @var kWlanCmdIsrRegister Command to register an
/// interrupt service routine (ISR).
/// @var kWlanCmdTxbmSync Command to synchronize transmit
/// buffer manager (TXBM) information.
/// @var kWlanCmdRegClientDev Register a client device.
/// @var kWlanCmdDpModeCtrl Set DP mode.
/// @var kWlanCmdMockBmSyncDoorbell Synchronize the buffer info doorbell.
/// @var kWlanCmdLogSysCtrl Log system control.
/// @var kWlanCmdPacketSnifferCtrl Packet sniffer control.
/// @var kWlanCmdReportCtrl Report control.
/// @var kWlanCmdIdNum Indicates the maximum number of WLAN
/// @var kWlanCmdShellRequest Handle a shell request.
/// @var kWlanCmdPmStateNotify Host notifies the power state of dongle to fw.
/// command types.
typedef enum WlanCmdId {
	kWlanCmdIdStart = 0,
	kWlanCmdRxbmSync = kWlanCmdIdStart,
	kWlanCmdFwInit,
	kWlanCmdFwStart,
	kWlanCmdFwExit,
	kWlanCmdFwStop,
	kWlanCmdRingUpdate,
	kWlanCmdTxRingActivate,
	kWlanCmdStaActivate,
	kWlanCmdRegReceiver,
	kWlanCmdIsrRegister,
	kWlanCmdTxbmSync,
	kWlanCmdRegClientDev,
	kWlanCmdDpModeCtrl,
	kWlanCmdMockBmSyncDoorbell,
	kWlanCmdLogSysCtrl,
	kWlanCmdPacketSnifferCtrl,
	kWlanCmdShareInfoCtrl,
	kWlanCmdReportCtrl,
	kWlanCmdShellRequest,
	kWlanCmdPmStateNotify,
	kWlanCmdPacketSnifferReset,
	kWlanCmdUpdateUp2Flow,
	kWlanCmdUpdateFlowIdLookUpEntry,
	kWlanCmdRxHandoverSync,
	kWlanCmdIdEnd,
	kWlanCmdIdNum = kWlanCmdIdEnd,
} WlanCmdId;

/// @enum WlanEventType
/// Represents the different types of WLAN events.
///
/// @brief WLAN Event Types
///
/// This enumeration defines the various event types that
/// can be generated by the NCP WLAN FW.
///
/// @var kWlanEventTypeRingDoorbell Event indicating a
/// doorbell ring from the WLAN driver.
/// @var kWlanEventTypeRxbmSync Event signaling the need
/// to synchronize receive buffer manager (RXBM) information.
/// @var kWlanEventTypeTxcplSync Event for synchronizing
/// transmit completion (TXCPL) information.
/// @var kWlanEventTypeWakeup Event to wake up the system.
/// @var kWlanEventTypeMockRingDoorbellToApc Event used
/// for mocking a doorbell ring to the APC.
/// @var kWlanEventTypePmBusPower Event to request/release
/// the bus power.
/// @var kWlanEventTypePmDevicePower Event to request/release
/// the device power.
/// @var kWlanEventTypeMax Indicates the maximum number
/// of WLAN event types.
typedef enum WlanEventType {
	kWlanEventTypeRingDoorbell,
	kWlanEventTypeRxbmSync,
	kWlanEventTypeTxcplSync,
	kWlanEventTypeWakeup,
	kWlanEventTypeMockRingDoorbellToApc,
	kWlanEventTypePmBusPower,
	kWlanEventTypePmDevicePower,
	kWlanEventTypeCmdCompletion,
	kWlanEventTypePacketSnifferFull,
	kWlanEventTypeMax,
} WlanEventType;

/// @struct WlanCmdBmSyncInfo
/// Information about a single buffer in a WLAN command buffer
/// manager sync operation.
///
/// @brief WLAN Cmd Buffer Mgr Sync Info
///
/// Same as the `struct noa_bm_buf` in noa_wlan.h
///
/// @var pktid The packet ID associated with the buffer.
/// @var len The length of the buffer data.
/// @var pa The physical address of the buffer.
/// @var va The virtual address of the buffer.
typedef struct WlanCmdBmSyncInfo {
	uint16_t pktid;
	uint16_t len;
	uint64_t pa;
	uint64_t va;
} __attribute__((aligned(4))) WlanCmdBmSyncInfo;

/// @struct WlanCmdBmSyncHeader
/// Header for a WLAN command buffer manager sync operation.
///
/// @brief WLAN Cmd Buffer Mgr Sync Header
///
/// Same as the `struct noa_wlan_cmd_bm` in noa_wlan.h
///
/// @var buffer_count The number of WlanCmdBmSyncInfo entries
/// following this header.
/// @var to_dev The boolean value of request send to device.
/// @var info A flexible array member containing the buffer
/// information entries. The size of this array is determined
/// by `info_count`.
typedef struct WlanCmdBmSyncHeader {
	uint32_t buffer_count;
	bool to_dev;
	WlanCmdBmSyncInfo info[MAX_NETWORK_BUF_NUM];
} __attribute__((aligned(4))) WlanCmdBmSyncHeader;

typedef struct WlanMsiDesc {
	uint32_t nvec_used;
	uint16_t msi_index;
	uint32_t data;
} __attribute__((aligned(4))) WlanMsiDesc;

typedef struct WlanCmdIrqReuest {
	uint32_t irq_nums;
	uint32_t irqs[MAX_IRQ_NUM];
	WlanMsiDesc msi_descs[MAX_WLAN_PCIE_MSI_NUM];
} WlanCmdIrqRequest;

/// @struct WlanCmdFwInit
/// Parameters for initializing the WLAN firmware.
///
/// @brief WLAN Firmware Initialization Parameters
///
/// Same as the `struct noa_wlan_cmd_fw_init` in noa_wlan.h
///
/// @var rx_pkt_max Maximum number of receive packets supported.
/// @var tx_pkt_max Maximum number of transmit packets supported.
/// @var rx_buf_sz Size of the receive buffer.
/// @var tx_bm_sz Size of the transmit buffer manager.
/// @var chip_type Identifier for the specific WLAN chip type.
/// @var share_addr Physical address of the shared memory region.
/// @var share_size Size of the shared memory region.
typedef struct WlanCmdFwInit {
	uint32_t rx_pkt_max;
	uint32_t tx_pkt_max;
	uint32_t rx_buf_sz;
	uint32_t tx_bm_sz;
	uint32_t chip_type;
	uint64_t noa_shared_mem_addr;
	uint32_t noa_shared_mem_size;
} __attribute__((aligned(4))) WlanCmdFwInit;

/// @struct WlanCmdFwStart
/// Parameters for starting the WLAN firmware.
///
/// @brief WLAN Firmware Start Parameters
///
/// Same as the `struct noa_wlan_cmd_fw_start` in noa_wlan.h
///
/// @var share_addr Physical address of the shared memory region.
/// @var share_size Size of the shared memory region.
/// @var reg_addr Physical address of the register space.
/// @var reg_size Size of the register space.
/// @var ints_offset Offset to the interrupt status register.
/// @var intm_offset Offset to the interrupt mask register.
typedef struct WlanCmdFwStart {
	uint64_t share_addr;
	uint64_t share_size;
	uint64_t reg_addr;
	uint64_t reg_size;
	uint32_t ints_offset;
	uint32_t intm_offset;
} __attribute__((aligned(4))) WlanCmdFwStart;

typedef struct WlanCmdFwExit {
} WlanCmdFwExit;

typedef struct WlanCmdFwStop {
} WlanCmdFwStop;

/// @struct WlanCmdRingUpdateRegs
/// Information for updating WLAN ring registers.
///
/// @brief WLAN Ring Update Registers
///
/// Same as the `struct noa_ring_regs` in noa_hw_ring.h
///
/// @var base The starting address of the ring buffer.
/// @var len The size (in bytes) of each item in the ring buffer.
/// @var max_item The total number of slots in the ring buffer.
/// @var read The current read pointer (consumer's position).
/// @var write The current write pointer (producer's position).
typedef struct WlanCmdRingUpdateRegs {
	unsigned long base;
	unsigned long len;
	unsigned long max_item;
	unsigned long read;
	unsigned long write;
} __attribute__((aligned(4))) WlanCmdRingUpdateRegs;

/// @struct WlanCmdRingUpdateInfo
/// Information for updating a WLAN ring.
///
/// @brief WLAN Ring Update Information
///
/// Same as the `struct noa_wlan_ring_info` in noa_wlan.h
///
/// @var regs Register values associated with the ring.
/// @var ndesc Number of descriptors in the ring.
/// @var desc_size Size (in bytes) of each descriptor.
/// @var offset Offset value.
/// @var hw_idx Hardware index associated with the ring.
/// @var stride Stride value for the ring (element spacing).
/// @var name Null-terminated string representing the ring name.
/// @var dma_va (Driver mode simulator only) Virtual address for DMA.
/// @var dma_pa Physical address for DMA.
typedef struct WlanCmdRingUpdateInfo {
	WlanCmdRingUpdateRegs regs;
	uint32_t ndesc;
	uint32_t desc_size;
	uint32_t offset;
	uint8_t hw_idx;
	uint8_t stride;
	char name[RING_MAX_NAME_LEN];
	// driver mode simulator only
	uint64_t dma_va;
	uint64_t dma_pa;
} __attribute__((aligned(4))) WlanCmdRingUpdateInfo;

/// @struct WlanCmdRingUpdateHeader
/// Header for a WLAN ring update command.
///
/// @brief WLAN Ring Update Command Header
///
/// Same as the `struct noa_wlan_cmd_ring_info` in noa_wlan.h
///
/// This structure provides metadata for a WLAN ring update command,
/// specifying the ring type, number of rings being updated, and
/// details about each ring.
///
/// @var ring_type The type of rings being updated.
/// @var ring_count The number of rings being updated.
/// @var info A flexible array member containing information
/// about each ring (`WlanCmdRingUpdateInfo`). The size of
/// this array is determined by `ring_count`.
typedef struct WlanCmdRingUpdateHeader {
	uint32_t ring_type;
	uint32_t ring_count;
	WlanCmdRingUpdateInfo info[MAX_TX_RING_NUM];
} __attribute__((aligned(4))) WlanCmdRingUpdateHeader;

/// @struct WlanCmdTxRingActivate
/// Parameters for activating/deactivating a WLAN TX ring.
///
/// @brief WLAN TX Ring Activation Parameters
///
/// @var ring_id ID of the TX ring pool to activate/deactivate.
/// @var enable True to activate, false to deactivate the TX ring pool.
typedef struct WlanCmdTxRingActivate {
	uint16_t ring_id;
	bool enable;
} WlanCmdTxRingActivate;

/// @struct WlanCmdStaActivate
/// Parameters for activating or deactivating a WLAN station.
///
/// @brief WLAN Station Activation Parameters
///
/// Same as the `struct StaInfo` in sta_table.h
///
/// @var oif Operating interface identifier.
/// @var bss_idx Basic Service Set (BSS) index.
/// @var qos_txq_map Array mapping priority classes to transmit
/// queues.
/// @var addr MAC address of the station.
/// @var encrypt_type Encryption type used for communication.
/// @var encap_type Encapsulation type used for data frames.
/// @var lmac_id Logical MAC identifier.
/// @var bmid Buffer manager ID associated with the station.
/// @var reserved1 Reserved for alignment.
/// @var search_idx Search index used for station lookup.
/// @var search_type Search type used for station lookup.
/// @var dscp_tid_map_id DSCP to Traffic Identifier (TID) map ID.
/// @var addry_en Flag to enable address Y.
/// @var addrx_en Flag to enable address X.
/// @var reserved2 Reserved for alignment.
/// @var enable Flag to enable or disable the station.
/// @var sta_id Station ID.
/// @var reserved3 Reserved for alignment.
typedef struct WlanCmdStaActivate {
	// DW 0
	uint32_t oif;
	// DW 1
	uint16_t bss_idx;
	uint16_t qos_txq_map[PRIORITY_CLASS_NUM];
	// DW 2/3
	uint8_t addr[MAC_ADDR_LEN];
	uint8_t encrypt_type : 4;
	uint8_t encap_type : 2;
	uint8_t lmac_id : 2;
	uint8_t bmid;
	uint8_t reserved1[2];
	// DW 4
	uint32_t search_idx : 20;
	uint32_t search_type : 2;
	uint32_t dscp_tid_map_id : 6;
	uint32_t addry_en : 1;
	uint32_t addrx_en : 1;
	uint32_t reserved2 : 2;
	// DW 5
	uint8_t enable;
	uint8_t sta_id;
	uint8_t sta_table_idx;
	uint8_t reserved3[1];
} __attribute__((packed, aligned(4))) WlanCmdStaActivate;

/// @brief WLAN Command for DP Modes
typedef enum WlanCmdDpMode {
	/// @brief Normal data path operation.
	kWlanCmdDpNormalMode = 0,
	/// @brief Force APC mode (utilize APC-NCP ring).
	kWlanCmdDpDirectApcMode,
	/// @brief Force feedthrough mode (bypass NET engine).
	kWlanCmdDpForceFeedthroughMode,
	/// @brief Force tethering mode.
	kWlanCmdDpForceTetheringMode,
	/// @brief Force all traffic to be forwarded to the network engine.
	kWlanCmdDpVpnForceFwdToNetEngineMode,
} WlanCmdDpMode;

/// @brief Control structure for setting the WLAN DP mode via commands.
typedef struct WlanCmdDpModeCtrl {
	WlanCmdDpMode mode;
} __attribute__((aligned(4))) WlanCmdDpModeCtrl;

/// @brief WLAN command for shell requests.
typedef struct WlanCmdShellRequest {
	/// @brief The shell command string
	char cmd[MAX_SHELL_CMD_LEN];
	/// @brief The number of arguments in the argv array.
	uint32_t argv_len;
	/// @brief The argument vector for the shell command.
	char argv[MAX_SHELL_ARGV_LEN];
} __attribute__((aligned(4))) WlanCmdShellRequest;

/// @brief WLAN command for host sends notification to fw about the dongle power
/// state changed.
typedef struct WlanCmdPmStateNotify {
	uint32_t power_state;
} __attribute__((aligned(4))) WlanCmdPmStateNotify;

/// @brief WLAN command completion event and result.
typedef struct WlanEventCmdCompletion {
	/// @brief The command id of completion.
	uint32_t cmd;
	/// @brief The command result.
	int32_t result;
} __attribute__((aligned(4))) WlanEventCmdCompletion;

typedef struct WlanCmdUpdateUp2Flow {
	uint8_t type;
	uint8_t table[NUMPRIO];
} __attribute__((aligned(4))) WlanCmdUpdateUp2Flow;

#endif /* WLAN_SERVICE_PUCLIC_WLAN_SERVICE_RPC_PROTOCOL_H__ */
