/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_BINDINGS_LPCM_CLOCK_MBU_H
#define __DT_BINDINGS_LPCM_CLOCK_MBU_H

/*
 * define LPCM's clock ID of different SSWRPs, should match CPM values
 */
#define DPU_DP0_PIX_CLK 0
#define DPU_DSI0_PIX_CLK 1
#define DPU_DSI1_PIX_CLK 2
#define DPU_DSI_PHY_CLK 3
#define DPU_BE_CLK 4
#define DPU_FE0_CLK 5
#define DPU_FE1_CLK 6

#define GPCM_HSION_PLL_DP_CLK 0

#define GPCM_DPU_CHNL_CLK 0
#define GPCM_ISPBE_CHNL_CLK 1
#define GPCM_GCV_CHNL_CLK 2
#define GPCM_ISPFE_CHNL_CLK 3
#define GPCM_ISPFE_SCAN_WORDCLKHS_CLK 4
#define GPCM_ISPFE_P2D6_400M_CLK 5
#define GPCM_ISPFE_P2D4_600M_CLK 6

#define HSION_USBC_STICKY_CLK 0
#define HSION_USBC_NON_STICKY_CLK 1
#define HSION_USBDP_USBDRD_REF_CLK 2
#define HSION_USBCTRLREF_CLK 3
#define HSION_USB2_PHY_RESET_CLK 4
#define HSION_USB3DP_PHY_RESET_CLK 5
#define HSION_USBDP_U3PHY_FW_CLK 6
#define HSION_USBDP_U2PHY_APB_CLK 7
#define HSION_USBDP_USBDRD_BUS_CLK 8
#define HSION_USBDP_TOP_CLK 9
#define HSIO_N_USB2AUX_CTRL_VAUX_STICKY_CLK 10
#define HSIO_N_USB2AUX_CTRL_VCC_NON_STICKY_CLK 11
#define HSIO_N_USB2AUX_PHY_RESET_CLK 12
#define HSIO_N_USBDP_USB2AUX_CTRL_BUS_CLK 13
#define HSIO_N_USBDP_USB2AUX_PHY_APB_CLK 14
#define HSIO_N_USBDP_USB2AUX_CTRL_REF_CLK 15
#define HSIO_N_USBDP_USB2AUX_SUSPEND_CLK 16

#define HSIO_N_USBDP_SCLK0_CLK 17
#define HSIO_N_SRESETN0_CLK 18
#define HSIO_N_USBDP_AUX16M_CLK 19
#define HSIO_N_VIDEO_0_CLK 20
#define HSIO_N_DP_PIXEL_0_CLK 21
#define HSIO_N_USBDP_PIXEL_0_CLK 22
#define HSIO_N_SW_PIXEL0CLK_VIDEOBUFF_RSTN_CLK 23
#define HSIO_N_USBDP_DPTOP_CLK 24
#define HSIO_N_CSR_CLK 25
#define HSIO_N_SDP_0_CLK 26
#define HSIO_N_TRNG_CLK 27
#define HSIO_N_PRESETN0_CLK 28
#define HSIO_N_HDCP22_CLK 29
#define HSIO_N_DP_VCC_CLK 30
#define HSIO_N_USBDP_ESM_CLK 31
#define HSIO_N_MAXI_CLK 32

#define HSIOS_GPIO_REF_CLK 0
#define HSIOS_MPHY_REF_CLK 1
#define HSIOS_UFS_CLK 2
#define HSIOS_CP_CORE_CLK 3
#define HSIOS_UFS_DEEP_H8_CLK 4

#define LSIO_S_PWM_CLK 0
#define LSIO_S_M0_CLK 1
#define LSIO_S_M1_CLK 2
#define LSIO_S_M2_CLK 3
#define LSIO_S_M3_CLK 4
#define LSIO_S_M4_CLK 5
#define LSIO_S_M5_CLK 6
#define LSIO_S_M6_CLK 7
#define LSIO_S_M7_CLK 8
#define LSIO_S_I2C_0_CLK 9
#define LSIO_S_I3C_0_CLK 10
#define LSIO_S_I2C_1_CLK 11
#define LSIO_S_I3C_1_CLK 12
#define LSIO_S_I2C_2_CLK 13
#define LSIO_S_I3C_2_CLK 14
#define LSIO_S_I2C_3_CLK 15
#define LSIO_S_I3C_3_CLK 16
#define LSIO_S_I2C_4_CLK 17
#define LSIO_S_I3C_4_CLK 18
#define LSIO_S_SPI_0_CLK 19
#define LSIO_S_UART_0_CLK 20
#define LSIO_S_SPI_1_CLK 21
#define LSIO_S_UART_1_CLK 22
#define LSIO_S_SPI_2_CLK 23
#define LSIO_S_UART_2_CLK 24
#define LSIO_S_SPI_3_CLK 25
#define LSIO_S_UART_3_CLK 26
#define LSIO_S_QSPI_CLK 27
#define LSIO_S_I2C_0_CFG_CLK 28
#define LSIO_S_I3C_0_CFG_CLK 29
#define LSIO_S_I2C_1_CFG_CLK 30
#define LSIO_S_I3C_1_CFG_CLK 31
#define LSIO_S_I2C_2_CFG_CLK 32
#define LSIO_S_I3C_2_CFG_CLK 33
#define LSIO_S_I2C_3_CFG_CLK 34
#define LSIO_S_I3C_3_CFG_CLK 35
#define LSIO_S_I2C_4_CFG_CLK 36
#define LSIO_S_I3C_4_CFG_CLK 37
#define LSIO_S_SPI_0_CFG_CLK 38
#define LSIO_S_UART_0_CFG_CLK 39
#define LSIO_S_SPI_1_CFG_CLK 40
#define LSIO_S_UART_1_CFG_CLK 41
#define LSIO_S_SPI_2_CFG_CLK 42
#define LSIO_S_UART_2_CFG_CLK 43
#define LSIO_S_SPI_3_CFG_CLK 44
#define LSIO_S_UART_3_CFG_CLK 45
#define LSIO_S_QSPI_CFG_CLK 46
#define LSIO_S_PWM_CFG_CLK 47
#define LSIO_S_GPIO_CLK 48

#define LSIO_E_I2C_0_CLK 0
#define LSIO_E_I3C_0_CLK 1
#define LSIO_E_I2C_1_CLK 2
#define LSIO_E_I3C_1_CLK 3
#define LSIO_E_I2C_2_CLK 4
#define LSIO_E_I3C_2_CLK 5
#define LSIO_E_I2C_3_CLK 6
#define LSIO_E_I3C_3_CLK 7
#define LSIO_E_I2C_4_CLK 8
#define LSIO_E_I3C_4_CLK 9
#define LSIO_E_SPI_0_CLK 10
#define LSIO_E_UART_0_CLK 11
#define LSIO_E_SPI_1_CLK 12
#define LSIO_E_UART_1_CLK 13
#define LSIO_E_I2C_0_CFG_CLK 14
#define LSIO_E_I3C_0_CFG_CLK 15
#define LSIO_E_I2C_1_CFG_CLK 16
#define LSIO_E_I3C_1_CFG_CLK 17
#define LSIO_E_I2C_2_CFG_CLK 18
#define LSIO_E_I3C_2_CFG_CLK 19
#define LSIO_E_I2C_3_CFG_CLK 20
#define LSIO_E_I3C_3_CFG_CLK 21
#define LSIO_E_I2C_4_CFG_CLK 22
#define LSIO_E_I3C_4_CFG_CLK 23
#define LSIO_E_SPI_0_CFG_CLK 24
#define LSIO_E_UART_0_CFG_CLK 25
#define LSIO_E_SPI_1_CFG_CLK 26
#define LSIO_E_UART_1_CFG_CLK 27
#define LSIO_E_GPIO_CLK 28

#define AOSS_PG_AMB_I2C0_APB_CLK 0
#define AOSS_PG_AMB_I3C0_APB_CLK 1
#define AOSS_PG_AMB_I3C1_APB_CLK 2
#define AOSS_PG_AMB_I3C2_APB_CLK 3
#define AOSS_PG_AMB_UART0_APB_CLK 4
#define AOSS_PG_AMB_UART1_APB_CLK 5
#define AOSS_PG_AMB_UART2_APB_CLK 6
#define AOSS_PG_AMB_UART3_APB_CLK 7
#define AOSS_PG_AMB_UART4_APB_CLK 8
#define AOSS_PG_AMB_UART5_APB_CLK 9
#define AOSS_PG_AMB_SPI0_APB_CLK 10
#define AOSS_PG_AMB_SPI1_APB_CLK 11
#define AOSS_PG_AMB_SPI2_APB_CLK 12
#define AOSS_PG_AMB_SPI3_APB_CLK 13
#define AOSS_PG_AMB_SPI4_APB_CLK 14
#define AOSS_PG_AMB_SPI5_APB_CLK 15
#define AOSS_PG_AMB_SPI6_APB_CLK 16
#define AOSS_PG_AMB_TSPI_APB_CLK 17
#define AOSS_PG_AMB_I2C0_PERI_CLK 18
#define AOSS_PG_AMB_I3C0_PERI_CLK 19
#define AOSS_PG_AMB_I3C1_PERI_CLK 20
#define AOSS_PG_AMB_I3C2_PERI_CLK 21
#define AOSS_PG_AMB_UART0_PERI_CLK 22
#define AOSS_PG_AMB_UART1_PERI_CLK 23
#define AOSS_PG_AMB_UART2_PERI_CLK 24
#define AOSS_PG_AMB_UART3_PERI_CLK 25
#define AOSS_PG_AMB_UART4_PERI_CLK 26
#define AOSS_PG_AMB_UART5_PERI_CLK 27
#define AOSS_PG_AMB_SPI0_PERI_CLK 28
#define AOSS_PG_AMB_SPI1_PERI_CLK 29
#define AOSS_PG_AMB_SPI2_PERI_CLK 30
#define AOSS_PG_AMB_SPI3_PERI_CLK 31
#define AOSS_PG_AMB_SPI4_PERI_CLK 32
#define AOSS_PG_AMB_SPI5_PERI_CLK 33
#define AOSS_PG_AMB_SPI6_PERI_CLK 34
#define AOSS_PG_AMB_TSPI_PERI_CLK 35

#define CPUACC_GPDMA0_CLK 0
#define CPUACC_GPDMA1_CLK 1
#define CPUACC_GPDMA2_CLK 2
#define CPUACC_GPDMA3_CLK 3
#define CPUACC_GPDMA4_CLK 4

#define CLK_PCIE_DPA_UART_CLK 10

#define CPU_SSWRP_TSS_CLK 0

#define CLK_HSIO_N_EBU_CORE 33

#endif /* __DT_BINDINGS_LPCM_CLOCK_MBU_H */
