// SPDX-License-Identifier: GPL-2.0-only
/*
 * LVM Device Abstraction Layer for NOA Mode
 *
 * Copyright (c) 2024 Google LLC.
 * Author: Henry Yen <henryyen@google.com>
 *
 * This file provides the glue logic between the WLAN driver and the
 * underlying NOA driver. It implements the platform bus operations,
 * including initialization, de-initialization, packet transmission,
 * reception, and control operations.
 */

#include <common/wlan_ring_id.h>
#include <ring_service/ring_mgmt/port.h>
#include <ring_service/ring_mgmt/ring_manager.h>
#include <wlan/noa_wlan_client.h>
#include <wlan/noa_wlan_mapper.h>
#include <wlan/noa_wlan_nep_helper.h>
#include <core/print.h>
#include <dal/wlan/api.h>
#include <drivers/wlan/format.h>
#include <drivers/wlan/interface.h>
#include <drivers/wlan/mcu.h>
#include <drivers/wlan/topbank.h>

enum lvm_mapper_pool_id {
	LVM_MAPPER_POOL_APC_RX,
	LVM_MAPPER_POOL_APC_TX,

	__LVM_MAPPER_POOL_MAX,
};

static struct noa_wlan_client *client;

/**
 * lvm_dal_txcpl_sync - Process TX completion messages from the WLAN firmware
 * @priv: Pointer to the WLAN data structure
 * @msg: Pointer to the TX completion message
 *
 * This function is called by the NOA driver to process TX completion
 * messages received from the WLAN firmware. It extracts the relevant
 * information from the message and passes it to the WLAN driver's
 * TX completion handling function.
 */
static void lvm_dal_txcpl_sync(void *priv, void *msg)
{
	struct wlan_data *data = priv;
	struct host_txbuf_cmpl *txcpl = msg;
	u32 tkid = txcpl->cmn_hdr.request_id;

	if (!data)
		return;

	noa_wlan_mapper_unmap_by_tkid(client, LVM_MAPPER_POOL_APC_TX, tkid);
	lvm_wlan_txcpl_process(data, txcpl);
}

/**
 * lvm_dal_isr - Interrupt Service Routine (ISR) for the WLAN driver
 * @irq: The interrupt request number
 *
 * This function is the ISR for the WLAN driver. It is called when
 * an interrupt is generated by the WLAN hardware. It invokes
 * the WLAN driver's ISR handler function.
 */
static void lvm_dal_isr(int irq)
{
	lvm_wlan_isr(irq, client->bus);
}

/**
 * struct client_ops_noa_mode - WLAN client operations for the DAL
 * @txcpl_sync: Function to process TX completion messages
 * @rxbm_sync: Function to synchronize RX buffer metadata
 * @rx_isr: Interrupt Service Routine (ISR) for RX events
 */
static struct noa_wlan_client_ops client_ops_noa_mode = {
	.txcpl_sync		= lvm_dal_txcpl_sync,
	.rx_isr			= lvm_dal_isr,
};

/**
 * lvm_dal_rxbm_sync - Synchronize RX buffer metadata with the NOA firmware
 * @priv: Pointer to the WLAN data structure
 * @count: The number of RX buffers to synchronize
 * @rxbm: An array of pointers to the RX buffers to synchronize
 *
 * This function synchronizes the RX buffer metadata with the NOA firmware.
 * It copies the buffer information from the provided array of RX buffers
 * to a temporary array of noa_bm_buf structures and then passes it to
 * the NOA driver.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_rxbm_sync(void *priv, u32 count, struct lvm_buffer **rxbm)
{
	struct wlan_data *data = priv;
	struct noa_bm_buf *bufs;
	struct noa_wlan_mapping_params params = {
		.contiguous	= true,
		.tkid_in_use	= true,
		.pool_id	= LVM_MAPPER_POOL_APC_RX,
	};
	int ret;
	int i;

	if (!data || !rxbm)
		return -EINVAL;

	bufs = kzalloc(count * sizeof(struct noa_bm_buf), GFP_KERNEL);
	if (!bufs)
		return -ENOMEM;

	/*
	 * Copy the allocated LVM buffer information to the temporary
	 * noa_bm_buf array
	 */
	for (i = 0; i < count; ++i) {
		bufs[i].pktid = rxbm[i]->tkid;
		bufs[i].len = rxbm[i]->data_len + WLAN_PKT_PAD;
		bufs[i].pa = (u64)rxbm[i]->data_pa - WLAN_PKT_PAD;
		bufs[i].apc_va = (u64)rxbm[i]->data_va - WLAN_PKT_PAD;

		params.cpu_addr = (void *)bufs[i].apc_va;
		params.size = bufs[i].len;
		params.tkid = bufs[i].pktid;

		ret = noa_wlan_mapper_remap(client, &params, &bufs[i].dpa_va);
		if (ret) {
			LVM_ERR("%s(): failed to remap address, err: %d\n",
				__func__, ret);
			continue;
		}
	}

	/* Synchronize the RX buffer metadata with the NOA firmware */
	noa_wlan_fw_rxbm_sync(client, bufs, count, true);
	kfree(bufs);

	return 0;
}

/**
 * lvm_dal_init - Initialize the WLAN DAL
 * @_dev: Pointer to the device structure
 * @priv: Pointer to the WLAN data structure
 *
 * This function initializes the WLAN DAL. It allocates and registers
 * a WLAN client with the WLAN driver, and initializes the client's
 * parameters based on the provided WLAN data structure.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_init(void *_dev, void *priv)
{
	struct device *dev = _dev;
	struct wlan_data *data = priv;
	const struct wlan_param *param;
	struct noa_wlan_mapping_setup setup = {
		.profile_num = 2,
		.profile = {
			{
				.pool_id = LVM_MAPPER_POOL_APC_RX,
				.tkid_range = data->param->rxbm.buf_num,
			},
			{
				.pool_id = LVM_MAPPER_POOL_APC_TX,
				.tkid_range = data->param->txbm.buf_num,
			},
		},
	};
	int ret;

	if (!dev || !data)
		return -EINVAL;

	/* Allocate a new WLAN client */
	client = noa_wlan_client_alloc(&client_ops_noa_mode);
	if (!client)
		return -ENOMEM;

	/* Initialize the client's parameters */
	param = data->param;
	client->dev = dev;
	client->bus = data;
	client->type = param->type;
	client->rx_pkt_max = param->rxbm.buf_num;
	client->tx_pkt_max = param->txbm.buf_num;
	client->rx_buf_sz = param->rxbm.buf_len - param->rxbm.head_len;
	client->tx_bm_sz = param->txbm.txbm_buf_num;

	lvm_dal_rxbm_sync_cb_register(lvm_dal_rxbm_sync);

	ret = noa_wlan_mapper_init(client, &setup);
	if (ret) {
		LVM_ERR("%s(): failed to init mapper, err: %d\n",
			__func__, ret);
		return -EINVAL;
	}

	/* Register the client with the NOA driver */
	return noa_wlan_client_register(client);
}

/**
 * lvm_dal_exit - De-initialize the WLAN DAL
 * @priv: Pointer to the WLAN data structure
 *
 * This function de-initializes the WLAN DAL. It unregisters and frees
 * the WLAN client.
 */
static void lvm_dal_exit(void *priv)
{
	/* Unregister the client from the NOA driver */
	noa_wlan_client_unregister(client);

	noa_wlan_mapper_deinit(client);

	/* Free the WLAN client */
	noa_wlan_client_free(client);

	lvm_dal_rxbm_sync_cb_register(NULL);

	client = NULL;
}

/**
 * __lvm_dal_ring_info_query - Query and populate WLAN ring information
 * @data: Pointer to the WLAN data structure
 * @info: Pointer to the WLAN ring information structure to populate
 * @ring_id: ID of the WLAN ring
 *
 * This function queries the WLAN ring information from the WLAN data
 * structure and populates the provided WLAN ring information structure.
 */
static void __lvm_dal_ring_info_query(struct wlan_data *data,
				      struct noa_wlan_ring_info *info,
				      u32 ring_id)
{
	struct noa_ring_regs *regs = &info->regs;
	struct wlan_ring *ring = data->ring[ring_id];

	/* Populate the ring register information */
	regs->base = (unsigned long)(ring->regbase_pa);
	regs->len = (unsigned long)(ring->regbase_pa + WLAN_RING_REG_LEN);
	regs->read = (unsigned long)(ring->regbase_pa + WLAN_RING_REG_READ);
	regs->write = (unsigned long)(ring->regbase_pa + WLAN_RING_REG_WRITE);
	regs->max_item = (unsigned long)(ring->regbase_pa + WLAN_RING_REG_NUM);

	regs = &info->cpu_regs;
	regs->base = (unsigned long)(ring->regbase_va);
	regs->len = (unsigned long)(ring->regbase_va + WLAN_RING_REG_LEN);
	regs->read = (unsigned long)(ring->regbase_va + WLAN_RING_REG_READ);
	regs->write = (unsigned long)(ring->regbase_va + WLAN_RING_REG_WRITE);
	regs->max_item = (unsigned long)(ring->regbase_va + WLAN_RING_REG_NUM);

	/* Populate the ring DMA information */
	info->dma_pa = (u64)ring->desc_pa;
	info->dma_va = (u64)ring->desc_va;
	info->ndesc = ring->desc_num;
	info->desc_sz = ring->desc_len;
	info->hw_idx = ring->hw_id;
	info->stride = 1;

	/* Copy the ring name */
	strncpy(info->name, ring->name, RING_MAX_NAME);
}

/**
 * lvm_dal_ring_info_query - Query and populate all WLAN ring information
 * @client: Pointer to the WLAN client structure
 *
 * This function queries and populates the information for all WLAN rings
 * associated with the WLAN client.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_ring_info_query(struct noa_wlan_client *client)
{
	struct wlan_data *data = client->bus;
	int i;

	if (!data)
		return -EINVAL;

	/* Query and populate RX data ring information */
	client->rx_flow_max = 1;
	__lvm_dal_ring_info_query(data, &client->rx_ring[0],
				  WLAN_RING_ID_RX_DATA0);

	/* Query and populate RX post ring information */
	client->rx_post_max = 1;
	__lvm_dal_ring_info_query(data, &client->rx_post_ring[0],
				  WLAN_RING_ID_RX_POST0);

	/* Query and populate TX data ring information */
	client->tx_flow_max = 2;
	for (i = 0; i < client->tx_flow_max; ++i)
		__lvm_dal_ring_info_query(data, &client->tx_ring[i],
					  WLAN_RING_ID_TX_DATA0 + i);

	/* Query and populate TX completion ring information */
	client->tx_cpl_flow_max = 1;
	__lvm_dal_ring_info_query(data, &client->tx_cpl_ring[0],
				  WLAN_RING_ID_TX_CPL0);

	return 0;
}

/**
 * lvm_dal_nep_rx_init - Initialize the NEP RX ring
 * @client: Pointer to the WLAN client structure
 * @ring: Pointer to the WLAN ring structure
 *
 * This function initializes the NEP RX ring by registering it with the
 * WLAN client and configuring its parameters.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_nep_rx_init(struct noa_wlan_client *client,
			       struct wlan_ring *ring)
{
	client->nep_rx_desc_sz = NOA_DESC_BASIC_BYTE;
	client->nep_rx_items = ring->desc_num;
	return 0;
}

static ssize_t lvm_dal_tx_write_payload(void *dest, size_t dest_len,
					const void *src, size_t src_len);

/**
 * lvm_dal_nep_tx_init - Initialize the NEP TX ring
 * @client: Pointer to the WLAN client structure
 * @ring: Pointer to the WLAN ring structure
 *
 * This function initializes the NEP TX ring by registering it with the
 * WLAN client and configuring its parameters.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_nep_tx_init(struct noa_wlan_client *client,
			       struct wlan_ring *ring)
{
	client->nep_tx_desc_sz = NOA_DESC_WLAN_TX_BRCM_BYTE;
	client->nep_tx_items = ring->desc_num;
	client->ops->write_payload = lvm_dal_tx_write_payload;
	return 0;
}

/**
 * lvm_dal_start - Start the WLAN DAL
 * @priv: Pointer to the WLAN data structure
 *
 * This function starts the WLAN DAL. It initializes the WLAN client's
 * ring information, starts the NOA firmware, and initializes the
 * NEP RX and TX rings.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_start(void *priv)
{
	struct wlan_data *data = priv;

	if (!data)
		return -EINVAL;

	/* Query and populate WLAN ring information */
	lvm_dal_ring_info_query(client);

	/* Set the WLAN client's register addresses */
	client->ints_addr = WLAN_TOP_REG_OUT_RING_ISR;
	client->intm_addr = WLAN_TOP_REG_OUT_RING_IMR;
	client->share_addr = 0x0;
	client->share_size = 0x0;
	client->reg_addr = data->param->reg.ncp_dev_base;
	client->reg_size = 0x40000;

	/* Initialize the NEP RX and TX rings */
	lvm_dal_nep_rx_init(client, data->ring[WLAN_RING_ID_RX_DATA0]);
	lvm_dal_nep_tx_init(client, data->ring[WLAN_RING_ID_TX_DATA0]);
	/* Start the NOA firmware */
	return noa_wlan_fw_start(client);
}

/**
 * lvm_dal_stop - Stop the WLAN DAL
 * @priv: Pointer to the WLAN data structure
 *
 * This function stops the WLAN DAL. It deactivates the NEP rings,
 * de-initializes the NEP RX and TX rings, and stops the NOA firmware.
 */
static void lvm_dal_stop(void *priv)
{
	/* Check if the WLAN client is already started */
	if (!test_bit(CLIENT_FLAG_START, &client->flags))
		return;

	/* Stop the NOA firmware */
	noa_wlan_fw_stop(client);
}

static int lvm_dal_request_irq(void *priv)
{
	struct wlan_data *data = priv;

	client->irqs[0] = data->irq.id;
	client->irq_nums = 1;
	return noa_wlan_irq_request(client);
}

/**
 * lvm_dal_desc_transform - Transform a TX descriptor for the WLAN driver
 * @client: Pointer to the WLAN client structure
 * @buf: Pointer to the buffer associated with the TX descriptor
 * @desc: Pointer to the TX descriptor to transform
 *
 * This function transforms a TX descriptor from the WLAN vendor format
 * to the NOA format. It extracts the necessary information from the
 * vendor descriptor and populates the NOA descriptor accordingly.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_desc_transform(struct noa_wlan_client *client, void *_buf,
				  struct host_txbuf_post *desc)
{
	struct pkt_info_cso *cso_info = &desc->pktinfo;
	struct noa_bcm_txd bcm_txd;
	struct noa_bcm_txd *txd = &bcm_txd;
	struct noa_desc *d = (struct noa_desc *)desc;
	struct lvm_buffer *buf = _buf;
	int ret;
	u8 *ext_data = &d->ext_data[0];
	u16 pkt_len = desc->data_len;
	u16 pkt_id = desc->cmn_hdr.request_id;

	struct noa_wlan_mapping_params params = {
		.cpu_addr	= buf->data_va,
		.size		= buf->data_len,
		.contiguous	= true,
		.tkid_in_use	= true,
		.pool_id	= LVM_MAPPER_POOL_APC_TX,
		.tkid		= pkt_id,
	};

	/*
	 * Extract the necessary information from the vendor descriptor
	 * and populate the NOA descriptor accordingly.
	 */
	txd->current_phase = desc->cmn_hdr.flags;
	txd->ext_flags = desc->ext_flags;
	txd->ring_id = 0;
	txd->flags = desc->flags;
	txd->ifidx = desc->cmn_hdr.if_id;
	txd->ethertype = *((u16 *)&desc->txhdr[12]);

	txd->ext_tag = cso_info->ver;
	txd->pkt_csum_type = cso_info->pkt_csum_type;
	txd->l3_hdr_len = cso_info->nwk_hdr_len;
	txd->l4_hdr_len = cso_info->trans_hdr_len;

	memset(d, 0, sizeof(struct noa_desc));
	d->ver = 0;
	d->dst = NoaRingPathIdConvert(kNoaNetworkInterfaceWlan, kNoaNetworkFlowHostToDevice,
				      kNoaWlanRingTxData);
	d->mode = NOAD_MODE_DATA;
	d->cp = 0;
	d->fk = 0;

	d->dp_low = desc->data_buf_addr & 0xFFFFFFFF;
	d->dp_high = (desc->data_buf_addr >> 32) & 0xFFFFFFFF;
	d->dl = pkt_len;
	d->tkid = pkt_id;
	d->ddone = 0;
	d->head_offset = 0;
	d->desc_type = NOA_DESC_WLAN_TX_BRCM;
	d->reason = FWD_REASON_FEEDTHROUGH;

	ret = noa_wlan_mapper_remap(client, &params, &d->dv);
	if (ret) {
		LVM_ERR("%s(): failed to remap address, err: %d\n", __func__, ret);
		return -EINVAL;
	}

	memcpy(ext_data, txd, sizeof(struct noa_bcm_txd));

	return 0;
}

/**
 * struct wlan_tx_args - Arguments for the WLAN TX payload write function
 * @client: Pointer to the WLAN client structure
 * @buf: Pointer to the buffer containing the packet data
 * @ifidx: Interface index for the packet
 */
struct wlan_tx_args {
	struct noa_wlan_client	*client;
	void			*buf;
	u32			ifidx;
};

/**
 * lvm_dal_tx_write_payload - Write the payload to a NEP TX descriptor
 * @dest: Pointer to the destination buffer
 * @dest_len: Length of the destination buffer
 * @src: Pointer to the source buffer
 * @src_len: Length of the source buffer
 *
 * This function writes the payload data to a NEP TX descriptor. It
 * first prepares the WLAN TX descriptor using the provided arguments
 * and then transforms it to the NOA format.
 *
 * Return: The number of bytes written on success, a negative error code
 * otherwise.
 */
static ssize_t lvm_dal_tx_write_payload(void *dest, size_t dest_len,
					const void *src, size_t src_len)
{
	const struct wlan_tx_args *args = (const struct wlan_tx_args *)src;
	struct wlan_data *data = args->client->bus;
	struct host_txbuf_post *txd = (struct host_txbuf_post *)dest;
	int ret;

	/* Prepare the WLAN TX vendor descriptor */
	ret = lvm_wlan_txd_prepare(data, args->buf, args->ifidx, txd);
	if (ret)
		return ret;

	/* Transform the WLAN TX vendor descriptor to the NOA format */
	ret = lvm_dal_desc_transform(args->client, args->buf, txd);

	return ret;
}

/**
 * lvm_dal_tx - Transmit a packet through the WLAN DAL
 * @priv: Pointer to the WLAN data structure
 * @buf: Pointer to the buffer containing the packet data
 * @ifidx: Interface index for the packet
 *
 * This function transmits a packet through the WLAN DAL. It constructs
 * a wlan_tx_args structure with the provided arguments and writes it
 * to the NEP TX ring.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_tx(void *priv, void *buf, u32 ifidx)
{
	const struct wlan_tx_args args = {
		.client		= client,
		.buf		= buf,
		.ifidx		= ifidx,
	};

	return noa_wlan_client_ring_write(client, &client->tx_data_ring.ring,
					  (void *)&args);
}

/**
 * lvm_dal_rx_replenish - Replenish RX buffers
 * @priv: Pointer to the WLAN data structure
 * @count: Number of RX buffers to replenish
 * @reuse_tkid: Whether to reuse the TKID
 *
 * This function replenishes RX buffers in the WLAN DAL. It calls the
 * WLAN driver's RX buffer allocation function to allocate new buffers.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_rx_replenish(void *priv, u32 count, bool reuse_tkid)
{
	struct wlan_data *data = priv;

	if (!data)
		return -EINVAL;

	/* Allocate new RX buffers given from WLAN driver */
	return lvm_wlan_rxpost_buf_alloc(data, count);
}

/**
 * lvm_dal_rx_cb - Callback function for processing received packets
 * @client: Pointer to the WLAN client structure
 * @msg: Pointer to the received message
 *
 * This function is called by the ring service when DAL iterates and
 * reads the NEP ring. Then it looks up the corresponding WLAN RX vendor
 * descriptor using the TKID from the received message and passes
 * the vendor descriptor to the WLAN driver's RX completion handling
 * function.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_rx_cb(struct noa_wlan_client *client, void **msg)
{
	struct wlan_data *data = client->bus;
	struct noa_desc *desc = *msg;
	struct lvm_buffer *buf;

	if (!data || !desc)
		return -EINVAL;

	noa_wlan_mapper_unmap_by_tkid(client, LVM_MAPPER_POOL_APC_RX, desc->tkid);

	/* Lookup the buffer using the TKID from the received packet message */
	buf = lvm_buffer_lookup(data->driver->rx_manager, desc->tkid);

	if (buf) {
		/*
		 * Shift the data section pointer forward to obtain the
		 * WLAN RX vendor descriptor and deliver it to WLAN driver
		 */
		*msg = (struct wlan_rxbuf_cmpl *)(buf->data_va - WLAN_PKT_PAD);
		lvm_wlan_rxcpl_process(data, *msg);
	}

	return 0;
}

/**
 * lvm_dal_rx - Receive packets through the WLAN DAL
 * @priv: Pointer to the WLAN data structure
 * @cnt: Pointer to store the number of packets received
 *
 * This function receives packets through the WLAN DAL. It reads packets
 * from the NEP RX ring and processes them using the lvm_dal_rx_cb
 * callback function.
 *
 * Return: True if there are more packets to receive, false otherwise.
 */
static bool lvm_dal_rx(void *priv, u32 *cnt)
{
	struct wlan_data *data = priv;
	noa_ring_consumer *nep_ring;
	int ret = 0;

	if (!client || !data)
		return false;

	nep_ring = &client->rx_data_ring.ring;

	if (noa_wlan_client_ring_is_empty(nep_ring))
		return false;

	/* Read packets from the NEP RX ring and process them */
	ret = noa_wlan_client_ring_read_loop(client, nep_ring, lvm_dal_rx_cb);
	if (ret < 0)
		goto out;

	*cnt = ret;

	/* Refill Rx buffers after packet reception */
	lvm_wlan_rxpost_process(data);

out:
	return !noa_wlan_client_ring_is_empty(nep_ring);
}

/**
 * lvm_dal_txq_active - Activate or deactivate a TX queue
 * @priv: Pointer to the WLAN data structure
 * @flowid: The ID of the TX queue to activate or deactivate
 * @enable: True to activate the TX queue, false to deactivate it
 *
 * This function activates or deactivates a TX queue in the NOA firmware.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_txq_active(void *priv, u16 flowid, bool enable)
{
	return noa_wlan_fw_txq_active(client, flowid, enable);
}

/**
 * lvm_dal_sta_active - Activate or deactivate a station
 * @priv: Pointer to the WLAN data structure
 * @info: Pointer to the station information structure
 * @enable: True to activate the station, false to deactivate it
 *
 * This function activates or deactivates a station in the NOA firmware.
 *
 * Return: 0 on success, a negative error code otherwise.
 */
static int lvm_dal_sta_active(void *priv, struct sta_info *info, bool enable)
{
	return noa_wlan_fw_sta_active(client, info, enable);
}

/**
 * lvm_dal_tx_cpl - Handle the TX completion
 * @priv: Pointer to the WLAN data structure
 * @cnt: Pointer to the number of TX completions
 *
 * This function handles the TX completion.
 *
 * Return: True if there are more TX completions to handle, false otherwise.
 */
static bool lvm_dal_tx_cpl(void *priv, u32 *cnt)
{
	return noa_wlan_fw_txcpl(client, cnt);
}

/**
 * google_bus_ops - Platform bus operations for the NOA mode
 *
 * This structure defines the platform bus operations for the NOA mode.
 * It is used by the WLAN driver to interact with the underlying hardware.
 */
struct platform_bus_ops google_bus_ops = {
	.init			= lvm_dal_init,
	.exit			= lvm_dal_exit,
	.start			= lvm_dal_start,
	.stop			= lvm_dal_stop,
	.request_irq		= lvm_dal_request_irq,
	.tx			= lvm_dal_tx,
	.tx_cpl			= lvm_dal_tx_cpl,
	.rx			= lvm_dal_rx,
	.rx_replenish		= lvm_dal_rx_replenish,
	.tx_queue_active	= lvm_dal_txq_active,
	.sta_active		= lvm_dal_sta_active,
};

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Henry Yen <henryyen@google.com>");
MODULE_DESCRIPTION("LVM Device Abstraction Layer for NOA Mode");
