/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2026 Google LLC.
 */

#ifndef __WWAN_DEFINES_H__
#define __WWAN_DEFINES_H__

#if IS_ENABLED(CONFIG_MTK_DATA_CPU_LOADING_OPTIMIZE)
#define CONFIG_DATA_CPU_LOADING_OPTIMIZE 1
#endif

#if IS_ENABLED(CONFIG_DATA_GRO_WITHOUT_NAPI_POLL)
#define CONFIG_DATA_GRO_WITHOUT_NAPI_POLL 1
#endif

#if IS_ENABLED(CONFIG_MTK_DATA_FEATURE_TEST)
#define CONFIG_MTK_DATA_FEATURE_TEST 1
#endif

#if IS_ENABLED(CONFIG_MTK_MEMLOG_EVENT_SUPPORT)
#define CONFIG_MTK_MEMLOG_EVENT_SUPPORT 1
#endif

#if IS_ENABLED(CONFIG_MTK_DATA_TEST)
#define CONFIG_DATA_TEST_MODE 1
#endif

#if IS_ENABLED(CONFIG_DEBUG_FS)
#define CONFIG_DEBUG_FS 1
#endif

#if IS_ENABLED(CONFIG_MTK_WWAN_PWRCTL_SUPPORT)
#define CONFIG_MTK_WWAN_PWRCTL_SUPPORT 1
#endif

#if IS_ENABLED(CONFIG_MTK_HOST_DRV_WWAN_SUPPORT)
#define CONFIG_MTK_HOST_DRV_WWAN_SUPPORT 1

#if IS_ENABLED(CONFIG_SUPPORT_RELAYFS)
#define CONFIG_SUPPORT_RELAYFS 1
#endif
#endif

#if IS_ENABLED(CONFIG_MTK_DEVLINK)
#define CONFIG_MTK_DEVLINK 1

#if IS_ENABLED(CONFIG_MTK_DEVLINK_COREDUMP_SUPPORT)
#define CONFIG_MTK_DEVLINK_COREDUMP_SUPPORT 1
#endif
#if IS_ENABLED(CONFIG_MTK_DEVLINK_LOGDUMP_SUPPORT)
#define CONFIG_MTK_DEVLINK_LOGDUMP_SUPPORT 1
#endif
#if IS_ENABLED(CONFIG_MTK_DEVLINK_FLASH_SUPPORT)
#define CONFIG_MTK_DEVLINK_FLASH_SUPPORT 1
#endif
#endif

#if IS_ENABLED(CONFIG_MTK_THINMD_SLT_ENABLE)
#define CONFIG_MTK_THINMD_SLT_ENABLE 1
#endif

#if IS_ENABLED(CONFIG_MTK_PCIE_LINK_ERR_DEBUG_SUPPORT)
#define CONFIG_MTK_PCIE_LINK_ERR_DEBUG_SUPPORT 1
#endif

#endif /* __WWAN_DEFINES_H__ */
