# SPDX-License-Identifier: GPL-2.0-only

# vendor mm module

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "vh_mm",
    srcs = glob([
        "**/*.h",
    ]),
    out = "vh_mm.ko",
    conditional_srcs = {
        "CONFIG_VH_MM": {
            True: [
                "cma.c",
                "filemap.c",
                "pixel_mm_hint.c",
                "vh_mm_init.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:deferred-free-helper",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:headers",
        "//private/google-modules/soc/gs/drivers/soc/google/vh:headers",
    ],
)
