# SPDX-License-Identifier: GPL-2.0-only

load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "gittool_test",
    size = "small",
    srcs = ["gittool_test.sh"],
    data = [
        "test_base.sh",
        "//private/devices/google/common/tools:gittool.sh",
        "//private/devices/google/common/tools:logging.sh",
    ],
)

sh_test(
    name = "logging_test",
    size = "small",
    srcs = ["logging_test.sh"],
    data = [
        "test_base.sh",
        "//private/devices/google/common/tools:logging.sh",
    ],
)

sh_test(
    name = "repotool_test",
    size = "small",
    srcs = ["repotool_test.sh"],
    data = [
        "test_base.sh",
        "//private/devices/google/common/tools:gittool.sh",
        "//private/devices/google/common/tools:logging.sh",
        "//private/devices/google/common/tools:repotool.sh",
    ],
)

test_suite(name = "tests")
