# SPDX-License-Identifier: GPL-2.0-only

# HW Random Number Generator (RNG) device drivers.

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

filegroup(
    name = "kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "exyswd-rng",
    out = "exyswd-rng.ko",
    conditional_srcs = {
        "CONFIG_HW_RANDOM_EXYNOS_SWD": {
            True: [
                "exyswd-rng.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)
