# SPDX-License-Identifier: GPL-2.0-or-later
load("//build/kernel/kleaf:kernel.bzl", "checkpatch", "ddk_headers", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

ddk_headers(
    name = "bcmdhd_headers",
    hdrs = glob([
        "**/*.h",
        "**/*.mk",
    ]) + [
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/wlan/wonder:wonder_headers",
    ],
    includes = [
        ".",
        "include",
    ],
)

ddk_module(
    name = "bcmdhd4390",
    srcs = glob(
        [
            "**/*.c",
            "**/*.h",
        ],
        exclude = [
            "bcm_l2_filter.c",
            "verhoeff_chksum.c",
            "dhd_custom_google.c",
            "dhd_custom_google_4383.c",
            "dhd_custom_google_4398.c",
            "dhd_custom_meson.c",
        ],
    ),
    out = "bcmdhd4390.ko",
    copts = [
        "-include",
        "dhd_defines.h",
        "-DBCMDHD=4390",
        "-I$(ROOT_DIR)/private/google-modules/soc/gs/include",
        "-Wno-date-time",
        "-Wno-missing-prototypes",
        "-Wno-parentheses-equality",
    ] + select({
        "//private/devices/google/common:factory_build": ["-DBCMDHD_FACTORY_BUILD"],
        "//conditions:default": [],
    }) + select({
        "//private/devices/google/common:soc_is_malibu": [
            "-include",
            "wlan_config.h",
        ],
        "//conditions:default": [],
    }),
    includes = [
        ".",
        "include",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        ":bcmdhd_headers",
        "//private/google-modules/soc/rdo/pci:google-pcie",
    ] + select({
        "//private/devices/google/common:soc_is_malibu": [
            "//private/google-modules/wlan/linux:cfg80211",
            "//private/google-modules/wlan/linux:wlan_linux_headers",
        ],
        "//conditions:default": [],
    }) + [
        "//private/google-modules/wlan/wonder",
    ],
)
