# SPDX-License-Identifier: GPL-2.0-only

load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "google-ra",
    out = "google-ra.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_RA": {
            True: [
                "google_ra.c",
            ],
        },
        "CONFIG_DEBUG_FS": {
            True: [
                "google_ra_debugfs.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)

ddk_module(
    name = "google-ra-test-client",
    out = "google-ra-test-client.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_RA_TEST_CLIENT": {
            True: [
                "google-ra-test-client.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)
