# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "gslc",
    srcs = glob([
        "**/*.h",
    ]),
    out = "gslc.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_SLC": {
            True: [
                "gslc_cpm_mba.c",
                "gslc_debugfs.c",
                "gslc_partition.c",
                "gslc_platform.c",
                "gslc_pt_ops.c",
                "gslc_regmap.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:slc_pt",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface",
    ],
)
