/* SPDX-License-Identifier: GPL-2.0 */
#ifndef PIXELMD_API_
#define PIXELMD_API_

#include <linux/ioctl.h>
#include <linux/types.h>

/*** Event sources ***/

/*
 * The "source" that produces events. To receive events generated by a source,
 * clients need to enable the source using PIXELMD_CMD_ENABLE_SOURCE.
 *
 * See documentation for each source to learn which events it generates.
 *
 * The values in this enum should be explicitly stated and be sequential.
 */
enum pixelmd_source {
	/*
	 * Test events (see PIXELMD_CMD_GENERATE_TEST_EVENT):
	 *  PIXELMD_EVENT_TEST
	 *  PIXELMD_EVENT_TEST_COOKIE
	 */
	PIXELMD_SOURCE_TEST_GENERATOR = 0,

	/* Generates PIXELMD_EVENT_KSWAPD_RECLAIM_* events. */
	PIXELMD_SOURCE_KSWAPD = 1,

	/* Generates PIXELMD_EVENT_LMKD_KILL events. */
	PIXELMD_SOURCE_LMKD = 2,

	PIXELMD_NUM_SOURCES
};

/*** Events ***/

/* Creates 32-bit event code combining event_id and payload_size. */
#define _PIXELMD_MAKE_EVENT(event_id, payload_size)                                  \
	((((__u32)(event_id) & _PIXELMD_EVENT_ID_MASK) << _PIXELMD_EVENT_ID_SHIFT) | \
	 ((__u32)(payload_size) & _PIXELMD_EVENT_PAYLOAD_SIZE_MASK)                  \
		 << _PIXELMD_EVENT_PAYLOAD_SIZE_SHIFT)

#define _PIXELMD_EVENT_ID_BITS 16
#define _PIXELMD_EVENT_ID_MASK ((1 << _PIXELMD_EVENT_ID_BITS) - 1)
#define _PIXELMD_EVENT_ID_SHIFT 16
#define _PIXELMD_EVENT_PAYLOAD_SIZE_BITS 8
#define _PIXELMD_EVENT_PAYLOAD_SIZE_MASK ((1 << _PIXELMD_EVENT_PAYLOAD_SIZE_BITS) - 1)
#define _PIXELMD_EVENT_PAYLOAD_SIZE_SHIFT 0

/*
 * Maximum size of an event payload (excluding the event header).
 *
 * This constant affects the kernel fifo size, so it must be kept small.
 * Events that do not fit into the fifo are dropped; there is no waiting logic
 * on the kernel side.
 */
#define PIXELMD_MAX_EVENT_PAYLOAD_SIZE 255
_Static_assert(PIXELMD_MAX_EVENT_PAYLOAD_SIZE == _PIXELMD_EVENT_PAYLOAD_SIZE_MASK,
	       "max payload size is out of sync with the mask");

/* Macros to create event codes. */
#define _PIXELMD_EVENT(event_id, payload_type) _PIXELMD_MAKE_EVENT(event_id, sizeof(payload_type))
#define _PIXELMD_EVENT_NO_PAYLOAD(event_id) _PIXELMD_MAKE_EVENT(event_id, 0)

/*
 * Defines the current version wire protocol.
 *
 * In the current version each event is written as a (packed) pixelmd_event_header
 * struct, optionally followed by event's payload (if the payload size is not 0).
 */
#define PIXELMD_PROTOCOL_VERSION 1

/*
 * The header that's written to the stream before the event's payload.
 */
struct pixelmd_event_header {
	/* Timestamp of the event. */
	__u64 timestamp_ns;

	/*
	 * Event's code (one of PIXELMD_EVENT_ constants below), which
	 * also includes the size of the payload that follows the header.
	 */
	__u32 event_code;
} __packed;

/*
 * Simple test event without a payload.
 * Generated using PIXELMD_CMD_GENERATE_TEST_EVENT.
 */
#define PIXELMD_EVENT_TEST _PIXELMD_EVENT_NO_PAYLOAD(10)

/*
 * Test event with a payload.
 * Generated using PIXELMD_CMD_GENERATE_TEST_EVENT.
 */
#define PIXELMD_EVENT_TEST_COOKIE _PIXELMD_EVENT(11, /* cookie */ __u32)

/*
 * Kswapd started reclaiming memory (called balance_pgdat()).
 */
#define PIXELMD_EVENT_KSWAPD_RECLAIM_START _PIXELMD_EVENT_NO_PAYLOAD(20)

/*
 * Kswapd stopped reclaiming memory (returned from balance_pgdat()).
 */
#define PIXELMD_EVENT_KSWAPD_RECLAIM_DONE _PIXELMD_EVENT_NO_PAYLOAD(21)

/*
 * Process killed by LMKD.
 */
struct pixelmd_lmkd_kill_event {
	/* PID of the killed process. */
	__s32 pid;
	/* UID of the killed process. */
	__u32 uid;
	/* OOM score adj of the killed process. */
	__s16 oom_score_adj;
} __packed;

#define PIXELMD_EVENT_LMKD_KILL _PIXELMD_EVENT(30, struct pixelmd_lmkd_kill_event)

/*** Commands ***/

/* Shortcuts to shorten the command definitions. */
#define _PIXELMD_IOC_MAGIC 'P'
#define _PIXELMD_IOR(nr, type) _IOR(_PIXELMD_IOC_MAGIC, nr, type)
#define _PIXELMD_IOW(nr, type) _IOW(_PIXELMD_IOC_MAGIC, nr, type)
#define _PIXELMD_IO(nr) _IO(_PIXELMD_IOC_MAGIC, nr)

/*
 * Command to retrieve information about the kernel module.
 */
#define PIXELMD_CMD_GET_MODULE_INFO _PIXELMD_IOR(10, struct pixelmd_module_info)

struct pixelmd_module_info {
	/* PIXELMD_PROTOCOL_VERSION the module was built with. */
	__u32 protocol_version;
};

/*
 * Command to enable the specific event source (one of PIXELMD_SOURCE_ values).
 */
#define PIXELMD_CMD_ENABLE_SOURCE _PIXELMD_IOW(20, /* source */ __u32)

/*
 * Command to disable the specific event source (one of PIXELMD_SOURCE_ values).
 */
#define PIXELMD_CMD_DISABLE_SOURCE _PIXELMD_IOW(30, /* source */ __u32)

/*
 * Command to generate a test event.
 *
 * The payload is a "cookie":
 *  If cookie is 0, PIXELMD_EVENT_TEST is generated,
 *  Otherwise PIXELMD_EVENT_TEST_COOKIE is generated, and includes the cookie.
 *
 * Note that clients need to enable PIXELMD_SOURCE_TEST_GENERATOR source to see
 * the generated events.
 */
#define PIXELMD_CMD_GENERATE_TEST_EVENT _PIXELMD_IOW(40, /* cookie */ __u32)

/*
 * Command to request LMKD to kill a process.
 *
 * This command sends a request to LMKD to kill a process. The killing happens
 * asynchronously after the command, and there is no guarantee that LMKD kills
 * anything at all. If LMKD does kill a process, it'll use VENDOR_KILL reason.
 *
 * The min_oom_score_adj param controls victim process selection - only processes
 * with OOM scores above the value will be considered for killing. The value
 * should be in [0, OOM_SCORE_ADJ_MAX) range.
 */
#define PIXELMD_CMD_LMKD_KILL _PIXELMD_IOW(50, /* min_oom_score_adj */ __u16)

/*
 * Command to wake up kswapd if it's not already running.
 *
 * Clients can watch PIXELMD_EVENT_KSWAPD_RECLAIM_* events to learn whether
 * kswapd is reclaiming.
 */
#define PIXELMD_CMD_NUDGE_KSWAPD _PIXELMD_IO(60)

#endif /* PIXELMD_API_ */
