# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "mba_old",
    srcs = glob([
        "**/*.h",
    ]) + [
        "mba_client.c",
        "mba_host.c",
        "mba_internal.c",
        "mba_platform.c",
    ],
    out = "mba_old.ko",
    copts = [
        "-Wno-error",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)
