# SPDX-License-Identifier: GPL-2.0-only

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch")
load("//private/devices/google/common/kleaf:device_build.bzl", "device_build", "gki_module", "intree_module")
load(":constants.bzl", "GS201_DEVICE_MODULE_OUTS", "GS201_DTBS", "GS201_MODULE_OUTS")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

device_build(
    name = "gs201_base",
    build_configs = ["build.config.gs201"],
    # keep sorted
    ddk_uapi_headers = [
        "//private/google-modules/aoc/alsa:uapi_headers",
        "//private/google-modules/display/samsung:uapi_headers",
        "//private/google-modules/soc/gs:exynos_uapi_headers",
        "//private/google-modules/soc/gs:misc_uapi_headers",
        "//private/google-modules/touch/common:uapi_headers",
        "//private/google-modules/video/gchips:uapi_headers",
    ],
    defconfig_fragments = ["gs201_defconfig"],
    kconfig_exts = ["Kconfig.ext.gs201"],
    # keep sorted
    kconfigs = [
        "//private/google-modules/aoc:aoc.kconfig",
        "//private/google-modules/aoc/alsa:alsa.kconfig",
        "//private/google-modules/aoc/usb:aoc.usb.kconfig",
        "//private/google-modules/bms/misc:bms-misc.kconfig",
        "//private/google-modules/display/common:common.kconfig",
        "//private/google-modules/display/samsung:display.samsung.kconfig",
        "//private/google-modules/fingerprint/goodix/fps_touch_handler:fps_touch_handler.kconfig",
        "//private/google-modules/power/mitigation:bcl.kconfig",
        "//private/google-modules/power/reset:reset.kconfig",
        "//private/google-modules/radio/samsung/s5300:cpif.kconfig",
        "//private/google-modules/soc/gs/drivers/bts:kconfig",
        "//private/google-modules/soc/gs/drivers/char/hw_random:kconfig",
        "//private/google-modules/soc/gs/drivers/clk/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/clocksource:kconfig",
        "//private/google-modules/soc/gs/drivers/cpufreq:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq-whi/google:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq/google:kconfig",
        "//private/google-modules/soc/gs/drivers/dma:kconfig",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:dmabuf-heaps-kconfig_group",
        "//private/google-modules/soc/gs/drivers/gpu/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/gpu/exynos/g2d:kconfig",
        "//private/google-modules/soc/gs/drivers/i2c/busses:kconfig",
        "//private/google-modules/soc/gs/drivers/iio:kconfig",
        "//private/google-modules/soc/gs/drivers/iio/power:kconfig",
        "//private/google-modules/soc/gs/drivers/input:kconfig",
        "//private/google-modules/soc/gs/drivers/input/keyboard:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc/vl53l1:kconfig",
        "//private/google-modules/soc/gs/drivers/iommu:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos/mfc:kconfig",
        "//private/google-modules/soc/gs/drivers/mfd:kconfig",
        "//private/google-modules/soc/gs/drivers/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump:sscoredump.kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc:kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc-whi:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/gs_perf_mon:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/lat_governors:kconfig",
        "//private/google-modules/soc/gs/drivers/phy/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/power:kconfig",
        "//private/google-modules/soc/gs/drivers/power/reset:kconfig",
        "//private/google-modules/soc/gs/drivers/pwm:kconfig",
        "//private/google-modules/soc/gs/drivers/regulator:kconfig",
        "//private/google-modules/soc/gs/drivers/rtc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/boot_control:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gcma:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gnssif_spi:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa.kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pa_kill:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pkvm-smc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/s2mpu:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/smra:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:kconfig",
        "//private/google-modules/soc/gs/drivers/spi:kconfig",
        "//private/google-modules/soc/gs/drivers/spmi:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/google:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/tty/serial:kconfig",
        "//private/google-modules/soc/gs/drivers/ufs:kconfig",
        "//private/google-modules/soc/gs/drivers/usb:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/dwc3:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/gadget:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/host:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:role-sw.kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:kconfig",
        "//private/google-modules/soc/gs/drivers/video/backlight:kconfig",
        "//private/google-modules/soc/gs/drivers/watchdog:kconfig",
        "//private/google-modules/touch/common:touch.common.kconfig",
        "//private/google-modules/touch/sec/legacy:sec.kconfig",
        "//private/google-modules/trusty:trusty.kconfig",
    ],
    # keep sorted
    kunit_modules = [
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw-kunit",
    ],
    # TODO: b/447013182 - Remove unused modules.
    # keep sorted
    system_dlkm_modules = [
        gki_module("drivers/android/binder/rust_binder.ko"),
        gki_module("drivers/block/virtio_blk.ko"),
        gki_module("drivers/bluetooth/btbcm.ko"),
        gki_module("drivers/bluetooth/btqca.ko"),
        gki_module("drivers/bluetooth/btsdio.ko"),
        gki_module("drivers/bluetooth/hci_uart.ko"),
        gki_module("drivers/char/hw_random/cctrng.ko"),
        gki_module("drivers/char/virtio_console.ko"),
        gki_module("drivers/gnss/gnss.ko"),
        gki_module("drivers/misc/open-dice.ko"),
        gki_module("drivers/misc/vcpu_stall_detector.ko"),
        gki_module("drivers/net/macsec.ko"),
        gki_module("drivers/net/mii.ko"),
        gki_module("drivers/net/ppp/bsd_comp.ko"),
        gki_module("drivers/net/ppp/ppp_deflate.ko"),
        gki_module("drivers/net/ppp/ppp_generic.ko"),
        gki_module("drivers/net/ppp/ppp_mppe.ko"),
        gki_module("drivers/net/ppp/pppox.ko"),
        gki_module("drivers/net/slip/slhc.ko"),
        gki_module("drivers/net/usb/aqc111.ko"),
        gki_module("drivers/net/usb/asix.ko"),
        gki_module("drivers/net/usb/ax88179_178a.ko"),
        gki_module("drivers/net/usb/cdc_eem.ko"),
        gki_module("drivers/net/usb/cdc_ether.ko"),
        gki_module("drivers/net/usb/cdc_ncm.ko"),
        gki_module("drivers/net/usb/r8152.ko"),
        gki_module("drivers/net/usb/r8153_ecm.ko"),
        gki_module("drivers/net/usb/rtl8150.ko"),
        gki_module("drivers/net/usb/usbnet.ko"),
        gki_module("drivers/net/wwan/wwan.ko"),
        gki_module("drivers/power/sequencing/pwrseq-core.ko"),
        gki_module("drivers/pps/pps_core.ko"),
        gki_module("drivers/ptp/ptp.ko"),
        gki_module("drivers/usb/class/cdc-acm.ko"),
        gki_module("drivers/usb/mon/usbmon.ko"),
        gki_module("drivers/usb/serial/ftdi_sio.ko"),
        gki_module("drivers/usb/serial/usbserial.ko"),
        gki_module("drivers/virt/halla/exynos-hvm.ko"),
        gki_module("drivers/virtio/virtio_balloon.ko"),
        gki_module("drivers/virtio/virtio_pci.ko"),
        gki_module("drivers/virtio/virtio_pci_legacy_dev.ko"),
        gki_module("drivers/virtio/virtio_pci_modern_dev.ko"),
        gki_module("fs/netfs/netfs.ko"),
        gki_module("kernel/kheaders.ko"),
        gki_module("lib/crypto/libarc4.ko"),
        gki_module("mm/zsmalloc.ko"),
        gki_module("net/6lowpan/6lowpan.ko"),
        gki_module("net/6lowpan/nhc_dest.ko"),
        gki_module("net/6lowpan/nhc_fragment.ko"),
        gki_module("net/6lowpan/nhc_hop.ko"),
        gki_module("net/6lowpan/nhc_ipv6.ko"),
        gki_module("net/6lowpan/nhc_mobility.ko"),
        gki_module("net/6lowpan/nhc_routing.ko"),
        gki_module("net/6lowpan/nhc_udp.ko"),
        gki_module("net/8021q/8021q.ko"),
        gki_module("net/9p/9pnet.ko"),
        gki_module("net/9p/9pnet_fd.ko"),
        gki_module("net/bluetooth/bluetooth.ko"),
        gki_module("net/bluetooth/hidp/hidp.ko"),
        gki_module("net/bluetooth/rfcomm/rfcomm.ko"),
        gki_module("net/ieee802154/6lowpan/ieee802154_6lowpan.ko"),
        gki_module("net/ieee802154/ieee802154.ko"),
        gki_module("net/ieee802154/ieee802154_socket.ko"),
        gki_module("net/l2tp/l2tp_core.ko"),
        gki_module("net/l2tp/l2tp_ppp.ko"),
        gki_module("net/mac802154/mac802154.ko"),
        gki_module("net/nfc/nfc.ko"),
        gki_module("net/rfkill/rfkill.ko"),
        gki_module("net/tipc/tipc.ko"),
        gki_module("net/tipc/tipc_diag.ko"),
        gki_module("net/vmw_vsock/vmw_vsock_virtio_transport.ko"),
    ],
    # keep sorted
    vendor_dlkm_modules = [
        intree_module("net/mac80211/mac80211.ko"),
        intree_module("net/wireless/cfg80211.ko"),
        # TODO(b/488894505): Make all modules sorted together after finding the root cause module.
        "//private/google-modules/soc/gs/drivers/iio/power:odpm-whi",
        "//private/google-modules/soc/gs/drivers/input/misc/vl53l1:stmvl53l1",
        "//private/google-modules/soc/gs/drivers/iommu:iovad-vendor-hooks",
        "//private/google-modules/soc/gs/drivers/mfd:slg51000-core",
        "//private/google-modules/soc/gs/drivers/mfd:slg51002-core",
        "//private/google-modules/soc/gs/drivers/pinctrl:pinctrl-slg51000",
        "//private/google-modules/soc/gs/drivers/pinctrl:pinctrl-slg51002",
        "//private/google-modules/soc/gs/drivers/pwm:pwm-exynos",
        "//private/google-modules/soc/gs/drivers/regulator:slg51000-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:slg51002-regulator",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:tzprot",
        "//private/google-modules/soc/gs/drivers/soc/google/smra",
        "//private/google-modules/soc/gs/drivers/usb/gadget/function:usb_f_etr_miu",
        # Sort soc/gs and other modules seperately
        "//private/google-modules/aoc:aoc_mbox_full_sdev",
        "//private/google-modules/bms:google-wlc",
        "//private/google-modules/bms:google_ccd",
        "//private/google-modules/bms:google_dock",
        "//private/google-modules/bms:hl7132",
        "//private/google-modules/bms:ln8282_regulator",
        "//private/google-modules/bms:ln8411",
        "//private/google-modules/bms:max77779-charger-i2c",
        "//private/google-modules/bms:max77779-fg-i2c",
        "//private/google-modules/bms:max77779-fwupdate",
        "//private/google-modules/bms:max77779-sp",
        "//private/google-modules/bms:max77779-sp-i2c",
        "//private/google-modules/bms:max77779-usecase",
        "//private/google-modules/bms:max77779-vimon",
        "//private/google-modules/bms:max77779-vimon-i2c",
        "//private/google-modules/bms:max77779_i2cm",
        "//private/google-modules/bms:max77779_i2cm_i2c",
        "//private/google-modules/bms:max77779_pmic_i2c",
        "//private/google-modules/bms:max77779_pmic_irq",
        "//private/google-modules/bms:max77779_pmic_pinctrl",
        "//private/google-modules/bms:max77779_pmic_sgpio",
        "//private/google-modules/bms:max77779_vdroop",
        "//private/google-modules/bms:rt9471_charger",
        "//private/google-modules/display/samsung/panel:panel-boe-nt37290",
        "//private/google-modules/display/samsung/panel:panel-common",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3fc3",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3fc3-p10",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc2",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc3",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc3-c10",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc4",
        "//private/google-modules/display/samsung/panel:panel-samsung-sofef01",
        "//private/google-modules/edgetpu/janeiro/drivers/edgetpu:edgetpu.janeiro",
        "//private/google-modules/fingerprint/goodix/fps_touch_handler",
        "//private/google-modules/fingerprint/goodix/gw9608:goodixfp",
        "//private/google-modules/gpu/mali_kbase:mali_kbase_driver",
        "//private/google-modules/gpu/mali_pixel",
        "//private/google-modules/gxp/gs201:gxp",
        "//private/google-modules/iif",
        "//private/google-modules/lwis:lwis.busan",
        "//private/google-modules/touch/common:goog_touch_interface",
        "//private/google-modules/video/gchips:bigwave",
    ],
    # keep sorted
    vendor_dlkm_modules_blocklisted = [
        "//private/google-modules/aoc:aoc_unit_test_dev",
        "//private/google-modules/gpu/mali_kbase/tests:mali_kutf",
        "//private/google-modules/gpu/mali_kbase/tests:mali_kutf_clk_rate_trace_test",
        "//private/google-modules/misc/sscoredump:sscoredump_sample_test",
        "//private/google-modules/misc/sscoredump:sscoredump_test",
        "//private/google-modules/soc/gs/drivers/video/backlight:rt4539_bl",
    ],
    # keep sorted
    vendor_ramdisk_modules = [
        gki_module("mm/zsmalloc.ko"),
        intree_module("drivers/gpu/drm/display/drm_display_helper.ko"),
        intree_module("drivers/i2c/i2c-dev.ko"),
        intree_module("drivers/misc/eeprom/at24.ko"),
        intree_module("drivers/perf/arm_dsu_pmu.ko"),
        intree_module("drivers/scsi/sg.ko"),
        intree_module("drivers/spi/spidev.ko"),
        intree_module("drivers/watchdog/softdog.ko"),
        # TODO(b/488894505): Make all modules sorted together after finding the root cause module.
        "//private/google-modules/soc/gs/drivers/block/zram:zcomp_cpu",
        "//private/google-modules/soc/gs/drivers/block/zram:zcomp_eh",
        "//private/google-modules/soc/gs/drivers/block/zram:zram_gs",
        "//private/google-modules/soc/gs/drivers/bts",
        "//private/google-modules/soc/gs/drivers/clk/gs:clk_exynos_gs",
        "//private/google-modules/soc/gs/drivers/clocksource:exynos_mct",
        "//private/google-modules/soc/gs/drivers/cpufreq:exynos-acme",
        "//private/google-modules/soc/gs/drivers/devfreq-whi/google:exynos_devfreq",
        "//private/google-modules/soc/gs/drivers/dma:pl330",
        "//private/google-modules/soc/gs/drivers/dma:samsung-dma",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:deferred-free-helper",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:page_pool",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps/samsung:samsung_dma_heap",
        "//private/google-modules/soc/gs/drivers/gpu/exynos/g2d",
        "//private/google-modules/soc/gs/drivers/i2c/busses:i2c-acpm",
        "//private/google-modules/soc/gs/drivers/i2c/busses:i2c-exynos5",
        "//private/google-modules/soc/gs/drivers/input:keycombo",
        "//private/google-modules/soc/gs/drivers/input:keydebug",
        "//private/google-modules/soc/gs/drivers/input:power_keydebug",
        "//private/google-modules/soc/gs/drivers/input/keyboard:s2mpg12-key",
        "//private/google-modules/soc/gs/drivers/iommu:exynos-pcie-iommu",
        "//private/google-modules/soc/gs/drivers/iommu:samsung-iommu-group",
        "//private/google-modules/soc/gs/drivers/iommu:samsung-secure-iova",
        "//private/google-modules/soc/gs/drivers/iommu:samsung_iommu",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos/mfc:exynos_mfc",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos/smfc",
        "//private/google-modules/soc/gs/drivers/mfd:s2mpg12-mfd",
        "//private/google-modules/soc/gs/drivers/mfd:s2mpg13-mfd",
        "//private/google-modules/soc/gs/drivers/mfd:s2mpg1x-gpio",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc-whi:pcie-exynos-gs",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc-whi:pcie-exynos-gs201-rc-cal",
        "//private/google-modules/soc/gs/drivers/performance/gs_perf_mon",
        "//private/google-modules/soc/gs/drivers/performance/lat_governors:gs_governor_memlat",
        "//private/google-modules/soc/gs/drivers/performance/lat_governors:gs_governor_utils",
        "//private/google-modules/soc/gs/drivers/phy/samsung:phy-exynos-mipi",
        "//private/google-modules/soc/gs/drivers/phy/samsung:phy-exynos-mipi-dsim",
        "//private/google-modules/soc/gs/drivers/phy/samsung:phy-exynos-usbdrd-super",
        "//private/google-modules/soc/gs/drivers/pinctrl/gs:pinctrl-exynos-gs",
        "//private/google-modules/soc/gs/drivers/power/reset:debug-reboot",
        "//private/google-modules/soc/gs/drivers/regulator:pmic_class",
        "//private/google-modules/soc/gs/drivers/regulator:s2mpg12-powermeter",
        "//private/google-modules/soc/gs/drivers/regulator:s2mpg12-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:s2mpg13-powermeter",
        "//private/google-modules/soc/gs/drivers/regulator:s2mpg13-regulator",
        "//private/google-modules/soc/gs/drivers/rtc:rtc-s2mpg12",
        "//private/google-modules/soc/gs/drivers/soc/google:bcm_dbg",
        "//private/google-modules/soc/gs/drivers/soc/google:dbgcore-dump",
        "//private/google-modules/soc/gs/drivers/soc/google:ect_parser",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-bcm_dbg-dump",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-cpuhp",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-cpupm",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-dm",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pd",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pd-dbg",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pd_el3",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pd_hsi0",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pm",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-pmu-if",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos-seclog",
        "//private/google-modules/soc/gs/drivers/soc/google:exynos_pm_qos",
        "//private/google-modules/soc/gs/drivers/soc/google:gs-chipid",
        "//private/google-modules/soc/gs/drivers/soc/google:hardlockup-debug",
        "//private/google-modules/soc/gs/drivers/soc/google:hardlockup-watchdog",
        "//private/google-modules/soc/gs/drivers/soc/google:kernel-top",
        "//private/google-modules/soc/gs/drivers/soc/google:sysrq-hook",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:acpm_flexpmu_dbg",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:acpm_mbox_test",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:gs_acpm",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:power_stats",
        "//private/google-modules/soc/gs/drivers/soc/google/cal-if:cmupmucal",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:debug-snapshot-debug-kinfo",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:dss",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:ehld",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:etm2dram",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-adv-tracer",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-adv-tracer-s2d",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-coresight",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-coresight-etm",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-debug-test",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:exynos-ecc-handler",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:itmon",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:pixel-boot-metrics",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:pixel-debug-test",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:pixel-suspend-diag",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:sjtag-driver",
        "//private/google-modules/soc/gs/drivers/soc/google/eh",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa_gsc",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa_ko",
        "//private/google-modules/soc/gs/drivers/soc/google/modemctl:google_modemctl",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat:pixel_stat_sysfs",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat/mm:pixel_stat_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/pkvm-s2mpu",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:slc_acpm",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:slc_dummy",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:slc_pmon",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:slc_pt",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:systrace",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/cgroup:vh_cgroup",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/fs:vh_fs",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/metrics:pixel_metrics",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/mm:vh_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/pixel_em",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:sched_tp",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_preemptirq_long",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_sched",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/thermal:vh_thermal",
        "//private/google-modules/soc/gs/drivers/spi:spi-s3c64xx",
        "//private/google-modules/soc/gs/drivers/thermal/google:s2mpg13_spmic_thermal",
        "//private/google-modules/soc/gs/drivers/thermal/samsung:gpu_cooling",
        "//private/google-modules/soc/gs/drivers/thermal/samsung:gs_thermal",
        "//private/google-modules/soc/gs/drivers/tty/serial:exynos_tty",
        "//private/google-modules/soc/gs/drivers/ufs:ufs-exynos-gs",
        "//private/google-modules/soc/gs/drivers/ufs:ufs-pixel-fips140",
        "//private/google-modules/soc/gs/drivers/usb/dwc3:dwc3-exynos-usb",
        "//private/google-modules/soc/gs/drivers/usb/gadget/function:usb_f_dm",
        "//private/google-modules/soc/gs/drivers/usb/gadget/function:usb_f_dm1",
        "//private/google-modules/soc/gs/drivers/usb/host:xhci-exynos",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:bc_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:google_tcpci_shim",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_helper",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77779_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max777x9_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max777x9_i2c",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usb_psy",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usbc_cooling_dev",
        "//private/google-modules/soc/gs/drivers/watchdog:s3c2410_wdt",
        # Sort soc/gs and other modules seperately
        "//private/google-modules/amplifiers/audiometrics",
        "//private/google-modules/aoc:aoc_channel_dev",
        "//private/google-modules/aoc:aoc_char_dev",
        "//private/google-modules/aoc:aoc_control_dev",
        "//private/google-modules/aoc:aoc_core",
        "//private/google-modules/aoc:aoc_tbn_service_dev",
        "//private/google-modules/aoc:aoc_uwb_platform_drv",
        "//private/google-modules/aoc:aoc_uwb_service_dev",
        "//private/google-modules/aoc:mailbox-wc",
        "//private/google-modules/aoc/alsa:aoc_alsa_dev",
        "//private/google-modules/aoc/alsa:aoc_alsa_dev_util",
        "//private/google-modules/aoc/usb:aoc_usb_driver",
        "//private/google-modules/aoc_ipc",
        "//private/google-modules/bms:google-battery",
        "//private/google-modules/bms:google-bms",
        "//private/google-modules/bms:google-charger",
        "//private/google-modules/bms:google-cpm",
        "//private/google-modules/bms:google_dual_batt_gauge",
        "//private/google-modules/bms:max1720x-battery",
        "//private/google-modules/bms:max20339",
        "//private/google-modules/bms:max77729-pmic",
        "//private/google-modules/bms:max77759-charger",
        "//private/google-modules/bms:max77779-charger",
        "//private/google-modules/bms:max77779-fg",
        "//private/google-modules/bms:max77779_pmic",
        "//private/google-modules/bms:p9221",
        "//private/google-modules/bms:pca9468",
        "//private/google-modules/bms/misc:gvotable",
        "//private/google-modules/bms/misc:logbuffer",
        "//private/google-modules/display/common/gs_drm:gs-drm-connector",
        "//private/google-modules/display/common/gs_panel:gs-panel",
        "//private/google-modules/display/samsung:exynos-drm",
        "//private/google-modules/display/samsung/panel:panel-samsung-drv",
        "//private/google-modules/display/samsung/panel:panel-samsung-emul",
        "//private/google-modules/power/mitigation:google_bcl",
        "//private/google-modules/power/mitigation:max77759_bcl_irq",
        "//private/google-modules/power/reset:pixel-reboot",
        "//private/google-modules/touch/common:heatmap",
        "//private/google-modules/touch/common:touch_bus_negotiator",
        "//private/google-modules/touch/common:touch_offload",
        "//private/google-modules/trusty:trusty-core",
        "//private/google-modules/trusty:trusty-ipc",
        "//private/google-modules/trusty:trusty-log",
        "//private/google-modules/trusty:trusty-test",
        "//private/google-modules/trusty:trusty-virtio",
    ],
)

device_build(
    name = "gs201",
    base_device = ":gs201_base",
    build_dtb = True,
    build_dtbo = True,
    build_system_dlkm = True,
    build_vendor_dlkm = True,
    build_vendor_kernel_boot = True,
    defconfig_fragments = [
        "//private/devices/google/felix:felix/defconfig_fragments",
        "//private/devices/google/lynx:lynx/defconfig_fragments",
        "//private/devices/google/pantah:pantah/defconfig_fragments",
        "//private/devices/google/tangorpro:tangorpro/defconfig_fragments",
    ],
    dtb_outs = GS201_DTBS,
    dts_makefile = "dts/Makefile",
    dts_srcs = glob(["dts/**"]) + [
        "//private/google-modules/soc/gs:gs.dt-bindings",
    ],
    ext_dtbos = [
        "//private/devices/google/felix:felix/dtbos",
        "//private/devices/google/lynx:lynx/dtbos",
        "//private/devices/google/pantah:pantah/dtbos",
        "//private/devices/google/tangorpro:tangorpro/dtbos",
    ],
    insmod_cfgs = glob(["insmod_cfg/*.cfg"]),
    module_outs = GS201_MODULE_OUTS + GS201_DEVICE_MODULE_OUTS,
    # keep sorted
    vendor_dlkm_modules = [
        "//private/devices/google/felix:felix/ext_modules",
        "//private/devices/google/lynx:lynx/ext_modules",
        "//private/devices/google/pantah:pantah/ext_modules",
        "//private/devices/google/tangorpro:tangorpro/ext_modules",
    ],
    # keep sorted
    vendor_dlkm_modules_blocklisted = [
        "//private/google-modules/amplifiers/cs40l26:cs40l26-i2c",
        "//private/google-modules/bluetooth/qcom:btpower",
        "//private/google-modules/fingerprint/fpc:fpc1020_platform_tee",
        "//private/google-modules/touch/common/usi:goog_usi_stylus",
        "//private/google-modules/touch/focaltech/ft3658:focal_touch",
        "//private/google-modules/touch/fts/fst2_p26:fst2",
        "//private/google-modules/touch/fts/ftm5",
        "//private/google-modules/touch/goodix:goodix_brl_touch",
        "//private/google-modules/touch/novatek/nt36xxx:nvt_touch",
        "//private/google-modules/touch/sec/p26:sec_touch",
        "//private/google-modules/touch/synaptics/syna_c10:syna_touch",
        "//private/google-modules/wlan/bcmdhd/bcm4389:bcmdhd4389",
        "//private/google-modules/wlan/syna/dhd43752p:synadhd",
    ],
    # keep sorted
    vendor_ramdisk_modules = [
        intree_module("drivers/leds/leds-pwm.ko"),
        intree_module("drivers/regulator/rt4801-regulator.ko"),
        intree_module("drivers/regulator/tps65132-regulator.ko"),
        intree_module("drivers/video/backlight/lp855x_bl.ko"),
        "//private/devices/google/felix/display:panel-samsung-ana6707-f10",
        "//private/devices/google/felix/display:panel-samsung-ea8182-f10",
        "//private/devices/google/lynx/display:panel-samsung-s6e3fc3-l10",
        "//private/devices/google/lynx/display:panel-samsung-s6e3fc5",
        "//private/devices/google/tangorpro/display:panel-boe-ts110f5mlg0",
        "//private/devices/google/tangorpro/display:panel-csot-ppa957db2d",
        "//private/google-modules/amplifiers/cs35l41:snd-soc-cs35l41",
        "//private/google-modules/amplifiers/cs35l41:snd-soc-cs35l41-spi",
        "//private/google-modules/amplifiers/cs35l43:snd-soc-wm-adsp",
        "//private/google-modules/amplifiers/cs35l45:cs35l45-cs-dsp",
        "//private/google-modules/amplifiers/cs35l45:snd-soc-cs35l45",
        "//private/google-modules/amplifiers/cs35l45:snd-soc-cs35l45-spi",
        "//private/google-modules/amplifiers/cs35l45:snd-soc-cs35l45-wm-adsp",
        "//private/google-modules/bms:google_dock",
        "//private/google-modules/display/samsung/panel:panel-boe-nt37290",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3fc3",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3fc3-p10",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc2",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc3",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc3-c10",
        "//private/google-modules/display/samsung/panel:panel-samsung-s6e3hc4",
        "//private/google-modules/display/samsung/panel:panel-samsung-sofef01",
        "//private/google-modules/gps/broadcom/bcm47765:bcm47765_ko",
        "//private/google-modules/nfc:st21nfc",
        "//private/google-modules/nfc/ese:st33spi",
        "//private/google-modules/nfc/ese:st54spi",
        "//private/google-modules/radio/samsung/s5300:cpif_ko",
        "//private/google-modules/radio/samsung/s5400:cp_thermal_zone",
        "//private/google-modules/radio/samsung/s5400:cpif_page",
        "//private/google-modules/radio/samsung/s5400:shm_ipc",
        "//private/google-modules/sensors/hall_sensor",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:pogo_transport",
        "//private/google-modules/soc/gs/drivers/video/backlight:rt4539_bl",
        "//private/google-modules/touch/common:heatmap",
        "//private/google-modules/touch/common:touch_bus_negotiator",
        "//private/google-modules/touch/common:touch_offload",
    ],
)

# For compatibility
alias(
    name = "dist",
    actual = ":gs201/dist",
)

alias(
    name = "kernel_compile_commands",
    actual = ":gs201/kernel_compile_commands",
)
