#ifndef USB_GADGET_DEFINES_H
#define USB_GADGET_DEFINES_H

#if IS_ENABLED(CONFIG_USB_GADGET_DEBUG)
#define DEBUG
#endif
#if IS_ENABLED(CONFIG_USB_GADGET_VERBOSE)
#define VERBOSE_DEBUG
#endif

#endif  // USB_GADGET_DEFINES_H
