# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "pixel_metrics",
    srcs = glob([
        "**/*.h",
    ]),
    out = "pixel_metrics.ko",
    conditional_srcs = {
        "CONFIG_CPUIDLE_METRICS": {
            True: [
                "cpuidle_metrics.c",
            ],
        },
        "CONFIG_PERF_METRICS": {
            True: [
                "perf_metrics.c",
            ],
        },
        "CONFIG_PIXEL_METRICS": {
            True: [
                "init_metrics.c",
            ],
        },
        "CONFIG_THERMAL_METRICS": {
            True: [
                "thermal_metrics.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/gs/drivers/soc/google/vh:headers",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:systrace",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_sched",
    ],
)
