# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = [
    "//private/devices/google:__subpackages__",
    "//private/google-modules:__subpackages__",
])

ddk_module(
    name = "mtk_pcimsg_google",
    srcs = [
        "mtk_pcimsg_google.c",
    ],
    out = "mtk_pcimsg_google.ko",
    copts = [
        "-include",
        "wwan_defines.h",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/radio/common/radio-bridge",
        "//private/google-modules/radio/mediatek/t900/wwan/tmi3:tmi3_headers",
        "//private/google-modules/radio/mediatek/t900/wwan/tmi3/pcie/customize/google:ddk_headers",
        "//private/google-modules/radio/mediatek/t900/wwan/tmi3/pcie/customize/google:radio_google",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/soc/rdo:rdo_soc_headers",
    ],
)

exports_files(
    ["Kconfig"],
    visibility = [
        "//private/google-modules/soc/rdo:__subpackages__",
    ],
)
