/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_BINDINGS_POWER_GENPD_MBU_H
#define __DT_BINDINGS_POWER_GENPD_MBU_H

#define GENPD_MBU_SSWRP_AOSS_AMBSS_ID 0
#define GENPD_MBU_SSWRP_AOSS_AONSS_ID 1
#define GENPD_MBU_SSWRP_AOSS_PG_ID 2
#define GENPD_MBU_SSWRP_AURDSP_ID 3
#define GENPD_MBU_SSWRP_BMSM_ID 4
#define GENPD_MBU_SSWRP_CODEC_3P_ID 5
#define GENPD_MBU_SSWRP_CPU_ID 6
#define GENPD_MBU_SSWRP_CPUACC_ID 7
#define GENPD_MBU_SSWRP_DPU_ID 8
#define GENPD_MBU_SSWRP_FABDISP_ID 9
#define GENPD_MBU_SSWRP_FABHBW_ID 10
#define GENPD_MBU_SSWRP_FABMED_ID 11
#define GENPD_MBU_SSWRP_FABSTBY_ID 12
#define GENPD_MBU_SSWRP_FABSYSS_ID 13
#define GENPD_MBU_SSWRP_G2D_ID 14
#define GENPD_MBU_SSWRP_GCV_ID 15
#define GENPD_MBU_SSWRP_GMC0_ID 16
#define GENPD_MBU_SSWRP_GMC1_ID 17
#define GENPD_MBU_SSWRP_GMC2_ID 18
#define GENPD_MBU_SSWRP_GMC3_ID 19
#define GENPD_MBU_SSWRP_GPCA_ID 20
#define GENPD_MBU_SSWRP_GPCM_AMB_ID 21
#define GENPD_MBU_SSWRP_GPCM_INFRA_ID 22
#define GENPD_MBU_SSWRP_GPU_ID 23
#define GENPD_MBU_SSWRP_GSA_ID 24
#define GENPD_MBU_SSWRP_HSIO_N_ID 25
#define GENPD_MBU_SSWRP_HSIO_S_ID 26
#define GENPD_MBU_SSWRP_ISPBE_ID 27
#define GENPD_MBU_SSWRP_ISPFE_ID 28
#define GENPD_MBU_SSWRP_LSIO_E_ID 29
#define GENPD_MBU_SSWRP_LSIO_S_ID 30
#define GENPD_MBU_SSWRP_MEMSS_ID 31
#define GENPD_MBU_SSWRP_PCIE_ID 32
#define GENPD_MBU_SSWRP_TPU_ID 33
#define GENPD_MBU_SSWRP_COUNT 34

#define GENPD_MBU_DPU_BE_ID 0
#define GENPD_MBU_DPU_FE0_ID 1
#define GENPD_MBU_DPU_FE1_ID 2
#define GENPD_MBU_DPU_DSI0_ID 3
#define GENPD_MBU_DPU_DSI1_ID 4
#define GENPD_MBU_DPU_DP0_ID 5
#define GENPD_MBU_DPU_SUBDOMAIN_COUNT 6

#define GENPD_MBU_G2D_CORE_ID 0
#define GENPD_MBU_G2D_SUBDOMAIN_COUNT 1

#define GENPD_MBU_GCV_GSE_ID 0
#define GENPD_MBU_GCV_GWE_ID 1
#define GENPD_MBU_GCV_CRE_ID 2
#define GENPD_MBU_GCV_SUBDOMAIN_COUNT 3

#define GENPD_MBU_GPU_CORE_LOGIC_ID 0
#define GENPD_MBU_GPU_SUBDOMAIN_COUNT 1

#define GENPD_MBU_HSIO_N_USB_ID 0
#define GENPD_MBU_HSIO_N_USB_PSW_ID 1
#define GENPD_MBU_HSIO_N_EBU_ID 2
#define GENPD_MBU_HSIO_N_DP_ID 3
#define GENPD_MBU_HSIO_N_USB2AUX_ID 4
#define GENPD_MBU_HSIO_N_USB2AUX_PSW_ID 5
#define GENPD_MBU_HSIO_N_SUBDOMAIN_COUNT 6

#define GENPD_MBU_HSIO_S_UFS_ID 0
#define GENPD_MBU_HSIO_S_SD_ID 1
#define GENPD_MBU_HSIO_S_UFS_PREP_ID 2
#define GENPD_MBU_HSIO_S_SUBDOMAIN_COUNT 3

#define GENPD_MBU_ISPFE_CORE0_ID 0
#define GENPD_MBU_ISPFE_CORE1_ID 1
#define GENPD_MBU_ISPFE_CORE2_ID 2
#define GENPD_MBU_ISPFE_CSIS_ID 3
#define GENPD_MBU_ISPFE_CSIS_DVDD0P75_ID 4
#define GENPD_MBU_ISPFE_CSIS_AVDD0P75_ID 5
#define GENPD_MBU_ISPFE_SUBDOMAIN_COUNT 6

#define GENPD_MBU_ISPBE_BTR0_ID 0
#define GENPD_MBU_ISPBE_BT0_HDR_ID 1
#define GENPD_MBU_ISPBE_BTR1_ID 2
#define GENPD_MBU_ISPBE_BTR2_ID 3
#define GENPD_MBU_ISPBE_MSA0_ID 4
#define GENPD_MBU_ISPBE_MSA1_ID 5
#define GENPD_MBU_ISPBE_YUV_ID 6
#define GENPD_MBU_ISPBE_SUBDOMAIN_COUNT 7

#define GENPD_MBU_LSIO_CLI_GPIO_ID 0
#define GENPD_MBU_LSIO_SUBDOMAIN_COUNT 1

#define GENPD_MBU_PCIE_SSWRP_ID 0
#define GENPD_MBU_PCIE_CTRL0_ID 1
#define GENPD_MBU_PCIE_CTRL1_ID 2
#define GENPD_MBU_PCIE_TOP_ID 3
#define GENPD_MBU_PCIE_DPA_ID 4
#define GENPD_MBU_PCIE_SUBDOMAIN_COUNT 5

#define GENPD_MBU_CPUACC_GPDMA_ID 0
#define GENPD_MBU_CPUACC_SSU_ID 1
#define GENPD_MBU_CPUACC_SUBDOMAIN_COUNT 2

#endif /* __DT_BINDINGS_POWER_GENPD_MBU_H */
